### ISSUE TITLE
This is not an issue, just adding pictures

### ISSUE THREAD

**Issue by tjanczuk** [tjanczuk/edge#1]
![fs ps py cs js](https://f.cloud.github.com/assets/822369/468830/a293c728-b6a3-11e2-9fb3-99c7bf2bf6ed.png)
![debug](https://f.cloud.github.com/assets/822369/190564/a41bab2c-7efb-11e2-878f-82ae2325876c.PNG)
![debug1](https://f.cloud.github.com/assets/822369/190566/c0a2d43c-7efb-11e2-9bb7-c11783204c66.PNG)
![jazz](https://f.cloud.github.com/assets/822369/190582/79ad0574-7efc-11e2-9d61-227ab70c37b4.PNG)
![rocknroll](https://f.cloud.github.com/assets/822369/190583/8151f190-7efc-11e2-92ab-dcbfffd96f35.PNG)
![exception](https://f.cloud.github.com/assets/822369/190735/51f14504-7f0b-11e2-8ea1-04f81fa406ff.PNG)
![clr2v8-2](https://f.cloud.github.com/assets/822369/234085/b305625c-8768-11e2-8de0-e03ae98e7249.PNG)
![welcome](https://f.cloud.github.com/assets/822369/266383/e6320302-8df7-11e2-94f3-45f3eca2979f.PNG)
![debug-inline](https://f.cloud.github.com/assets/822369/326781/923d870c-9b4a-11e2-8f45-201a6431afbf.PNG)
![py cs js](https://f.cloud.github.com/assets/822369/332372/da7e53ea-9c24-11e2-9fd4-a24f62c7115c.png)
![edgejs-performance1](https://f.cloud.github.com/assets/822369/486393/645f696a-b920-11e2-8a20-9fa6932bb092.png)

**Comment by tjanczuk** [comment]
![image](https://cloud.githubusercontent.com/assets/822369/11969625/2bc97e4e-a8d1-11e5-8717-60ab1206765f.png)

**Comment by tjanczuk** [comment]
![image](https://cloud.githubusercontent.com/assets/822369/11969640/66e0b86c-a8d1-11e5-9999-3ae4d9fb03c5.png)

**Comment by tjanczuk** [comment]
![image](https://cloud.githubusercontent.com/assets/822369/11969685/e9476f3a-a8d1-11e5-94d4-847bfc4ed960.png)

**Comment by paulcbetts** [comment]
lolwat
