### ISSUE TITLE
Install failure on MacOS

### ISSUE THREAD

**Issue by MattDrivenDev** [tjanczuk/edge#134]
I've had a search on both Google and in the issues of this repo for some help already - but drawn a blank.

I'm getting the following error when trying to install `edge`:

``` shell
Package mono-2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `mono-2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'mono-2' found
gyp: Call to 'pkg-config mono-2 --libs' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:340:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Darwin 13.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/matt/Repositories/node-app/node_modules/edge
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
edge@0.8.0 node_modules/edge
└── edge-cs@0.2.5
```

I'm running with:
- OSX 10.9.2
- Node 0.10.28
- Mono 3.4.0 (built from the `brew install` script listed as part of the MacOS instructions in the readme).

Any help suggested would be awesome - perhaps something I can fix as well.

**Comment by jwhitmarsh** [comment]
For anyone coming across this now, check you haven't got pkg-config installed in `/opt/local/bin/` which may well be taking precedence over the brew installed version.

If you have, I fixed it by simply renaming (because I'm a wuss) `/opt/local/bin/pkg-config` to `/opt/local/bin/pkg-config-old` and then the brew link to `/usr/local/bin/pkg-config` worked.

**Comment by stephan-nordnes-eriksen** [comment]
@jwhitmarsh How do you do this `brew link`? I have tried with no luck.

**Comment by jwhitmarsh** [comment]
I just ran `brew link /usr/local/bin/pgk-config/`as I said in my comment - presumably you're getting an error? Or did the link work? Check your linked kegs with `ls /usr/local/Library/LinkedKegs/`, you should see /pkg-config in there

**Comment by stephan-nordnes-eriksen** [comment]
@jwhitmarsh Looked like I did something wrong in the install process. I got pgk-config to work. And, well, mono does not appear to work on osx anyways(https://github.com/tjanczuk/edge/issues/182) :(

**Comment by jwhitmarsh** [comment]
It does work mate - I got there in the end. Running OSX 10.10.3, and mono
<img width="638" alt="screen shot 2015-08-12 at 22 16 42" src="https://cloud.githubusercontent.com/assets/8026009/9236939/d8a35f58-413f-11e5-923e-73456f990186.png">

**Comment by stephan-nordnes-eriksen** [comment]
Ok, I get that too. But I still get `No package 'mono-2' found` when i run `npm install edge`. 

I found that running `export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig` solved my issue :fireworks:

**Comment by gabrielstuff** [comment]
Here is what helped on my side: 

```
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:/Library/Frameworks/Mono.framework/Versions/5.10.1/lib/pkgconfig:$PKG_CONFIG_PATH
```
