### ISSUE TITLE
mscorlib.dll not found error running on OSX

### ISSUE THREAD

**Issue by reverentgeek** [tjanczuk/edge#140]
I followed the readme instructions to get Edge.js installed on OSX. It appeared to compile and all tests passed. However, when I try to run my own project, I'm getting the following error:

```
The assembly mscorlib.dll was not found or could not be loaded.
It should have been installed in the `/usr/local/Cellar/node/0.10.26/lib/mono/4.5/mscorlib.dll' directory.
```

I don't know why it would be looking mscorlib.dll in that path, and I assume that's the problem. However, I don't know how to get Node.js or Edge.js to look in the correct path for mono .NET assemblies. Any suggestions?

**Comment by krzkaczor** [comment]
I got it working by installing mono by brew and using it in pkg (of course i have also reinstalled edge)

    export PKG_CONFIG_PATH=/usr/local/Cellar/mono/4.0.2.5/lib/pkgconfig

Thanks for tips guys!
