### ISSUE TITLE
Reference external assembly not working on linux

### ISSUE THREAD

**Issue by chris-ray** [tjanczuk/edge#141]
I'm having an issue getting a simple assembly reference to work on linux (the code runs on Windows just fine)

Here's the app.js file. The Novell.Directory.Ldap.dll file is sitting right next to it, those are the only two files in the directory.

```
var edge = require('edge');

var hello = edge.func({
  source: function() {/*
        using System;
        using System.Reflection;
        using System.Threading.Tasks;
        using Novell.Directory.Ldap;
        public class Startup
        {
            public async Task<object> Invoke(object input)
            {
                var conn = new Novell.Directory.Ldap.LdapConnection();
                return "CSharp welcomes " + input.ToString();
            }
        }
  */},
  references: [ 'System.Data.dll', 'Novell.Directory.Ldap.dll' ]
});

hello('Node.js', function (error, result) {
    if (error) throw error;
    console.log(result);
});
```

On windows the output of `node app` is simply: 

> CSharp welcomes Node.js

but the output on linux is

> ```
> undefined:1
> (function (f, ctx) { return function (d, cb) { return f(d, cb, ctx); }; })
>                                                       ^
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
>   at EdgeCompiler.CurrentDomain_AssemblyResolve (System.Object sender, System.ResolveEventArgs args) [0x00000] in <filename unknown>:0
>   at System.AppDomain.DoAssemblyResolve (System.String name, Boolean refonly) [0x00000] in <filename unknown>:0
>   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.Object].Start[<Invoke>c__async0] (<Invoke>c__async0& stateMachine) [0x00000] in <filename unknown>:0
>   at Startup.Invoke (System.Object input) [0x00000] in <filename unknown>:0
>   at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
>   at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0
>   --- End of inner exception stack trace ---
>   at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0
>   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0
>   at EdgeCompiler+<>c__DisplayClass1.<CompileFunc>b__0 (System.Object input) [0x00000] in <filename unknown>:0
> ```

Note that if I simply comment out the `var conn = new Novell.Directory.Ldap.LdapConnection();` line, the program runs flawlessly on linux as well.

**Comment by ericrini** [comment]
Having the same issue on OSX. Wondering if this might have something to do with / vs. \ as a path delimiter.

**Comment by anthonyguertin** [comment]
tjanczuk I am having this exact issue as well, have spent several hours trying to solve the issue. Not sure what is causing this error. I am on Windows but verbatim, I am getting the same reference error.
