### ISSUE TITLE
Edge.js 0.9.0 seems to make nodewebkit crash upon invocation (Windows)

### ISSUE THREAD

**Issue by tamstrup** [tjanczuk/edge#152]
Hi

I have until a few days ago used Edge.js 0.7.14, which worked fine. Because of the problem I mentioned in #146 (supporting non-English characters in object attribute names), I decided to move to 0.9.0. Sadly, this version makes nodewebkit crash.

I used `git bisect` to find which commit is the culprit, and it seems to be ad837562ef48b199a9c35b44d1d1b8eebccf7335.

The crash can be reproduced by starting nodewebkit, invoking a .NET method through Edge.js and just waiting a while. Furthermore, it seems that if you open nodewebkit's devtools after invoking a .NET method, it crashes right away. The crash does not happen if the C# code for the method is written inline - only when the invoked method is located within an assembly.

Steps to reproduce:
- Download and extract NodeWebkit 0.8.6: http://dl.node-webkit.org/v0.8.6/node-webkit-v0.8.6-win-ia32.zip
- Run `npm install edge` in the folder where `nw.exe` from the aforementioned ZIP-file resides.
- Use `nw-gyp` to build Edge.js:

``` bash
npm install -g nw-gyp
cd node_modules/edge
nw-gyp configure --target=0.8.6
nw-gyp build
cp build/Release/edge.node lib/native/win32/ia32/0.10.0/edge.node
```
- Write the following C# file:

``` cs
namespace EdgeCrash {
    using System.Threading.Tasks;
    public class Example {
        public async Task<object> Invoke(dynamic data) {
            return "Example.";
        }
    }
}
```
- Compile the C# file: `csc /target:library /out:example.dll example.cs`
- Put the following HTML in `index.html`:

``` html
<html>
    <head>
        <title>Edge Crash</title>
        <script>
            function invoke() {
                var edge = require('edge');
                var f = edge.func({
                    assemblyFile: 'example.dll',
                    typeName: 'EdgeCrash.Example'
                });
                console.log(f(null, true));
            }
        </script>
    </head>
    <body>
        <button onclick="invoke()">Print</button>
    </body>
</html>
```
- Create a `package.json` file:

``` json
{
  "main": "index.html",
  "name": "edgecrash",
  "description": "Edge crash",
  "version": "0.1.0",
  "window": {
    "show": true,
    "title": "Edge Crash",
    "toolbar": true,
    "frame": true,
    "width": 960,
    "height": 640
  }
}
```
- Run `nw.exe`, click the _Print_ button and subsequently open devtools by clicking the toolbar button with three lines.

Thanks in advance,
Patrick

**Comment by tjanczuk** [comment]
Edge.js 0.10.0 that just shipped supports Node 0.12. Does this make supporting node-webkit easier?
