### ISSUE TITLE
node install edge: compilation error on osx

### ISSUE THREAD

**Issue by flq** [tjanczuk/edge#160]
Greetings,
after some troubleshooting, following guidelines in [xcode-select active developer directory error on OSX Mavericks](http://stackoverflow.com/questions/17980759/xcode-select-active-developer-directory-error-on-osx-mavericks), I am still stuck with a compilation error, and sadly I am stuck whether this is legit or due to some version confusion somewhere along the way...

```
franks-mbp:edgeplay flq$ npm install edge
npm WARN package.json edgeplay@0.0.1 No repository field.
npm WARN package.json edgeplay@0.0.1 No README data
npm http GET https://registry.npmjs.org/edge
npm http 304 https://registry.npmjs.org/edge
npm http GET https://registry.npmjs.org/edge-cs
npm http 304 https://registry.npmjs.org/edge-cs

> edge@0.9.0 install /Users/flq/Documents/src/Node/edgeplay/node_modules/edge
> node tools/install.js

  CXX(target) Release/obj.target/edge/src/mono/clractioncontext.o
In file included from ../src/mono/clractioncontext.cpp:1:
../src/mono/edge.h:138:47: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static Handle<v8::Value> Initialize(const v8::Arguments& args);
                                              ^~~~~~~~~~~~~
                                              v8::internal::Arguments
/Users/flq/.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
1 error generated.
make: *** [Release/obj.target/edge/src/mono/clractioncontext.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/flq/.nvm/v0.11.13/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Darwin 13.2.0
gyp ERR! command "node" "/Users/flq/.nvm/v0.11.13/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/flq/Documents/src/Node/edgeplay/node_modules/edge
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
edge@0.9.0 node_modules/edge
└── edge-cs@0.2.5
```

If anybody knows what to do about this, my knowledge on what is going on there is rather limited, but it looks like some API change somewhere...

**Comment by OlegBoulanov** [comment]
v 0.12.0:

$ npm install edge
\
> edge@0.9.3 install /Users/a/Projects/EdgeTest/node_modules/edge
> node tools/install.js

child_process: customFds option is deprecated, use stdio instead.
/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config mono-2 --libs' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/a/Projects/EdgeTest/node_modules/edge
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

**Comment by thinking-aloud** [comment]
with edge@0.10.1 I managed to get edge working with node v0.12.0. I think the ticket can be closed.

**Comment by flq** [comment]
Well then, this is so stale, I'll close it
