### ISSUE TITLE
Assemblies in NuGet package aren't signed

### ISSUE THREAD

**Issue by Fraegle** [tjanczuk/edge#170]
The assemblies coming with the NuGet package aren't signed. This means signed assemblies can't depend on them. 
To be able to use Edge.js with other signed assemblies, please update the NuGet package on NuGet.org with signed assemblies. 
Thank you very much in advance.

**Comment by tjanczuk** [comment]
I am not planning to provide a signed version of Edge.js NuGet package at this time.
