### ISSUE TITLE
Crashing with exit code 0x8

### ISSUE THREAD

**Issue by Code0987** [tjanczuk/edge#176]
This call inside a plain node's `http.createServer`'s `).listen(...` as explained [on](https://github.com/tjanczuk/edge#how-to-expose-nodejs-state-to-net), is crashing node+edge's thread inside .Net CLR with exit code **`0x8`**, thus' crashing whole .Net based application, when run normally from Desktop or Windows Explorer or CMD.

``` javascript
module.exports = function (data, callback) {
    var http = require("http"),
        url = require("url"),
        path = require("path"),
        fs = require("fs");

        var server = http.createServer(function (request, response) {

            response.end("Hello from edge (node inside .Net CLR) ! It's " + new Date() + ".");

        }).listen(data.port, function () {
            /* 

            // This is crashing app !
            callback(null, function (data, callback) {
                server.close();
                callback();
            });

            */
        });
};
```

While, everything works when I `Debug` (_i.e. launch app with debugger attached from VS2013 Debug button, with native debugging enabled_).

It still crashes when debugger is attached after launching app manually.

Please, can some one explain this thing? Have I missed anything ?

**Comment by RemiNV** [comment]
Using the NuGet package v0.10.0, I still get this error when running in a Windows service application.
Here is the JS code I am using:


    return function(data, callback) {
        "use strict";

        var Sandbox = require("sandbox");
        var sb = new Sandbox();
        sb.run("");
    };

Using the workaround you posted before works, though.

**Comment by romanbetik** [comment]
Your proper fix does not work for me either. I'm calling edge.js from WPF application. I found out that adding one extra line in your fix in double_edge.js makes it work:

this works for me:
```
try {
   var stdout = process.stdout;
   var stderr = process.stderr;
}
```
instead of just
```
try {
   var stdout = process.stdout;
}
```
at the beginning of the double_edge.js file.
