### ISSUE TITLE
Crashing App Pool in IIS 8.0

### ISSUE THREAD

**Issue by bcanzanella** [tjanczuk/edge#178]
Below I created an empty web project with one page, and used Nuget to install Edge.js. With Visual Studio 2013 I start it up using IIS Express, and it works fine (it prints 'hello world'). When I create a new web site in the IIS manager, give it an app pool, and setup a host name (edgetest.com) and point to this code, I get a series of errors in the Event Viewer like...

> A process serving application pool 'edgetest.com' suffered a fatal communication error with the Windows Process Activation Service. The process id was '9696'. The data field contains the error number.

... and the app pool eventually crashes without any exceptions. Any ideas on what might be going on?

machine info : Windows 8.0, IIS 8, node v0.10.30

```
<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="WebApplication1.Default" %>
<%@ Import Namespace="EdgeJs" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<body>
    <%
        var fn = Edge.Func(@"
                return function(message, callback) {          
                    return callback(null, 'hello ' + message);
                }");
        Response.Write(fn("world").Result);
    %>
</body>
</html>
```

**Comment by asednev** [comment]
I ran into similar issue and after extensive troubleshooting I discovered this was related to #247. Installing VC++ Redist for VS 2013 on web server solved the problem.

**Comment by MattyBoy4444** [comment]
Installing VC++ redist for 2013 on Windows Server 2012 ALSO fixed my issue.  Thanks!

**Comment by helmutkian** [comment]
Installing "Visual C++ Redistributable Packages for Visual Studio 2013" on the server fixed this issue for me too.

**Comment by mitchogaard** [comment]
Wow. Another +1 on the **_x86_** VC++ redist.

**Comment by justinhp** [comment]
Had the same issue, started installing VC++ 2015.  That didn't fix it so installed VC++ 2013 and it works!!!!

**Comment by bodell** [comment]
+1 on Visual C++ Redistributable (x64).  Solved my issue of not being able to run app in a 64 bit app pool.
