### ISSUE TITLE
AppDomain unload issue

### ISSUE THREAD

**Issue by pcibraro** [tjanczuk/edge#195]
It looks like Edge is preventing the application domain where is executed from being unloaded. I created a simple application to repro the issue, it's here. https://gist.github.com/pcibraro/1dadbf99eff02df7ed90
I noticed this issue while trying to run unit tests in Visual Studio or the CI server. The app domain created by the test runner gets blocked, so you are not able to re-execute the tests once they ran.

Thanks

**Comment by Metallium** [comment]
Having the similar issue with unloading: ReSharper Task Runner running xUnit tests fails in the end of execution with FatalEngineExecutionError on

edge.node!<Module>._exit_callback()
...
(omitted 3 items)
...
edge.node!<CrtImplementationDetails>.ModuleUninitializer.SingletonDomainUnload(...)

could c# Edge.Func possibly become IDisposable and unload correctly?

**Comment by akshaybheda** [comment]
any Updates on this issues?
