### ISSUE TITLE
ASP.NET & IIS

### ISSUE THREAD

**Issue by mauriciogentile** [tjanczuk/edge#208]
No error in the Event Viewer after application crashes on ASP.NET over IIS.
No Exception thrown in debugging mode (VS 2012), only this output:

The program '[10480] w3wp.exe: Managed (v4.0.30319)' has exited with code 8 (0x8).

Environment:
- IIS 7.5
- Windows 7 Enterprise
- .NET Framework 4.5
- ApplicationIdentityPool
- Edge.js.0.9.2

Reproduced in two machines with similar configurations, same issue, no clue.
Works fine with app console.

I'd appreciate any guidance on this.

Thanks!

**Comment by asednev** [comment]
I ran into similar issue and extensive troubleshooting I discovered this was related to https://github.com/tjanczuk/edge/issues/247. Installing VC++ Redist for VS 2013 on web server solved the problem.
