### ISSUE TITLE
Does Edge Work with Visual Basic or Only C# For Now

### ISSUE THREAD

**Issue by pworder** [tjanczuk/edge#214]
Does Edge Work with Visual Basic or Only C# For Now? Just asking because the VB to C# converters online aren't perfect.

**Comment by Jabark** [comment]
I have taken a copy of edge-cs and attempted a conversion to VB https://github.com/Jabark/edge-vb. I'm new to github/npm publishing so I'm happy for it be torn apart and stuck back together again ;D.

**Comment by tjanczuk** [comment]
Great job, VB away!
