### ISSUE TITLE
Installing Edge.Js from nuget

### ISSUE THREAD

**Issue by msuntharesan** [tjanczuk/edge#216]
Trying to install the Edge.Js nuget package and it seem to be stuck on a loop
From Package manager Console

PM> install-Package Edge.js
Installing 'Edge.js 0.9.2'.
Successfully installed 'Edge.js 0.9.2'.
Adding 'Edge.js 0.9.2' to Web.
Successfully added 'Edge.js 0.9.2' to Web.
Try set double_edge.js
RecurseOn double_edge.js
Try set 
RecurseOn 
Try set 
RecurseOn 
Try set 
RecurseOn 
Try set 
RecurseOn 
Try set 
RecurseOn 
Try set 

That keeps on repeating.

**Comment by cchamberlain** [comment]
I got this, also in a website project.

**Comment by DoubleCouponDay** [comment]
same problem. its using up a lot of my system resources.

**Comment by chaitanyabd** [comment]
Bug still present as of 2019.

**Comment by agracio** [comment]
New nuget package from https://github.com/agracio/edge-js should be used instead.
