### ISSUE TITLE
Failing to load express dependencies

### ISSUE THREAD

**Issue by whrami** [tjanczuk/edge#217]
Hello,
Great work on this library, first off. :)
I just ran into some trouble. I had build out an express.js server all in one file which I was sucking into C# via Edge.Func(File.ReadAllText("c:\xyz.js"));..

I just finished splitting all of that file out into respective node module files, with a folder structure, and suddenly the dependencies are failing to load. Specifically I'm being told that 'debug' cannot be found (a dependency of the express module). I can locate the debug files beneath bin/Debug/edge/node_modules/express/node_modules/debug/_._.

Do you know what I can do about this?

**Comment by FrankCummins** [comment]
Hi @tjanczuk ,

Thanks for all you've done here. Just a point of clarification: the entire **node_modules** folder goes inside the same folder as EdgeJs.dll (Debug or Release)?

Do I just need to copy and paste the folder into this directory?

In case it's helpful, I'm trying to use noble to pass BTLE characteristic data to/from C# using EdgeJs. 

Thanks for any clarification you can provide!
