### ISSUE TITLE
Multi edge

### ISSUE THREAD

**Issue by larwin** [tjanczuk/edge#218]
Hello Tomasz,
Is there a way to run "multiple instances" of edge in c# ?

I would like to do somehing like that :

var edge1 = new Edge();
var fn1 = edge1.Func(@"while(true){}");

var edge2 = new Edge();
var fn2 = edge2.Func(@"while(true){}");

Thanks

**Comment by tjanczuk** [comment]
No, it is only possible to run a single "instance" of Node.js per CLR process. This is due to how Node.js is designed: there is only one global event loop.
