### ISSUE TITLE
Ubuntu 14.04 with mono failing to execute simple query

### ISSUE THREAD

**Issue by exilonX** [tjanczuk/edge#222]
I have added this issue https://github.com/tjanczuk/edge-sql/issues/12 to the edge-sql repository and I am not sure if the problem is from edge or edge-sql... For more details please check the issue from edge-sql.

**Comment by btleffler** [comment]
Mono doesn't seem to provide `System.Data.SqlClient.SqlCommand::ExecuteReaderAsync` which is what edge-sql relies on.

Have you been able to figure anything out, @exilonX?
