### ISSUE TITLE
Jxcore compatibility

### ISSUE THREAD

**Issue by gberthalon** [tjanczuk/edge#225]
Hi,

An exception occurs with jxcore exceution : http://jxcore.com/home/
My app works fine with node.js 10.0.22

this is my exception :
unhandled exception : System.AccessViolationException : Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at continueOnV8Thread(uv_async_s* handle, Int32 status)

Have you got an idea to solve this problem?

**Comment by tjanczuk** [comment]
I am not sure if there is anything actionable for Edge.js here. Please re-open with specifics if there is.

**Comment by ktrzeciaknubisa** [comment]
Hi guys, we've merged our former jxdocs repository into [jxcore](https://github.com/jxcore/jxcore). The link mentioned above by @tjanczuk to native docs became obsolete. This is actual one: https://github.com/jxcore/jxcore/tree/master/doc/native.
