### ISSUE TITLE
EdgeJS fails on Win2008 R2

### ISSUE THREAD

**Issue by subbaraot** [tjanczuk/edge#228]
A simple C# console application fails to run on a Windows 2008 R2 server with .Net 4.5.2 and VC++ 2013 Redist installed.

The code is below
class Program
    {
        static Func<object, Task<object>> func = Edge.Func(@"
            return function (data, callback) {
                callback(null, 'Node.js ' + process.version + ' welcomes ' + data);
            }
        ");

        static void Main(string[] args)
        {
            try
            {
                var result = func(".Net");
                Console.WriteLine(result.Result);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }

            Console.Read();
        }
    }

This is the error message

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: The specified module could not be found.
C:\Users\Subbarao.Turlapati\Desktop\EdgeTest\edge\x86\edge.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Subbarao.Turlapati\Desktop\EdgeTest\edge\edg
e.js:40:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Any help will be appreciated!

**Comment by subbaraot** [comment]
It was my bad. The application was compiled with "Any CPU" and was always loading the x86 version of the edge.node. I changed the target to x64 and it worked!

**Comment by SparserLogic** [comment]
I'm getting this error but the build target is set properly.

**Comment by subbaraot** [comment]
I just ran into a similar error (I'm not yet sure if it is the exact same error) on a different server that I'm trying to set up. The build target is x64 but the application still fails. Will update if I get it to work.
