### ISSUE TITLE
How do I build it?

### ISSUE THREAD

**Issue by polkovnikov-ph** [tjanczuk/edge#236]
The `edge.node` file supplied is for Node 0.10.0. I'd like to use `edge` with Node 0.11 and Node 0.12. How do I build it?

I've tried running `node-gyp` in the root folder and it died, claiming that `v8` namespace doesn't contain `Arguments`. Should I use some version of `v8` sources different from the one that is supplied with `node-gyp`?

**Comment by webarchymeta** [comment]
I am having the same question. When will the code be updated so that it can be compiled for node 0.12?

**Comment by footmarksadmin** [comment]
yes I'm also wondering when 0.12 will be supported.

**Comment by tjanczuk** [comment]
I am planning on releasing a version that supports 0.12 within a week.

**Comment by polkovnikov-ph** [comment]
@tjanczuk Thank you!

**Comment by footmarksadmin** [comment]
@tjanczuk Sweet! We are anxiously waiting for it's arrival !! :)

**Comment by tjanczuk** [comment]
Edge.js 0.10.0 that just shipped supports Node 0.12.
