### ISSUE TITLE
Roadmap for edge?

### ISSUE THREAD

**Issue by jamietre** [tjanczuk/edge#239]
I just started playing around with Edge recently and it's an amazing library with endless potential uses. I was wondering if you could speak to the state of the project. It seems like activity has slowed down a little bit lately -- the last nuget release was 6 months ago and is also behind the last release on github. There seems to be some unresolved/possibly showstopping issues, particularly when using it with IIS which is my intention. So I am a bit concerned about investing too much in code that would be used in production without having a better understanding of the current state and where Edge is going. 

Thanks for any info you can provide. It's been so much fun to play with and I hope to see it continue!

**Comment by tjanczuk** [comment]
Generally speaking I am committed to maintaining Edge. I am planning to release a new version of Edge with support for Node.js 0.12 within a week. Which are the showstopping issues with IIS you are referring to?

**Comment by DasAng** [comment]
Hi @tjanczuk. That is great news! Looking forward to support for node 0.12

**Comment by jamietre** [comment]
Hi, thanks for responding, and that is great to hear! The issues that worried me were:

Issue #215 - Edge.Func hangs
Issue #208 - ASP.NET & IIS

I am evaluating approaches to using Javascript libraries to support .NET web services and HTTP handlers that ideally would use code that is better supported (or exists at all) in the JS world vs the .NET world. I would much rather use Edge than work directly with a V8 wrapper, which seems much cleaner and allows me to take advantage of the whole node.js ecosystem instead of dealing with code intended to be run in a browser.

**Comment by outofobscure** [comment]
this seems to be the same problem: https://github.com/tjanczuk/edge/issues/237

**Comment by tjanczuk** [comment]
Edge.js 0.10.0 that just shipped supports Node 0.12. I am going to close this issue as the other bugs are already covering problems with running under IIS.

**Comment by jamietre** [comment]
Fantastic! Thanks!
