### ISSUE TITLE
Debugging NodeJS Javascript that is running within a C# Module and Process

### ISSUE THREAD

**Issue by joevolcano** [tjanczuk/edge#240]
Can/How does one debug javascript via a chrome browser inspector using something like WEINRE or similar when it is running within a C# .NET process using EdgeJS?

Thanks

**Comment by tjanczuk** [comment]
I have not tried but I suspect it may not be currently possible. Edge starts the Node runtime hosted in a CLR process here: https://github.com/tjanczuk/edge/blob/master/src/double/dotnet/EdgeJs.cs#L79. I suspect changes would be required to conditionally pass in debugging options there. Ideas/PRs welcome.

**Comment by IntranetFactory** [comment]
I'd tested the code shown in https://github.com/tjanczuk/edge/issues/163 in the past and it allowed to debug the JavaScript code with NodeInspector as usual.

**Comment by joevolcano** [comment]
That's excellent. I hope it can be made as a configurable variable so one
could Iive debug executing code without restarting the c# app.

I'd tested the code shown in #163
<https://github.com/tjanczuk/edge/issues/163> in the past and it allowed to
debug the JavaScript code with NodeInspector as usual.

—
Reply to this email directly or view it on GitHub
<https://github.com/tjanczuk/edge/issues/240#issuecomment-75394245>.

**Comment by tjanczuk** [comment]
The fix for this is to use the `EDGE_NODE_PARAMS` environment variable to pass whatever command line parameters you would normally invoke node.exe with, including `--debug`. 

This will ship as Edge.js Nuget package 0.10.0
