### ISSUE TITLE
Windows Server 2008 R2 Standard x64 Edge not loading

### ISSUE THREAD

**Issue by davidTurczi** [tjanczuk/edge#242]
I pretty much ran into the exact same problem as described here: http://stackoverflow.com/questions/27929164/edgejs-fails-on-win2008-r2
Did what he suggested (I'm building on a different machine (win 7), dunno if that's relevant or not), but only thing that changed is that the error message is now looking for /x64/edge.node but it's still failing.

It works on my Win 7 machine.

**Comment by davidTurczi** [comment]
Further investigation:
On a Windows 7 Enterprise x64 machine, with 32-bit build it works perfectly, but with 64-bit it quits as soon as the javascript code attepts to load [mongodb](https://github.com/mongodb/node-mongodb-native). I don't know if the two issues are related or not, it seems that on 2008R2 it doesn't even get as far as executing the javascript code.

**Comment by ludoviclefevre** [comment]
Hi,

See my comment: https://github.com/tjanczuk/edge/issues/247#issuecomment-77590089

does it solve your problem?

Ludovic LEFEVRE

**Comment by tjanczuk** [comment]
Edge 0.10.1 just shipped and it should fix the issue. Can you take it for the spin?

**Comment by davidTurczi** [comment]
It solves the node -> clr problem, but not the clr->node one. Can you release 0.10.1 nuget package too?

**Comment by tjanczuk** [comment]
Isn't the NuGet package used in the context of VS, in which case the dll dependencies would already be on the machine?

**Comment by RaghuGV7** [comment]
Hi tjanczuk,

In windows server 2008/2008 r2/2012 does not have msvcp120.dll and msvcr120.dll  by default. So when someone tries to deploy app on server it throws error. 

The only fix for this is to install http://www.microsoft.com/en-us/download/details.aspx?id=40784 as you already mentioned in https://github.com/tjanczuk/edge/issues/247
