### ISSUE TITLE
Latest node and edge not working

### ISSUE THREAD

**Issue by janvsc** [tjanczuk/edge#245]
I installed latest nodejs v0.12.0 and latest edge 0.9.3 and I get this in my C# project:

![image](https://cloud.githubusercontent.com/assets/6188515/6474658/766630ba-c24e-11e4-8ba9-512ed40c9eb9.png)

Please help

**Comment by tjanczuk** [comment]
?Edge 0.9.3 does not support node 0.12. Edge 0.10.0 that shipped a few days ago does. Make sure you install edge 0.10.0.


________________________________

**Comment by janvsc** [comment]
Thank you - All fixed up now

*Jan van Schalkwyk*
