### ISSUE TITLE
Version 0.10.0 npm install and run error

### ISSUE THREAD

**Issue by exilonX** [tjanczuk/edge#246]
I have tried the latest version of edge and I have some problems using it.

The first problem is when I run npm install: 
***************************************
[Error: The specified module could not be found.
C:\ARMONIA\AplicatiiWeb\ArmoniaUPU\FisaUPU\node_modules\edge1\lib\native\win32\x64\0.10.0\edge.node]
***************************************

The second problem is when I try to start the server:
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: The specified module could not be found.
C:\ARMONIA\AplicatiiWeb\ArmoniaUPU\FisaUPU\node_modules\edge\lib\native\win32\x64\0.10.0\edge.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\ARMONIA\AplicatiiWeb\ArmoniaUPU\FisaUPU\node_modules\edge\lib\edge.js:41:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by kulwinder156** [comment]
There are few team members from my team who installed today has been faced  this error. But yet no solution.

**Comment by davidTurczi** [comment]
While trying to narrow down the cause for my problem (of calling node from C#, see https://github.com/tjanczuk/edge/issues/242), I did a small repro of a few lines calling C# from node and vica versa. When the host application was node, the second error was the same error as I got.

**Comment by blackshadev** [comment]
I updated to the latest Edge and faced this issue as well.

**Comment by tjanczuk** [comment]
I am unable to reproduce this on Windows 8. 

What is the OS version?

Can you try running [Process Monitor](https://technet.microsoft.com/en-us/library/bb896645.aspx) to see if any errors are reported while node loads the edge module? (e.g. missing DLL dependencies)

**Comment by blackshadev** [comment]
I had this issue on both windows 7 and windows server 2008 R2. But I will only have access to these machines next Tuesday. So I will check the process monitor then.

**Comment by tjanczuk** [comment]
Edge 0.10.1 just shipped and it should fix the issue. Can you take it for the spin?

**Comment by blackshadev** [comment]
It works, thanks.
