### ISSUE TITLE
Edge Fails to load or install cleanly on Windows 2008 R2

### ISSUE THREAD

**Issue by SparserLogic** [tjanczuk/edge#247]
Installation gives the following message:

***************************************
[Error: The specified module could not be found.
C:\Users\bahammon\Desktop\CircuitCommentProcessing\node_modules\edge\lib\native\
win32\x64\0.10.0\edge.node]
***************************************
Success: platform check for edge.js: node.js x64 v0.10.26
edge@0.10.0 node_modules\edge
├── nan@1.7.0
└── edge-cs@0.2.7

And trying to run an otherwise tested application gives the following error:

CircuitCommentProcessing\bin\Release\

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: The specified module could not be found.

C:\Users\bahammon\Desktop\CircuitCommentProcessing\node_modules\edge\lib\native\win32\x64\0.10.0\edge.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\bahammon\Desktop\CircuitCommentProcessing\node_modules\edge\lib\edge.js:41:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
error: Forever detected script exited with code: 8

I verified that this file exists:
C:\Users\bahammon\Desktop\CircuitCommentProcessing\node_modules\edge\lib\native\win32\x64\0.10.0\edge.node

And manually installed the latest .Net framework and verified its configuration. Help?

**Comment by tjanczuk** [comment]
I am unable to reproduce this on Windows 8. 

What is the OS version?

Can you try running [Process Monitor](https://technet.microsoft.com/en-us/library/bb896645.aspx) to see if any errors are reported while node loads the edge module? (e.g. missing DLL dependencies)

**Comment by SparserLogic** [comment]
I solved it by installing the previous version. It has something to do with
the latest release.

**Comment by davidTurczi** [comment]
Is it related to https://github.com/tjanczuk/edge/issues/246 and https://github.com/tjanczuk/edge/issues/242?

**Comment by SparserLogic** [comment]
Yes, I believe it is. Close as a dupe?

**Comment by davidTurczi** [comment]
Well as long as the others are fixed :)

**Comment by ludoviclefevre** [comment]
Hi thomasz,

I had the same error on a Windows 2008 Server R2. My app worked on windows 7.

When I launched process monitor on server and i saw a problem when trying accessing msvcp120.dll. So I took this file from my computer and put it to node_modules\edge\lib\native\win32\x64\0.10.0 directory on server and it worked.

 What's your opinion about that?

Ludovic

**Comment by tjanczuk** [comment]
@ludoviclefevre splendid, thank you for the data. Yes upon further investigation it appears msvcp120.dll is a new native dependency of edge 0.10.0 compared to 0.9.x. This is likely due to a major refactoring of code to use `nan` in order to support node 0.12. nan must have taken dependency on msvcp120.dll. 

I agree the proper fix is to ship edge with msvcp120.dll. I the meantime a workaround of installing [VC++ Redist for VS 2013](http://www.microsoft.com/en-us/download/details.aspx?id=40784) should also do the  trick.

**Comment by tjanczuk** [comment]
Edge 0.10.1 just shipped and it should fix the issue. Can you take it for the spin?

**Comment by SparserLogic** [comment]
All fixed, thanks!

**Comment by tjanczuk** [comment]
Great, thanks for confirming.
