### ISSUE TITLE
edge + entity framework

### ISSUE THREAD

**Issue by mdavid5** [tjanczuk/edge#249]
Hi, I have a problem with edge js  when I am trying use an object with lists.

(I have tested it with a simple console app without any problem)

The scenario is the following: 
- entity framework generated classes
- simple get method
- node js dies on stackoverflow exception (I guess edge js handles something badly)

code:

The class: 

namespace DataLayerLibrary
{
    using System;
    using System.Collections.Generic;

```
public partial class User
{
    public User()
    {
        //this.Restaurant = new HashSet<Restaurant>();
        //this.Search = new HashSet<Search>();
        //this.UserLocation = new HashSet<UserLocation>();
    }

    public int UserId { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }
    public string PasswordHash { get; set; }
    public int UserTypeId { get; set; }

//These properties cause the StackOverflow Exception ... somehow

    //public virtual ICollection<Restaurant> Restaurant { get; set; }
    //public virtual ICollection<Search> Search { get; set; }
    //public virtual ICollection<UserLocation> UserLocation { get; set; }
}
```

}

Task:

public async Task<object> GetUserByIdTask(dynamic input)
        {
            try
            {
                int id; 
                var validInput = int.TryParse((string)input, out id);

```
            if(!validInput) throw new ArgumentException("The parameter is not a number.");

            return await Task.FromResult(GetUserById(id));
        }
        catch (Exception ex)
        {
            throw new Exception(ex.Message);
   }
```

 }

Get method:

public User GetUserById(int id)
{
        using (var da = _container.Resolve<DbEntities>())
        {
                return da.User.FirstOrDefault(user => user.UserId == id);
        }
 }

If I remove the Collections from the User class, it works perfectly.
What is the cause?

Thanks, David

**Comment by mdavid5** [comment]
As a workaround I can use an other JSON serializer. But mehh :)
Like this:
 return await Task.FromResult(
                     JsonSerializer.SerializeToString(GetUserById(id))
                    );

**Comment by tjanczuk** [comment]
Is it possible that the actual implementation of the `ICollection<T>` properties at runtime contains circular references?

**Comment by mdavid5** [comment]
The actual implementation is a hashset (see in the constructor) and all of them were empty during the tests.(yet :))

**Comment by leoyoo** [comment]
I got the StackOverflowException too when I'm using simple Entity Framework codes like below, this exception is not always occurred, it will happened after my program run for a while, weired. 
My Node code is a tcp server, when new data comes in, I will handle that, and update my station through the .net codes below, this is done via the edgejs. I 'm frustrated and can not find the reason. 
 
public async Task<object> UpdateStationAsync(dynamic station)
        {
            string projid = (string)station.projid;
            string stid = (string)station.stid;
            using (var context = new FlyDataContext(ConnectString))
            {
                var st = await context.Stations.FirstOrDefaultAsync(
                    s => s.ProjectID == projid && s.StationID == stid);
                if (st != null)
                {
                    st.IpAddress = (string)station.ip;
                    st.IpPort = (int)station.port;
                    st.ServerPort = (int)station.serverport;
                    st.LastCmd = (string)station.cmd;
                    st.LastUpdated = DateTime.Now;
                }
                else
                {
                    st = new Station()
                    {
                        ProjectID = projid,
                        StationID = stid,
                        IpAddress = (string)station.ip,
                        IpPort = (int)station.port,
                        ServerPort = (int)station.serverport,
                        Interval = 10,
                        LastCmd = (string)station.cmd,
                        LastUpdated = DateTime.Now
                    };
                    context.Stations.Add(st);
                }

                return await context.SaveChangesAsync();
            }

**Comment by leoyoo** [comment]
By the way, can someone let me know what is the thread model is when the .net code running through the Edgejs? is that the edgejs call .net with a single thread or with multiple threads for each call?

**Comment by leoyoo** [comment]
why there is no any response here? and nobody else had the same issue?

**Comment by mdavid5** [comment]
Well.. btw the issue is about JSON serializing/deserializing for sure. I have solved the problem by preprocessing the response. I am using now JSON.net library. It handles for me the circular references too. I am sending back the JSON string, not the object itself. Now it's fully working.

Something like this:
 public async Task<object> GetRestaurantByIdTask(dynamic input)
        {
            try
            {
                int restaurantId;
                var validId = int.TryParse(input as string, out restaurantId);

                if (!validId)
                    throw new ArgumentException("The restaurantId is invalid!");

                return await Task.FromResult(
                    JsonConvert.SerializeObject(GetRetaurantById(restaurantId),
                      new JsonSerializerSettings
                      {
                          ReferenceLoopHandling = ReferenceLoopHandling.Ignore
                      }
                    )
                );
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }

**Comment by leoyoo** [comment]
thanks for the reply, looks my case is not same with you. my .NET code only return an Integer value, this should not raise the serializing issue, right?

**Comment by davcup** [comment]
Hi,

I'm having the some problem, I have tried to return a serialized object and a single int value but always get the StackOverflowException.

I even have tried something like this
var s = mContextProivder.Context.ClokingDatas.ToList();
return "nothing";

So the method just use EntityFramework but return a string not related with it and again the error is stackoverflowexception.
