### ISSUE TITLE
Symbols in NuGet Package

### ISSUE THREAD

**Issue by martinsson** [tjanczuk/edge#251]
I'm trying to debug an issue. Would it be possible to make the sources available in a way that I can debug in VS? I'm new to C#, but I found this post that seems to state that it is possible as soon as they are available in a server like symbolsource.org and that I include that server in the debug options in VS.

http://stackoverflow.com/questions/13488280/best-practices-with-nuget-debug-or-release?rq=1

Or did I miss something very obvious?

**Comment by yosiat** [comment]
:+1:  for adding symbols in nuget package/symbolsource
