### ISSUE TITLE
node.js state persistence in a .Net web application?

### ISSUE THREAD

**Issue by axefrog** [tjanczuk/edge#252]
My use case that I'm investigating Edge for is isomorphic web applications. In order to achieve isomorphism, you have to reuse the same code for prerendering your DOM on the server as is what is used on the client after the fact. This means the server and client both have to be running JavaScript, and ideally node.js.

My application is built using ASP.Net Web API and so I only need node.js for the actual HTML rendering. So my idea is this: call `Edge.Func` from within a custom MediaTypeFormatter (targeting "text/html") and have it perform the rendering using the client-side scripts. My renderer is going to need to load various scripts and so forth though, and there's a small amount of overhead in doing that if that JavaScript framework code has to be re-executed on every request. A normal node.js application would have these things already cached in memory for use by subsequent requests, which would avoid both the execution cost and the file IO cost.

What can you tell me about these concerns with regards to the current implementation of Edge?

**Comment by tjanczuk** [comment]
The JavaScript passed to Edge.Func is evaluated just once the Edge.Func call is made. You can cache the Func delegate returned from Edge.Func and call it any number of times from your .NET application without incurring additional JavaScript evaluation costs. 

If you have a one-time initialization logic you need to preform in JavaScript, doing it before returning a JavaScript function ensures that it will only run once. 

Note that if you call Edge.Func several times, even with the same JavaScript literal, JavaScript evaluation will happen several times too.

**Comment by axefrog** [comment]
Oh, nice! Thanks for replying.
