### ISSUE TITLE
Cast error on returning short values (0.10.1)

### ISSUE THREAD

**Issue by fsahmad** [tjanczuk/edge#258]
Starting from release 0.10.0 returning short values from C# throws the exception "Error: Specified cast is not valid."

The following code will fail for example:

``` javascript
var edge = require('edge');

var helloWorld = edge.func(function () {/*
    async (input) => { 
        return (short)1; 
    }
*/});

helloWorld('JavaScript', function (error, result) {
    if (error) throw error;
    console.log(result);
});
```

while the following works:

``` javascript
var edge = require('edge');

var helloWorld = edge.func(function () {/*
    async (input) => { 
        return (ushort)1; 
    }
*/});

helloWorld('JavaScript', function (error, result) {
    if (error) throw error;
    console.log(result);
});
```

**Comment by ignotus0001** [comment]
We too are experiencing this problem. It's preventing us from upgrading from 0.9, which in turn is making it difficult to upgrade our node version, since 0.9 isn't precompiled for node 0.12. In short, causing some pain.

I'm writing here to inquire about the status. Any timeframe for a fix?

**Comment by crisfervil** [comment]
+1 To fix this 😄
