### ISSUE TITLE
Possible problems for node 0.12.*

### ISSUE THREAD

**Issue by webarchymeta** [tjanczuk/edge#259]
We are using nodejs + edgejs for a distributed application and it is quite fine when running under nodejs 0.10.\* despite the complexity of the apps (hundreds of thousands lines). 

However problems appear after upgrading to nodejs 0.12.1 (on Windows). We are experiencing long delays or even missing returns from nodejs/.net interface calls. If there is a delay, a repeated call will get it return shortly, like there is a kind of cache behind that must be flushed. The problem disappear after downgrading to nodejs 0.10.36. The report second down from this one may have similar problems to the ones we are having.

**Comment by tjanczuk** [comment]
Can you provide a conscise repro?

**Comment by webarchymeta** [comment]
I will try, but it could take a while since we are in a product release phase that keep us quite busy now. We choose to stick to node 0.10.* for this round ...

Thanks for your efforts anyways ...

**Comment by webarchymeta** [comment]
I have managed to create a repo to show the problem ([see here](https://github.com/webarchymeta/northwind-nodejs-demo)). It's not really concise, but closely represents our situation, in a simplified way.

I checked that this service has the same problem described above when running under nodejs 0.12.1.

**Comment by tjanczuk** [comment]
Thanks for the repro. What are the steps to reproduce the problem? 

What is your OS?

**Comment by webarchymeta** [comment]
I have tried node 0.12.1 on Windows 7 64bit (the real thing) and Windows 7 32bit (the demo). The problem will appear when you visit the service using a browser. What you will see is that one has to refresh the page to get the page displayed in some cases. When a (client side) debugger is used, one can see that some calls to the service are sometimes suspended for quite long time.

It seems that when server side debugger is used to break it, the problems goes away. Strang, isn't it? But I haven't dig it in any depth.

We use the data service as backend data API which is hit by sequence of calls from front end web servers in short amount of time. The problems are even more serious here.
