### ISSUE TITLE
Edge.js throws System.TypeInitializationException if Glimpse.Mvc5 package is installed

### ISSUE THREAD

**Issue by nelsonwellswku** [tjanczuk/edge#264]
## Steps to reproduce
1. Create a new MVC 5 application in Visual Studio 2013
2. Add the Edge.js package to the project
3. In a controller action, add a call to Edge.Func(...) 
4. Add the package Glimpse.Mvc5 to the project
5. Navigate to a page that would trigger the call to the Edge.js call.
6. Watch the entire MVC 5 application crash
## Exception details

There were not many details in the exception. I did not get a stack trace or anything useful, really. I was able to click the exception dialog and copy this to the clipboard.

```
System.TypeInitializationException was unhandled
Message: An unhandled exception of type 'System.TypeInitializationException' occurred in EdgeJs.dll
Additional information: The type initializer for '<Module>' threw an exception.
```
## Example

I've created a [Visual Studio 2013 project to reproduce this issue](https://github.com/nelsonwellswku/GlimpseEdgejsCrash).

Package versions:
- Edge.js - 0.10.0
- Glimpse.Mvc5 - 1.5.3
- Glimpse.AspNet - 1.8.0
- Glimpse - 1.8.2

**Comment by tjanczuk** [comment]
Does this reproduce without Glimpse added to the project?

**Comment by nelsonwellswku** [comment]
No. If I remove Glimpse, Edge.js works fine. If I re-add the Glimpse package, the exception occurs every time.

I've tried this on a Windows 8 machine with .Net 4.5 (how I originally found the issue) and a Windows 7 machine with .Net 4.5 and both exhibit the same problem.

**Comment by guptaarpit** [comment]
Hi

I've created two projects in Visual Studio 2015 with edge.js, while one is in Console which is working properly on the other hand I am using the same code of Console on MVC having infinite loading no response.

Thanks in Advance
