### ISSUE TITLE
How to use local module in javascript sent to Edge

### ISSUE THREAD

**Issue by estelleLeBouler** [tjanczuk/edge#266]
I download local module in a directory that i want to use in the javascript with require('aModule')
How to precise the directory when i launch Edge with : 
Edge.Func(javscript);

**Comment by tjanczuk** [comment]
See https://github.com/tjanczuk/edge#how-to-use-external-nodejs-modules

**Comment by glennblock** [comment]
You can also use the npm module to install modules programatically. As long
as the npm node module is in the require path you can use it to do
installation programatically.
