### ISSUE TITLE
Using EWS Managed API On Mac OS 10.10

### ISSUE THREAD

**Issue by MichaelWhite63** [tjanczuk/edge#270]
I want to read an Exchange Mailbox from my Mac.  I have installed Edge.js and am able to make the sample code work thus I am confident in my install.

My goal is to bring the EWS Managed API DLL into my Mac environment and interact with the DLL as if I were a C# developer.  Not having easy access to a Windows machine my question is in regard to bringing the C# EWS Managed API DLL into my environment and once it is in can I interact with it as if I were a c# developer.  

Is the following correct:
1) Download the MSI to a Windows machine.
2) Use the MSI installer to extract the DLL.
3) Copy the DLL from the Windows machine to my Mac.  
4) Then work with the API as described in the Microsoft documentation.  Thus, once it is on my Mac I can begin to follow the Microsoft documentation as if I were a C# developer.

**Comment by tjanczuk** [comment]
This is largely correct. The key question you must ask though is whether the Exchange DLL works with Mono, since that is what Edge uses on OSX. I would start by experimenting with the DLL on OSX and Mono, and only after that experiment is successful jump into Node.js integration via Edge.

**Comment by MichaelWhite63** [comment]
After comfiing that the DLL worked with Mono I got it working with Edge. I wasn't able to get the Autodiscover logic working but other than that it wasn't too bad.

**Comment by tjanczuk** [comment]
This scenario would make a great blog post.




On Sat, May 2, 2015 at 2:19 PM -0700, "MichaelWhite63" <notifications@github.com<mailto:notifications@github.com>> wrote:


After comfiing that the DLL worked with Mono I got it working with Edge. I wasn't able to get the Autodiscover logic working but other than that it wasn't too bad.

-

**Comment by MichaelWhite63** [comment]
Do have a specific place that you would like the blog post to be written?
Happy to do it.

**Comment by tjanczuk** [comment]
I don't have a project blog for Edge, just a personal blog (http://tomasz.janczuk.org). If you can put it up on your personal blog I can link from the GitHub page for Edge. If you don't have a blog and don't care about creating one, we can also do a guest blog post on my own blog.

**Comment by MichaelWhite63** [comment]
I will write it up and send you the link.  It will be a couple of weeks
before I do so as I am pushing to complete the project for which I needed
this logic.

**Comment by demarius** [comment]
@MichaelWhite63 Did you ever write this up? I'm following in your steps now and would like to see what you did.

**Comment by MichaelWhite63** [comment]
I didn't write it up but it works without any problem at all. It has been in production for almost a year without a single failure.  Let me look back at my code

What exactly are you doing?  

Michael White

**Comment by demarius** [comment]
Thanks for the swift response! I was able to bring the EWS Managed API in. I'm handling Autodiscover with Node so that's not a problem. The C# code contains a function to query, and one to update EWS. The trouble I'm having is actually with mscorlib, which is supposed to be targeted by default. I was hoping to see someone else's steps to see if I missed or ruined something.

**Comment by MichaelWhite63** [comment]
How far are you getting? If you have Autodiscover working you must be
accessing your C# code?
You must have FTPed the WebServices dlls & xml files to your OS X box and
put them into the run directory if Autodiscover is working.

I looked through my notes and I do not have anything about that library.  I
expect that by default it was in the correct place for me.

**Comment by demarius** [comment]
Yeah I'm able to access the code, and I can access the API fine... just not the core library. Pretty strange.

**Comment by MichaelWhite63** [comment]
Never experienced that.  I interacted with the Exchange server and it
worked fine.  Let me know how you resolve it.

**Comment by MichaelWhite63** [comment]
Tomek,

I have been very happy with how well Edge has run for me.  I am happy to
blog about it if you have a location for me to write.

Michael

**Comment by tjanczuk** [comment]
@MichaelWhite63 glad to hear that. Why don't you write up the content in markdown say on a gist, and then we can figure out where to put it best. I appreciate it!

**Comment by niclego** [comment]
Did you get around to writing up this blog post? I am new to EWS/C# and mono on the mac. I am simply trying to access my companies Exchange server via a React Native Application. 

Best,
Nick

**Comment by MichaelWhite63** [comment]
Nick,

I did not write the blog post. When I was asked to write it I was in the middle of my implementation. The implementation was difficult due to environmental issues. 

Good and bad. The software has been so stable that I have not had to consider / get involved with it. I’ve never had any memory issues, which was my biggest fear as I am returning a dynamic and occasionally large buffer. The buffer returns processed email in groups of 10 mail messages. 

To have a Node to C# bridge is great. 

Michael White
