### ISSUE TITLE
Question: Persistence of objects

### ISSUE THREAD

**Issue by MeirionHughes** [tjanczuk/edge#271]
Its not clear how you deal with keeping .net objects alive between calls. All the examples seem to be calling C# delegates to act on some input and produce an output. 

What happens if I want a to set up a service object then use its methods? Is that possible? 

I guess I can do this: 

```javascript
var edge = require('edge');

var increment = edge.func(function () {/*
 using System.Threading.Tasks;

 public class Startup
  {
    static int counter;
    static Startup()
    {
       //some setup here
       counter = 10;
    }

    public async Task<object> Invoke(object param)
    {
        return counter++;
    }
  }
 */});

increment('', function (error, result) {
  if (error) throw error;
  console.log(result);
});

increment('',  function (error, result) {
  if (error) throw error;
  console.log(result);
});
```

Which does the trick. So is this good to use?

**Comment by tjanczuk** [comment]
Yes, this is one way of doing it if you can tie the initialization of the CLR object with the `edge.func` call and don't need to pass in any initialization parameters to the object (the constructor is parameterless). 

A more complete demonstration of the concept that allows you to control the object initialization is shown in this sample: https://github.com/tjanczuk/edge/blob/master/samples/110_clr_instance.js

**Comment by MeirionHughes** [comment]
Cool. Seems like that would do the trick.

**Comment by Mytia** [comment]
Отправлено с iPhone
