### ISSUE TITLE
node 0.12.* and multi-context

### ISSUE THREAD

**Issue by webarchymeta** [tjanczuk/edge#275]
Was reading atom/electron repo and found that node 0.12 and above supports [multiple context](https://strongloop.com/strongblog/whats-new-node-js-v0-12-multiple-context-execution/) now.

I noticed that the initialization part in edge.cpp still uses the old 

```
NODE_MODULE(edge, init);
```

instead of 

```
NODE_MODULE_CONTEXT_AWARE(edge, init)
```

for the node 0.12.\* cases.

This could solve the problem reported in #259

**Comment by pocesar** [comment]
:+1:
