### ISSUE TITLE
AccessViolationException problem on site

### ISSUE THREAD

**Issue by mega15** [tjanczuk/edge#282]
Hello, I'm currently using 0.10.0 and using Edge ins a IIS app with this code:

``` c#
private Func<object, Task<object>> LoadEdgejsFunction(string function)
{
    try
    {
        Func<object, Task<object>> result = Edge.Func(function);
        return result;
    }
    catch (Exception exe)
    {
        throw new LoadEdgejsException(string.Format("Cannot load edgejs function"), exe);
    }
}
```

where function has the following:

``` javascript
return function (data, callback) {
    var json = JSON.parse(data);
    var connector = require('C:/nodejs/router.js');
    connector.invokeAction(json.g, json.a,json.d ,function (response){callback(null, response);});
}
```

but when is executed the  Edge.Func(function); line throws this exception:

Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
Stack:
   at EdgeJs.Edge.NodeStart(Int32, System.String[])
   at EdgeJs.Edge.<Func>b__1()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

This exception only happens sometimes so it seems a difficult to fix if there is anything to fix.

Can you help me solving this issue?

Thank you

**Comment by lijunle** [comment]
I got the same error here.

**Comment by mega15** [comment]
I put a image of the exception that vs2012 catch with this error.
![exceptionnode](https://cloud.githubusercontent.com/assets/10999963/8016447/f50c4712-0ba8-11e5-8de0-2c5d3fb10342.png)

I hope it helps

**Comment by FabienLavocat** [comment]
I got the same error with Edge 4.0.0.0

**Comment by ojosdegris** [comment]
Is there any solution to it? it kills w3wp process with this exception.

**Comment by drgrieve** [comment]
We also get the same issue. Pretty much every time app pool is recycled (every compile in development) it crashes.

**Comment by ojosdegris** [comment]
@drgrieve just a heads up that we were not able to solve it anyhow and just moved to [jint](https://github.com/sebastienros/jint)

**Comment by lijunle** [comment]
@ojosdegris Good to know a live alternative, it is time to *unsubscribe* this issue now. :smiley:

**Comment by mega15** [comment]
Does this problem has any solution in a recent edgejs version?, we have v 4.0.0.0 and still happens
