### ISSUE TITLE
Error marshaling Int16 values from CLR to JS

### ISSUE THREAD

**Issue by lostbutlearning** [tjanczuk/edge#285]
When marshaling from CLR to javascript there appears to be an error when casting Int16 values, causing the marshaling to fail with the error: "Specified cast is not valid."  The following illustrates the error (Win 7 64bit, node 0.12.4, edge 0.10.1, .net 4.5.1) [edited to simplify]:

``` javascript
var edge = require('edge');

var success = edge.func(function () {/*
  async (input) => { return 42; }
  // casts to int32 and int64 also work fine
*/});

var failure = edge.func(function () {/*
  async (input) => { return (Int16) 42; }
  // cast to short fails too
*/});

success(null, function (error, result) {
    if (error) throw error;
    console.log(result);
});

failure(null, function (error, result) {
    if (error) throw error;
    console.log(result);
});

```

This results in the following error, with stack trace:

```
PS C:\path\to\test> node test.js
42

C:\path\to\test\test.js:19
    if (error) throw error;
                     ^
Error: Specified cast is not valid.
    at Error (native)
    at <anonymous>:1:55
    at Object.<anonymous> (C:\path\to\test\test.js:18:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I can't hazard a fix, but clrfunc.cpp seems to have a case for this, and I'd guess it's failing around here: https://github.com/tjanczuk/edge/blob/840be77865b2d1756cb0ef2a222b820bc0f50c56/src/dotnet/clrfunc.cpp#L184
Thanks for a great project.

**Comment by TheBenji** [comment]
yep, have the same issue...

**Comment by SKVasanth** [comment]
I also have the same issue when marshaling from CLR supported dll to edgeJs. In my CLR I have called unmanaged dll which return's short always and it can't be changed. Any help is highly appreciated. Thanks in advance.

**Comment by SKVasanth** [comment]
I have fixed this by converting short object into string,
 public async Task<object> Invoke(dynamic input)
        {
    
            Int16 obj = this.OpenComSerial((int)input.debug, (int)input.trace);
            return obj.ToString();

        }

**Comment by dpolivy** [comment]
I am just upgrading from edge 0.9.3, and am now hitting this as well. Took quite a bit of debugging to figure out what was causing this! In looking at the diff, it seems that the Int16 marshalling case was added post 0.9.3; I'm not certain what it was marshaled as before, but it did work just fine.

https://github.com/tjanczuk/edge/compare/v0.9.3...master?diff=unified&name=master#diff-c52d7b9918e39cc1a6572a363ebea2e6R183

@tjanczuk There's a PR for this (#299) that's been open for over a year. Any chance of pulling it in?
