### ISSUE TITLE
Trouble referencing PresentationCore.dll

### ISSUE THREAD

**Issue by samuelkilada** [tjanczuk/edge#286]
Hello,

I am trying to reference PresentationCore.dll so that I can use System.Windows.Media.Imaging. However, whenever I try to run the project it crashes on:

return edge.initializeClrFunc(options);

...with the error "#<Error>". In fact that's the only error I ever get whenever I have typed anything incorrectly. I have gotten Edge to work when running one of the samples, but I really need to access that namespace. I've tried a try / catch to get error details but it doesn't work, and "#<Error>" doesn't help me at all.

This is a nodeJS server that needs to use some existing c# code I've written in the past, so I'm trying to wire this up.

This is how I create the method using Edge:

var helloWorld = edge.func({
    source: path.join('scripts', 'hello.cs'),
    references: ['PresentationCore.dll'](I've tried an absolute path to this dll)
});

...and this is the method, based on one of the samples:

using System;
using System.Threading.Tasks;
using System.Windows.Media.Imaging;

public class Startup
{
    public async Task<object> Invoke(int startingSalary)
    {
        var person = new Person(startingSalary);
        return new
        {
            getSalary = (Func<object, Task<object>>)(
                async (i) =>
                {
                    return person.Salary;
                }
            ),
            giveRaise = (Func<object, Task<object>>)(
                async (amount) =>
                {
                    person.GiveRaise((int)amount);
                    return person.Salary;
                }
            )
        };
    }
}
public class Person
{
    public int Salary { get; private set; }
    public Person(int startingSalary)
    {
        this.Salary = startingSalary;
    }
    public void GiveRaise(int amount)
    {
        this.Salary += amount;
    }
}

If I remove the System.Windows.Media.Imaging reference as well as the reference to the PresentationCore.dll file, it works.

Thanks for your help!
-Sam

**Comment by tjanczuk** [comment]
I am using Windows8, node 0.12.2, and Edge 0.10.1. The following code runs OK for me:

```javascript
var edge = require('edge');

var hello = edge.func({
	source: function () {/*
		using System.Windows.Media.Imaging;
		async (input) => 
		{ 
			return ".NET welcomes " + input.ToString(); 
		}
	*/},
	references: ['c:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\WPF\\PresentationCore.dll']
});

hello('Node.js', function (error, result) {
	if (error) throw error;
	console.log(result);
});
```

Note that if I replace 

```
references: ['c:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\WPF\\PresentationCore.dll']
```

with

```
references: ['PresentationCore.dll']
```

I am getting a compilation error: 

```
Error: Unable to compile C# code.
----> Errors when compiling as a CLR library:
error CS0006: Metadata file 'PresentationCore.dll' could not be found
----> Errors when compiling as a CLR async lambda expression:
error CS0006: Metadata file 'PresentationCore.dll' could not be found
    at Error (native)
    at Object.exports.func (C:\projects\adhoc\node_modules\edge\lib\edge.js:154:
```

which is what I think you may be getting too. Try specifying the fully qualified reference to PresentationCore.dll

**Comment by samuelkilada** [comment]
Thanks! That did the trick.

Any idea why I get those non-descriptive error messages, though? It would be great if I knew what the issue was from looking at the error message.

-Sam
