### ISSUE TITLE
Custom path for node executable

### ISSUE THREAD

**Issue by mega15** [tjanczuk/edge#289]
Hi, Is there a way to pass to edge the node.exe path?. For example, I don't want to force my clients to download and install the msi node installer, so I want to provide the node package (folder) with my application then in my code pass to edge the node.exe path when I call it from my .NET app.

**Comment by tjanczuk** [comment]
The Edge.js NuGet package is self-contained and does not have a dependency on node.exe. It contains with a private build of Node runtime created as a shared library (node.dll).
