### ISSUE TITLE
Could this module be used to bind to an ActiveX component?

### ISSUE THREAD

**Issue by AleCaste** [tjanczuk/edge#292]
Inititially we wanted to use node-ffi to do this but the author of such module is advising me to use Edge instead to achieve the bind to an ActiveX component.
The thing is that I could not find any examples anywhere that would show me how.
I have an "XXXXXX.application" ActiveX control that I would like to use within node but I am totally stuck.
Apparently the way is to connect to the Win32 api through your module and then call CoCreateInstance but I have no idea how to properly do this.
Thanks in advace

**Comment by AleCaste** [comment]
Apparently the authors of the ActiveX component we want to use have also created a in dll that wraps the activex component to enable the use of this wrapper dll in a .NET environment.
But could we use your module to make use of such a dll from node instead of from a .NET project?
Thanks again

**Comment by jkash20** [comment]
Hi, did you get this working? I'm in a similar situation.
