### ISSUE TITLE
Messages being sent to client are "chunking" rather than streaming

### ISSUE THREAD

**Issue by oconnef** [tjanczuk/edge#294]
Tomasz, 

Love what you've done here, as I'm using edge to source game code that was built in C# with node.js as the game server. 

I've run into a problem I've described in the following stackoverflow post. Any insight or guidance would be a great help!

http://stackoverflow.com/questions/31193330/why-are-my-socket-io-events-coming-through-in-chunks

Thanks very much,
Tom O

**Comment by tjanczuk** [comment]
Posted a suggestion on SO. Bottom line is don't think this is related to edge.js.
