### ISSUE TITLE
Support for Mono

### ISSUE THREAD

**Issue by mythz** [tjanczuk/edge#3]
I understand this may not be a high priority, but many open source .NET frameworks and potential owin hosts want to ensure their frameworks and libraries work cross-platform.

I'm assuming there's going to be a bit of win specific bits, but it'd be nice if the parts that can be re-usable across platform can easily be decoupled and re-used from the bits that aren't.

**Comment by kaviproject** [comment]
I can able run on my local machine with edge.js.When I will deploy into the server it is giving an error."casttype is not found".
