### ISSUE TITLE
F# Not work with Paket

### ISSUE THREAD

**Issue by hswick** [tjanczuk/edge#301]
Trying to call js from within f# following this blog post:
http://blog.ctaggart.com/2014/05/embedding-nodejs-in-your-net-f-app.html

Got the example working within VisualStudio using package manager console:
Install-Package Edge.js
No problem.

However, when I tried installing the package with Paket outside of a vizstudio solution I ran into include errors within my F# script.

I'm calling" nuget Edge.js" within my paket.dependencies, running paket install puts /Edge.js in /packages directory.

1st attempt at including in script -
This line: #r "packages/Edge.js/lib/EdgeJs.dll" gives me this error -

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'node.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at EdgeJs.Edge.NodeStart(Int32 argc, String[] argv)
   at EdgeJs.Edge.<Func>b__1()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

2nd attempt at include-
Added this line of code at top:
#r "packages/Edge.js/content/edge/x64/node.dll"

Which gives a new error:

Message: Evaluation failed
Error: app.fsx(3,1): error FS0229: Error opening binary file 'C:\Users\hswick001\Desktop\Reactive\packages/Edge.js/content/edge/x64/node.dll': C:\Users\hswick001\Desktop\Reactive\packages/Edge.js/content/edge/x64/node.dll: bad cli header, rva 0

app.fsx(3,1): error FS3160: Problem reading assembly '': Exception of type 'Microsoft.FSharp.Compiler.ErrorLogger+StopProcessing' was thrown.

I noticed that the VisualStudio project has /edge directory in root of project. So I tried copying the edge folder in /content to the root of project. Still was unable to locate node.dll and tried to change the include to point to the node.dll at the new path and same error as second attempt.

**Comment by ctaggart** [comment]
You are trying to run from F# interactive and Edge.js needs to load a native `node.dll`. It is not really a Paket issue. `node.dll` needs to be on a native search path. The first place that is attempted is the same directory as the process. `#r` is only for .NET assemblies.

When not using F# interactive, the path structure that works is:
![image](https://cloud.githubusercontent.com/assets/80104/12008315/35bbccd0-abe8-11e5-8334-5f075b128f98.png)
where `EdgeJs.dll` and `node.js` dll are in the same folder with a subdirectory.

**Comment by hswick** [comment]
Ah I see now. Thanks!
