### ISSUE TITLE
External DLL needs external file

### ISSUE THREAD

**Issue by shernshiou** [tjanczuk/edge#308]
Hello,

I am trying to compile a dll which i compiled before hand. However, the dll requires some external reference dll that require another file to operate. I tried to place the external file along side with them together, but the dll cannot find the file.
 Can you point me where should I place it or how should I debug it.

Basically,

Edge -> Compiled DLL -> Referenced DLL -> External file

UPDATE:
If I build another executable to access the compiled DLL, the external file, referenced dll and compiled dll must be in a same folder.

Executable -> Compiled DLL -> Referenced DLL -> External file

**Comment by tjanczuk** [comment]
You can specify DLL references in a call to `edge.func` using the `references` parameter as follows: https://github.com/tjanczuk/edge#how-to-specify-additional-clr-assembly-references-in-c-code. In particular, the `references` parameter can specify the fully qualified file name of the referenced DLL. 

As to how to load the external file, it is impossible to say without knowing how the loading is set up in the referenced DLL in your case.

**Comment by shernshiou** [comment]
Hi @tjanczuk 

I did specify the references. Edge can access the compiled dll and reference dll. However, the referenced dll did not manage to find the external file which is supposed to be sitting in the same folder.

**Comment by georglang** [comment]
Hi @shernshiou,  have you found a solution to the problem ?

**Comment by shernshiou** [comment]
@georglang no. I've not been using this solution for sometimes
