### ISSUE TITLE
Cannot Run edge.node in node.js v4.0 environment

### ISSUE THREAD

**Issue by namsouth** [tjanczuk/edge#313]
Error: The edge module has not been pre-compiled for node.js version v4.0.0. 
You must build a custom version of edge.node. 
Please refer to https://github.com/tjanczuk/edge for building instructions.

**Comment by mogmios** [comment]
I'll second this issue. Could start building my own module but it makes updates really slow on Elastic Beanstalk.

**Comment by tjanczuk** [comment]
I am currently working on enabling Edge to work with Node 4.0.

**Comment by doruu12** [comment]
My fork works with Node 4.0, for simple scenarios. I used https://github.com/nodejs/nan/blob/master/tools/1to2.js to port to nan 2.
For more complex apps I get a heap corruption error at runtime
https://github.com/doruu12/edge

**Comment by doruu12** [comment]
It's passing the tests

**Comment by tjanczuk** [comment]
@doruu12 Are you saying you get heap corruption errors for complex scenarios *despite* all tests are passing?

**Comment by doruu12** [comment]
Yes

**Comment by tjanczuk** [comment]
Can you provide a repro?

**Comment by doruu12** [comment]
I think code was migrated correctly in general, but I'm not very sure about these lines
https://github.com/doruu12/edge/blob/master/src/dotnet/clrfunc.cpp#L45-L59
I'll try to provide a repro

**Comment by tjanczuk** [comment]
Status update: you can now use Edge.js with Node.js 4.0 on OSX and *nix using Mono. Install with `npm i tjanczuk/edge#four`. I am working on Windows support next.

**Comment by Siafu** [comment]
Awesome, I'll be waiting on the Windows update.

**Comment by tjanczuk** [comment]
Support for Node.js 4.x just shipped. 

Nuget package: https://www.nuget.org/packages/Edge.js
npm: edge@4.0.0
