### ISSUE TITLE
Cannot return the method in the object which instance from the C# class , see below code.

### ISSUE THREAD

**Issue by gentlecolder** [tjanczuk/edge#314]
var edge = require('edge');

var getPerson = edge.func(function () {/*
    using System.Threading.Tasks;

    public class Person
    {
        public int anInteger = 1;
        public double aNumber = 3.1415;
        public string aString = "foo";
        public bool aBoolean = true;
        public byte[] aBuffer = new byte[10];
        public object[] anArray = new object[] { 1, "foo" };
        public object anObject = new { a = "foo", b = 12 };
		
	public int Test(){
			return 7;
		}
    }
	

    public class Startup
    {
        public async Task<object> Invoke(dynamic input)
        {
            Person person = new Person();
            return person;
        }
    }
*/});

getPerson(null, function (error, result) {
    if (error) throw error;
    console.log(result);
	console.log(result.Test()); //complie error
});

C:\project\index3.js:35
        console.log(result.Test());
                           ^
TypeError: undefined is not a function
    at C:\project\index3.js:35:21
    at <anonymous>:1:55
    at Object.<anonymous> (C:\project\index3.js:32:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

can reuse the C# object

**Comment by tjanczuk** [comment]
Edge can only export instance methods that follow the `Func<object,Task<object>>` async signature. To export specific sync functionality you need to provide an async wrapper of that shape around it. See https://github.com/tjanczuk/edge#how-to-export-c-function-to-nodejs for details.
