### ISSUE TITLE
Support ASP.NET 5

### ISSUE THREAD

**Issue by Lenne231** [tjanczuk/edge#315]
If i try to use EdgeJS with ASP.NET 5 the "node.dll" is not installed by NuGet and DNX searches at the wrong places.  

![capture](https://cloud.githubusercontent.com/assets/2046557/9917646/10e4720a-5cc3-11e5-8ec1-c2a0c3c000f3.PNG)

**Comment by jskulavik** [comment]
@Lenne231 Did you ever resolve this?  It's still a problem in beta 8

**Comment by tjanczuk** [comment]
This will be enabled by https://github.com/tjanczuk/edge/pull/337

**Comment by gregbty** [comment]
When will 5.0 be released to Nuget?
