### ISSUE TITLE
Debug JavaScript in Visual Studio 2015

### ISSUE THREAD

**Issue by Lenne231** [tjanczuk/edge#316]
Is it possible to debug JavaScript running in a .NET process in Visual Studio?

**Comment by tjanczuk** [comment]
Yes please see https://github.com/tjanczuk/edge/issues/163#issuecomment-76808068.

**Comment by Lenne231** [comment]
Thanks! It works with node-inspector, do you know a way to debug in VS? Im using EdgeJS in a ASP.NET project for server side UI rendering.

**Comment by tjanczuk** [comment]
You could try doing something with https://nodejstools.codeplex.com/, but you are in uncharted territory. If this works out, please blog or at least drop me a note.
