### ISSUE TITLE
Donations for progress?

### ISSUE THREAD

**Issue by blackshadev** [tjanczuk/edge#321]
Edge seems very popular. Wouldn't it be a good idea to open a donation page in order for you to spend more time on this project. I myself would donate at least a fair amount.

**Comment by tjanczuk** [comment]
I appreciate the thought and I am glad Edge is proving useful to you. I am currently working on porting Edge to Node 4.x, and will attempt to address other low hanging fruit along the way. One thing that would help more than donations would be quality PRs which I am glad to accept.

**Comment by tjanczuk** [comment]
Support for Node.js 4.x just shipped.

Nuget package: https://www.nuget.org/packages/Edge.js
npm: edge@4.0.0
