### ISSUE TITLE
Strangest bug ever

### ISSUE THREAD

**Issue by kevinsbennett** [tjanczuk/edge#328]
We have been seeing a seemingly random bug when scripting js from C#, where we would get the error: 

```
SyntaxError: Unexpected token ILLEGAL
    at compileFunc
```
on the call to Edge.Func(js), even though the javascript we were passing in was perfectly valid.  

After much trial and error, we discovered that once the length of the javascript string was over a certain threshold, we would get this error, but only if the length of the string was divisable by 8.  The threshold appears to be around 84976 characters (but is not consistent).  It will fail with the illegal token error at any length above that threshold that is divisable by 8.  Told you it was strange!

Here is a test to recreate:

```
            for (var i = 84000; i < 90000; i++)
            {
                var js = "return function(e, callback){" + Environment.NewLine;
                js += "//" + new String('0', i) + Environment.NewLine;
                js += "}";
                try
                {
                    var execute = EdgeJs.Edge.Func(js);
                }
                catch
                {
                    Debug.WriteLine(i.ToString());
                }
            }
```

From this simple test you will see an output like this:

```
84976
84984
84992
85000
85008
85016
85024
...
```

**Comment by tjanczuk** [comment]
May be related to https://github.com/tjanczuk/edge/issues/310

**Comment by kevinsbennett** [comment]
fyi...  this bug is also a problem for the parameters passed in to the edge func, not just the javascript code

**Comment by tianhuat** [comment]
I have met with this issue as well...
