### ISSUE TITLE
The edge module has not been pre-compiled for node.js version v4.1.1. You must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge for building instruction

### ISSUE THREAD

**Issue by raysefo** [tjanczuk/edge#331]
Hello,

I am using VS 2015 with node 4.1.1 and npm 2.14.4. When I try to build my cordova app I get this error. How can I fix this?

Best Regards.

**Comment by Zougi** [comment]
run .\build.bat release 4.1.1 from forlder tools. It's written on the readme...I had this issue earlier and it solved it. Note that if edge is a dependencie of another package, you should execute this command from the node_modules of the package. Also I would do a npm up before trying to execute .\build.bat release 4.1.1

**Comment by viniciusmelquiades** [comment]
I fixed that problem going to the folder `C:\Users\{user}\AppData\Roaming\npm\node_modules\vs-tac` and changing the `package.json` to use `edge` version 4.0.0, deleting the edge folder in the node_modules, and running npm install in the vs-tac folder

**Comment by nccchirag** [comment]
Thanks @viniciusmelquiades for the solution

**Comment by astritzeqiri** [comment]
9997973336001
9993487139008
9993487139008
9993487139008
9993487139008
9993487139008
9993487139008
9993487139008
9993487139008
