### ISSUE TITLE
i found the value of long type in C# return to nodejs will changed 

### ISSUE THREAD

**Issue by gentlecolder** [tjanczuk/edge#338]
when i use edge, i found the value of long type in C# return to nodejs will changed when the value larger than the nodejs' allowed max number, so if there is a file we can edit to let the all long type or double number to be converted to the string when return to js before the my rebuiding time.

**Comment by gentlecolder** [comment]
thanks in advance

**Comment by Konard** [comment]
Why not to convert long value to string inside C# (using ToString()) before returning?

**Comment by gentlecolder** [comment]
thank, i have solved it, just recomplie the edge which let the long allconvert to string
