### ISSUE TITLE
SQL Connection String in Program Instead of Environment Variable

### ISSUE THREAD

**Issue by Scott-Cochrane** [tjanczuk/edge#346]
I'm working on getting a simple REST service on top of MSSQL up and going.  I have a working test project using the environment variable method for the connection string.  The string I use is as follows:

"set EDGE_SQL_CONNECTION_STRING=Data Source=localhost\SQLEXPRESS;Initial Catalog=AdventureWorks2014;Integrated Security=True"

I send that into the console and start the node process and everything is great.  Ultimately I'm trying to host this project inside of IISNode along side several older SOAP web services already in production.  For this reason I'm trying to work out how to implement the connection string within the project or somewhere inside IIS instead of using the environment variable method.

I've tried the method outlined by @tjanczuk in [this post](https://github.com/tjanczuk/edge/issues/65) with no success.  Here's my code:

```javascript
var edge = require('edge');
var sqlPath = "Data Source=localhost\sqlexpress;"+
              "Initial Catalog=AdventureWorks2014;"+
              "Integrated Security=True";

var getEmployeeById = edge.func('sql', {
	source: function () {/*
		SELECT *
		FROM [AdventureWorks2014].[HumanResources].[vEmployee]
		WHERE [BusinessEntityID] = @Id
	*/},
	connectionString: sqlPath
});

exports.findById = function (req, res, next) {
    getEmployeeById({ Id: req.params.id }, function (error, data) {
        if (error) { 
            console.log(error);
            res.send(error.message);
        }
        if (data) {
            res.send(data);
        }
        else {
            var noData = [];
            res.send(noData);
        }
    });
}
```

Here's the error that generates:

"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"

I have gone through troubleshooting steps to see if it is indeed a SQL problem and I can't identify any glaring issues.  I have no issues connecting via any other method than that described above.  If it were a SQL issue I would think it would also be an issue using the environment variable which it is not.

I would prefer being able to set the string in the program so I can connect to different databases if needed in the future, but a solution on how to configure this within IISNode instead would be alright as well.

**Comment by Miramac** [comment]
I guess it's the not escape backslash in your connection string.

Try:
```javascript
var sqlPath = "Data Source=localhost\\sqlexpress;"+
              "Initial Catalog=AdventureWorks2014;"+
              "Integrated Security=True";
```

**Comment by Scott-Cochrane** [comment]
Wow, just....wow. I've spent more time than I'd like to admit trying to work this out and never noticed my rookie mistake of the missing escape.  Thank you for taking the time to set me straight.  Works like a champ now.
