### ISSUE TITLE
CoreCLR: avoid project.json for simple cases 

### ISSUE THREAD

**Issue by tjanczuk** [tjanczuk/edge#351]
@lstratman The CoreCLR requirement for project.json even for the simplest of scenarios is in rather stark contrast to the experience Node users are used to. Is there a reasonable way of avoiding this requirement? Can the project.json be specified imperatively via an API, perhaps one that covers at least the built-in dependencies: https://github.com/tjanczuk/edge-cs/blob/master/src/edge-cs-coreclr/EdgeCompiler.cs#L67-L74?

**Comment by lstratman** [comment]
That should be possible, yes.  We actually already add a loader for the compiler's project.json (https://github.com/tjanczuk/edge/blob/master/src/CoreCLREmbedding/coreclrembedding.cs#L259-L268), but without a project.json for the application itself, it throws an exception before it can reach that point.  We can distribute the project.json for Edge.js itself (https://github.com/tjanczuk/edge/blob/master/src/CoreCLREmbedding/project.json), run `dnu restore` on it during install like we do when we're in Linux, and then, in the `EdgeAssemblyLoadContext` constructor when we detect that there's no project.lock.json, we can add a loader for the "stock" project.lock.json that should allow them to run just about anything that doesn't require any external libraries.  I'll experiment with this a bit tomorrow.

**Comment by tjanczuk** [comment]
Perfect, that would be a much better user experience!

**Comment by cmatskas** [comment]
Great question and an even better answer. I look forward seeing this implemented
