### ISSUE TITLE
C# -> JS -> C#

### ISSUE THREAD

**Issue by amitavmohanty01** [tjanczuk/edge#354]
I want to call a C# method from JS. The JS in turn will also be triggered from C#. 
```
// method to be called from JS
static void Print()
        {
            Console.WriteLine("Printing whenever called from JS");
        }

private static async void TryObject()
        {
            var func = Edge.Func(@"
            var http = require('http');                   // works fine
            var edge = require('edge');               // works after npm install -g edge
            var funcCs = edge.func(function() { /*
            */});
            return function (data, callback) {
                callback(null, JSON.stringify(data, null, 2));
            }
        ");
            object value = await func("temp");
            Console.WriteLine(value);
        }
```
The line where I am creating callback funcCs is where the code is failing. What is the correct way of achieving this ? The error I am getting is the following

```
Error: Could not load type 'Startup' from assembly 'hnnozlos, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
    at Error (native)
    at Object.exports.func (c:\users\me\node_modules\edge\lib\edge.js:155:17)
    at eval (eval at <anonymous> (c:\users\me\documents\visual studio 2015\Projects\edgejs_attempt\edgejs_attempt\bin\Debug\edge\double_edge.js:34:28), <anonymous>:3:31)
    at compileFunc (c:\users\me\documents\visual studio 2015\Projects\edgejs_attempt\edgejs_attempt\bin\Debug\edge\double_edge.js:35:16)
```

**Comment by amitavmohanty01** [comment]
The above problem was partly solved by using the following:

```
static class Program{
private static async void TryCb()
        {
            var func = Edge.Func(@"
            
            var edge = require('edge');
            var add = edge.func(
    {
        source: function() {/*
            using System.Threading.Tasks;

            public class Startup
            {
                public async Task<object> Invoke(dynamic input)
                {
                    int a = (int)input.a;
                    int b = (int)input.b;
                    //Program.Print();
                    return MathHelper.Add(a, b);
                }
            }

            static class MathHelper
            {
                public static int Add(int a, int b)
                {
                    return a + b;
                }
            }
        */},
            references: ['System.Linq.dll', 'Callbacks.dll']
            });
            
            var http = require('http');
            return function (data, callback) {
                callback(null, JSON.stringify(data, null, 2));
            }
        ");
            
            object value = await func("temp");
            Console.WriteLine(value);
        }
}
```

However, neither Program.Print() works nor adding a reference to another library project in the same solution works. In fact, I even copied the dll to the build folder of the same project yet it does not work.

**Comment by tjanczuk** [comment]
The mechanism of hosting Edge.js in Node.js code invoked from CLR using Edge.js itself has never been tested. While it may just work I would not be surprised it does not. 

There is a simpler way of accomplishing what you want to do: you can pass a `Func<object,Task<object>>` instance to a Node.js function exposed to C# using Edge.js as part of the `object` parameter. Edge.js allows marshaling of such function delegates, and will expose them as `function (obj, callback)` JavaScript function when the execution moves to Node.js. Check out https://github.com/tjanczuk/edge/blob/master/samples/108_func.js for inspiration.

**Comment by amitavmohanty01** [comment]
Thank you for the suggestion. That works fine. Just curious though, does my technique create 2 CLR heaps ? Please excuse my ignorance here.

**Comment by tjanczuk** [comment]
I don't think it would create another CLR heap, but it would initialize the Edge.js runtime twice. That in turn would invalidate the basic assumption Edge is only started once per process, with the hell breaking loose soon thereafter.
