### ISSUE TITLE
C# objects with indexer causes NullReferenceException

### ISSUE THREAD

**Issue by tedbigham** [tjanczuk/edge#361]
Returning an object with an indexer from Startup.Invoke causes a NullReferenceException instead of returning the object.

**Comment by tjanczuk** [comment]
Can you provide a repro?

**Comment by tedbigham** [comment]
Yessir

repro.js...

    var edge = require('edge');
    
    var helloWorld = edge.func('MyClass.cs');
    
    helloWorld('JavaScript', function (err, result) {
        if (err) {
            console.log(err + ":" + err.message);
            throw error;
        }
        console.log(result);
    });

MyClass.cs...

    using System.Threading.Tasks;
    
    public class Startup {
        public async Task<object> Invoke(dynamic input) {
            return new MyClass();
        }
    }
    
    public class MyClass {
        public object this[string name]	{
            get { return "something"; }
            set { }
        }
    }
