### ISSUE TITLE
Support for NodeJS 5.x

### ISSUE THREAD

**Issue by EricSmekens** [tjanczuk/edge#363]
I currently have the following npm log when I try to install edge with NodeJS 5.1.1.
```
Error: The edge module has not been pre-compiled for node.js version v5.1.1. You must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge for building instructions.
```

I noticed there was a commit with support for 5.x, but it did not release or ship on npm yet.
Is this something you will do in the near future? I would be happy to test it, if I have some guidelines.

**Comment by tjanczuk** [comment]
The version with support for Node.js 5.x will also supports CoreCLR in addition to Mono and desktop CLR. This was a major body of work and there is some fit & finish left before . Having said that if you install edge straight from Github with `npm i tjanczuk/edge` you should get a working version with Node.js 5.x support.

**Comment by EricSmekens** [comment]
Thanks, leaving this issue open for other people to see it. Will close it as soon as it is on npm! :)

**Comment by katopz** [comment]
And how to make it work via electron? I got his error from https://github.com/kexplo/electron-edge

Thanks

**Comment by s-a** [comment]
:+1: I got the error module did not self register in electron 0.36.1 (node 5.1.1)

**Comment by tsiddikee** [comment]
@ tjanczuk
error : The edge module has not been pre-compiled for node.js version v6.2.1.
I have install as you said **npm i tjanczuk/edge** from github repository, still it is giving same error.
Please help. Should I downgrade node version ?

I am using webstorm and installed git and set path properly . Git is working.
and it successfully load the module from github. but edge is giving  error as ebove

**Comment by VinayParasrampuria** [comment]
@ tjanczuk 

Please help how we can compile edge version against latest node js .

**Comment by actiontom** [comment]
npm i tjanczuk/edge worked for me with latest node js. Thanks
