### ISSUE TITLE
 The edge module has not been pre-compiled for node.js version v5.1.0

### ISSUE THREAD

**Issue by laanaithossam** [tjanczuk/edge#364]
Hi, 
I'm using Cordova-Multiplatform-Template with visual studio 2015, and i'm getting the npm error below.
 
[Error: The edge module has not been pre-compiled for node.js version v5.1.0. You must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge for building instructions.]

Thanks in advance,

**Comment by tjanczuk** [comment]
See https://github.com/tjanczuk/edge/issues/363
