### ISSUE TITLE
Server rendering React

### ISSUE THREAD

**Issue by andersekdahl** [tjanczuk/edge#365]
Hi!
We're about to start using Edge.js to render React components in an ASP.NET site on a medium to large site.
How many Node threads are created? When hosting Node by itself you often use the cluster module to utilize all cores, how does that relate to Edge.js? I'm guessing that it does something similar behind the scenes?

**Comment by tjanczuk** [comment]
When you host Node.js within a CLR process, Node event loop is running on a single thread in that process. Edge takes care of thread synchronization when calling between single threaded Node environment and multi-threaded ASP.NET code.

Cluster module is not going to work when hosting Node.js code in a CLR process. Cluster module normally spawns child processes to saturate multi-core CPUs, but in this case it would not be aware the master process is a CLR process. 

If you expect that the CPU-bound part of your application is going to be the Node.js code, I would recommend looking into ways of creating multiple CLR processes that each runs a singleton Node.js thread. I don't know what you are using for hosting of your ASP.NET app, but this can normally be configured using hosting-specific mechanisms, e.g. IIS.

**Comment by andersekdahl** [comment]
Thanks for the answer! Using Web Garden in IIS is something we'd like to avoid as running multiple processes will increase the memory usage with the number of processes (we use a framework that has a lot of in memory caching, and that cache would be duplicated across all processes).

Is it not possible to have multiple Node.js threads within one process in Edge.js?

**Comment by tjanczuk** [comment]
No, it is not possible. Node has a rather firmly encoded assumption about having a singleton thread per process.

**Comment by andersekdahl** [comment]
Okay, thanks for answering!
