### ISSUE TITLE
Question: Will edge support "mono 4.x"  for **script node.js from CLR**?

### ISSUE THREAD

**Issue by vicancy** [tjanczuk/edge#379]
Readme says that **script node.js from CLR** for "coreclr" is _coming soon_, will "mono 4.x" also be supported? BTW, how **soon** for coreclr support? Any target date?

**Comment by tjanczuk** [comment]
I have no plans to support scripting node.js from Mono unless a killer scenario comes up or a PR materializes from thin air. 

As for scripting Node.js from CoreCLR, I really would like to get to it as time allows. There are some technical challenges to tackle. Unless someone steps up to collaborate (hint hint @lstratman) I don't envision it happening in the nearest feature.

**Comment by donnyv** [comment]
So why do you have it say "coming soon" in your presentation page?
http://tjanczuk.github.io/edge/#/7

**Comment by tjanczuk** [comment]
Sorry about that. This statement predated Core CLR and was, well, too aspirational.
