### ISSUE TITLE
Cannot Run edge.node in Node.js version v5.3.0

### ISSUE THREAD

**Issue by patrickCode** [tjanczuk/edge#380]
Getting the following error - The edge module has not been pre-compiled for node.js version v5.3.0. You must build a custom version of edge.node.
I was trying to install the vs-tac package when I encountered the error. Will there be support for Node.js version v5.3.0.

**Comment by jeveloper** [comment]
Works well on OSX with 5.5.

**Comment by wendal** [comment]
Can we just make an CI to build pre-compile for latest node.js version ?
