### ISSUE TITLE
Promises aren't working properly

### ISSUE THREAD

**Issue by KfirShainholtz** [tjanczuk/edge#381]
Hello,
This past week I've been experiencing with Edge, invoking Func's from .NET to the server.

A problem occurs when trying to receive callbacks from methods inside a .then closure,
when I invoke a Func such as the following: 
Edge.Func("function(options) {... doSomething.then(function(result) { options.InvokeCSharpFunc(result))}"), it just doesn't work. 
In contrary to Edge.Func("function(options) {options.InvokeCSharpFunc(result)});
when not in a Promise closure.
the Request and jQuery's get requests
aren't responding well (or at all) when running them on Edge, too.

**Comment by pofider** [comment]
I can confirm the same behavior for the q promise library;

```
require('q')().then(function() { console.log("never gets here'); });
```

**Comment by KfirShainholtz** [comment]
Hello pofider,
since I posted this, I abandoned EdgeJS, and just created a
NodeJS service which interacts with my C# server.

To your comment, I didn't think that edge is behaving this way,
and didn't see it at the README (or I'm completely missing something)

So, I think the requests should be promisied, or should
be threat like the q.js ones, but any documentation should be put (about approaching callbacks in edge js)
