### ISSUE TITLE
Handling C# .NET events with NodeJS event handler

### ISSUE THREAD

**Issue by danielmihai** [tjanczuk/edge#384]
Hello @tjanczuk,

Could you please provide a simple example of EdgeJS code (Node.JS) code handling .NET events properly?

I want to start an ID Card Reader application (for 3M CR100 SwipeReader) and I want my (edgejs + nodejs) code to listen to the DocumentReadEvent and DocumentReadErrorEvent from my C# code.

If you want I can post some code, but I think a super simple example of a C# .NET Class that has a function that fires an event, and that event is caught in the JS file with edge and node would be superfine. 

Please reply to this comment just to see you have seen it and if you can apply some action to this issue commented here.

With all due respect,
Daniel.

**Comment by tjanczuk** [comment]
A sample of consuming .NET events in Node.js is available at https://github.com/tjanczuk/edge/blob/master/samples/211_events.js.

**Comment by Culicode** [comment]
How to use in Visual Studio and can i deploy it in Localhost ?
