### ISSUE TITLE
Compatibily with Windows 10 IoT on ARM device

### ISSUE THREAD

**Issue by ilgb** [tjanczuk/edge#385]
I want use your solution on RaspberryPi device with Windows Iot 10, to call c# dll from node.js.
But it doesn't work (exception on startup "not found dll native/arm ...").

**Comment by tjanczuk** [comment]
Edge only works on x86 and x64 architectures out of the box. You can try your luck compiling for Raspberry, but this is an uncharted territory.

**Comment by ojosdegris** [comment]
I think you need to use Microsoft Node js repo to get support for ARM , as it has binding for Chakra to replace V8. I have not tried it, but Edge should work in such a scenario.

**Comment by ChangeTheCode** [comment]
Has someone tried to build it for Windows 10 IoT Core?
