### ISSUE TITLE
DLL dependencies

### ISSUE THREAD

**Issue by antonio-castellon** [tjanczuk/edge#393]
Dear developers,

I have a problem when I try to execute a C# dll (MyWrapperDLL.dll) that use some objects from another Dll ( 3thpartydll.dll ).

`var add7 = edge.func({

	source: function() {/*
	
		public class Startup
		{
			public async Task<object> Invoke(dynamic input)
			{
			
				MyWrapperDLL.Core c = new MyWrapperDLL.Core();
				
				c.MethodWithoutReference3thPartyObject(); // it's fine

 				c.MethodWITH_AReference3thPartyObject(); // fails
												  
				return "..executed ...." + input.ToString(); 
			}
		}
		
	*/},
	references: ['MyWrapperDLL.dll']
});`

the exception was : 

`    if (error) throw error;
               ^
 Error: Could not load file or assembly '3thpartydll, Version=2.2.0.1, Culture=neutral, PublicKeyToken=1cdbd1c0f2a1aa22' or one of its dependencies. Invalid pointer (Exception from HRESULT: 0x80004003 (E_POINTER))
    at Error (native)
    at <anonymous>:1:55
    at Object.<anonymous> (D:\DEV\TEST\REST-services\MyTest\edge-test.js:41:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
`

I tested:

- adding the 3th party Dll into the reference
- including a full path (but sure that is taking, because the error is different if the dll was not found).
- If I use the 3thpartyDll into another app, it has no problem to be executed (as an used reference resource because it is not an MarshalByRefObject).
- If I execute the MyWrapperDLL.dll using other environments (like jruby-win32ole), it has no problem to be executed

Any ideas?

Thanks in advance for your responses

Antonio

**Comment by antonio-castellon** [comment]
Oppssss...  I forgot that my Workstation is a 64 bits!!! the 3thparty dll was compiled to 32bits. I can use other...but my question now is different... exists any solution if you want to use a 32bits DLL into a 64bits environment? because in my case, the version for 64bits from the 3th party is not enough stable.

Thanks in advance for your help

**Comment by tjanczuk** [comment]
Yes you can use 32 bit DLLs in Edge on a 64 bit OS. For that to work you need to install 32 bit node.exe.

**Comment by antonio-castellon** [comment]
Oh wait... I forgot this point about node!  you're right I'm excuting the 64bit version from nodejs, Thanks!

**Comment by JohnyHHH** [comment]
Hi, i'm facing the same issue. I'm referencing 32bit C# dll, with my workstation is 64bit.
Tried install 32bit node.exe.
But the error Could not load file or assembly or one of its dependencies. An attempt was made to load a program with an incorrect format.
Any clues?
