### ISSUE TITLE
EdgeJs Argument Is Truncated At 10,000 chars

### ISSUE THREAD

**Issue by JamesA27** [tjanczuk/edge#398]
Hello, I am having an issue where I have a long serialized string (currently it is at 10,111 chars).

However, when I pass this into my edge.js function, I printed it out right away and it is being cut off at 10,000 characters.  Is there any way around this?

Thanks!
James

**Comment by JamesA27** [comment]
By the way, I should also mention...  THANK YOU!  Edge.JS is AWESOME!  The one suggestion I have is it took my a long time to find out that I needed to run "node-gyp configure build" when following the Linux tutorial.  Maybe that is common knowledge, but it wasn't for me when this is my first project in node.

**Comment by tjanczuk** [comment]
James, what version of Node and Edge are you using, on which OS, and can you provide a short repro?

Regarding the Edge installation, running `node-gyp` manually should not be necessary as long as you install Edge with `npm i edge` rather than cloning the repo.

**Comment by JamesA27** [comment]
Thanks for getting back so fast!
I am using Amazon Linux on my host.
Version info: https://justpaste.it/rzqp
Amazon Linux AMI release 2015.09
Node: 4.2.3
Edge: 5.0
Mono: 4.2.2

Clipped Code to Repro (pretty simple): https://justpaste.it/rzqu
Output: https://justpaste.it/rzqq

Thanks for getting back to me so quickly!
James

**Comment by JamesA27** [comment]
Ah, so sorry to bug you!  This is not an issue with Edge.js!  I don't know what is causing it but it doesn't seem to be edge.js.
 Thanks!
James

**Comment by tjanczuk** [comment]
Out of curiosity, what was the issue with?

**Comment by JamesA27** [comment]
Seems to be a character limit in my mysql database column.  Silly me.  I didn't catch it in the output initially since I was appending info to it.

Thanks for the prompt response and an extremely helpful product!

**Comment by JamesA27** [comment]
Is there any way to support your project via donation, etc?
