### ISSUE TITLE
Calling native x86 code from .NET on node.js x64 on x64 Windows

### ISSUE THREAD

**Issue by node2013** [tjanczuk/edge#40]
Hi,

Is it possible to call native 32-bit dll from .NET code in edge.js, using node.js x64 on Windows x64?

In console .NET application I can call my old 32-bit native dll (by DllImport). But using the same code with edge.js i get BadImageException. The same result I get If I try call x86 .NET assembly. 

So, I have to use x86 node.js because of using some legacy x86 components?

Another question, how about COM-s?  

I saw that IIS-node uses only x86 node.js. I have no special requirements for x64 for my app (but of course x64 version would be more great on x64 machines). So I should use x86 version, shouldn't I?

**Comment by johnleetechnology** [comment]
+1 -- I am wondering if any progress has been made?  My specific use case is that I would like to call a 3rd party .NET assembly that in turn references a 32-bit native C++ dll.
