### ISSUE TITLE
Building for OS X 

### ISSUE THREAD

**Issue by barisicm** [tjanczuk/edge#404]
I am following the instructions on how to build "edge" for OS X, but, when i type : sudo brew tap aspnet/dnx , i recieve an error such as : 

![marin_ _-bash_ _103x56](https://cloud.githubusercontent.com/assets/14875692/13745438/5b5208da-e9ee-11e5-8642-dceab9d2d3d9.png)

I am really not sure, what exactly is the issue here. 
If i try without the "sudo" part, it still wont work.

**Comment by jipan25** [comment]
try : sudo brew install aspnet/dnx
