### ISSUE TITLE
Clean install in Cloud 9 IDE

### ISSUE THREAD

**Issue by Konard** [tjanczuk/edge#407]
Trying to do a clean install at http://c9.io using this commands:

```
export USERNAME=ubuntu
sudo bash -c 'bash <(wget -qO- https://raw.githubusercontent.com/tjanczuk/edge/master/tools/debian_ubuntu_clean_install.sh)'
```

But I`m getting an error:

![2016-03-17 01-32-00](https://cloud.githubusercontent.com/assets/1431904/13830827/78c99790-ebe0-11e5-880b-8d06ecdb0b77.png)

```
The following packages have unmet dependencies:
 libgdiplus : Depends: libjpeg62-turbo (>= 1.3.1) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Any ideas how to fix it?

**Comment by Glidias** [comment]
bump me 2, did u solve this..
