### ISSUE TITLE
Edge.js hangs without throwing any exception

### ISSUE THREAD

**Issue by ahnesc** [tjanczuk/edge#410]
I'm trying to run Edge.js from .NET (C#) using example from https://github.com/tjanczuk/edge
class Program
{
    public static async Task Start()
    {
        var func = Edge.Func(@"
            return function (data, callback) {
                callback(null, 'Node.js welcomes ' + data);
            }
        ");
        Console.WriteLine(await func(".NET"));
    }
    static void Main(string[] args)
    {
        Start().Wait();
    }
}

I've got virtual machine with Windows 7 installed on mac (via pararells).
It runs fine in VS debug mode but in hangs in release or when running it in console or vs command line.
I've installed  Visual C++ Redistributable Packages for Visual Studio 2013  and tried compiling  it against x86 and x64 version. I confirmed if dlls are installed there and i've got them under c:\windows\system32 path. 
When I run it on dell laptop with same windows and same packages installed it works fine.
It does not throw any exceptions and it hangs when creating Edge.Func when running it in VM.

Any ideas what might be wrong?

Edge version 4.0.0
VS 2013

**Comment by cumminsjp** [comment]
I ran into this issue this morning--eventually figured out that it the fact that the sln path contained a junction.

http://stackoverflow.com/questions/38508189/how-to-resolve-edge-func-hanging/38509850#38509850
