### ISSUE TITLE
edge-cs.dll cannot be loaded in electron app when packaged in asar

### ISSUE THREAD

**Issue by kneumei** [tjanczuk/edge#411]
Not sure if this is the right place to ask this question, but I'm trying to use edge in my electron app (using https://github.com/kexplo/electron-edge). Everything works fine when I run the app unpackaged, however when I package the app into an asar file, I see 

```
Error: Could not load file or assembly 'file:///C:\app\v0.36.2\win32-x64\…s\app.asar\node_modules\electron-edge\node_modules\edge-cs\lib\edge-cs.dll' or one of its dependencies. The system cannot find the file specified.
    at Error (native)
    at Object.exports.func (C:\app\v0.36.2\win32-x64\resources\app.asar\node_modules\electron-edge\lib\edge.js:157:17)
```

I've found other threads (https://github.com/atom/electron/issues/1802, for example) saying that I need to unpack the dlls. I did that, but still seeing the errors. I'm thinking that whatever loads edge-cs.dll needs to know to look in the unpacked folder?

**Comment by JoaoGabrielBrasil** [comment]
Me too.
I am with this problem!

node_modules\edge-cs is not packed into asar archive - contains executable code
node_modules\electron-edge is not packed into asar archive - contains executable code

What I do?

**Comment by adairborba** [comment]
2

**Comment by adairborba** [comment]
Too. Same error.

**Comment by Unforgiven-wanda** [comment]
Same issue here as well. Really hoping for a fix.

**Comment by Unforgiven-wanda** [comment]
Well it seems there is a solution after all, thanks to [this](https://github.com/pwik/edge-asar-cs)
To fix this, I went inside my `node_modules` folder, deleted the `edge-cs` folder and replaced it with `edge-asar-cs`, after that I renamed this new folder `edge-asar-cs` into `edge-cs` and it worked.

I hope this helps someone else.
Good evening.

**Comment by Augus** [comment]
I hope this helps someone else.
`
var path = require('path');

exports.getCompiler = function () {
	return process.env.EDGE_CS_NATIVE || (process.env.EDGE_USE_CORECLR ? 'Edge.js.CSharp' : path.join(__dirname, 'edge-cs.dll').replace('app.asar', 'app.asar.unpacked'));
};

exports.getBootstrapDependencyManifest = function() {
	return path.join(__dirname, 'bootstrap', 'bin', 'Release', 'netstandard1.6', 'bootstrap.deps.json');
}
`

`
"asar":{
        "unpackDir": "node_modules/edge-cs/**"
},
`

**Comment by hohks12** [comment]
@Augus can you clarify what you mean by 'change electron-packager asar propertiy' ? I can't find which file to make this change.

**Comment by josiahbryan** [comment]
Same, what exactly do I need to change? 😁

**Comment by Augus** [comment]
@hohks12 https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#asar

**Comment by Dyinfalse** [comment]
@Augus I am logged in just to give you a compliment

**Comment by calebbergman** [comment]
> change electron-packager asar propertiy
> 
> "asar":{
>         "unpackDir": "node_modules/edge-cs/**"
> }
> 

You can also add it as a command line argument:
`electron-packager --asar.unpackDir=node_modules/edge-cs/**`
