### ISSUE TITLE
edge5.0 and nwjs0.13  is not a valid Win32 application.

### ISSUE THREAD

**Issue by WinterWoods** [tjanczuk/edge#414]
This error occurred while I was using edge5.0 and nwjs0.13. Don't know how to solve. Please guide

Uncaught Error: %1 is not a valid Win32 application.
\?\D:\work\客户端标准\Clients\nwjs-sdk-v0.13.3-win-x64\node_modules\edge\lib\native\win32\x64\5.1.0\edge_nativeclr.node

**Comment by VRastrigin** [comment]
Topic discussed and closed on [NW.JS version 0.13.4 + Edge version 5.0.0 example](https://github.com/frankhale/nw-edge-example/issues/6)
