### ISSUE TITLE
209_websocket.js memory usage

### ISSUE THREAD

**Issue by 0090491** [tjanczuk/edge#420]
I am running your 209_websocket.js example and I notice that the V8 process memory usage in task manager continues to grow.  I understand that the garbage collection is handled by V8, but is there a way to stop this from continuously growing? It doesn't appear to be a memory leak because when I do a heap snapshot in chrome from two different times over about a 30 minute period they are about the same size (1.8MB vs 1.9MB).  I am developing a app that essentially receives new lines of text every second very similar to this and eventually it consumes all of the servers ram.  I thought is was maybe how I was calling socket.io in edge that was producing this behavior, but I see that your sample has the same behavior.

**Comment by tjanczuk** [comment]
Did you run it long enough (hours) to determine if you see the characteristc see-saw pattern of memory usage when GC is involved?
