### ISSUE TITLE
Python modules

### ISSUE THREAD

**Issue by GianlucaBortoli** [tjanczuk/edge#424]
I was wondering if it supports importing modules in python (communication between NodeJs and Python).
I tried importing some modules I need, but the only one which seems okay is sys. When I try to import re in my python script, which is then called by NodeJs, I get an error saying "Error: No module named re".
Am I doing something wrong or is edge not supposed to work with all the python modules around?
Thanks in advance

**Comment by tjanczuk** [comment]
Python support in Edge.js has not seen a lot of use that I have seen, and I am not aware of people every trying out more advanced functionality. I don't know the answer to your question. If you find out please drop a line. For reference, here is the code responsible for integrating Python into Node.js: https://github.com/tjanczuk/edge-py/blob/master/src/edge-py/EdgeCompiler.cs. Maybe support for modules would require `ScriptEngine` to accept additional parameters.

**Comment by GianlucaBortoli** [comment]
After some tome trying to use third-party modules within edge, I found out that it is not possible unfortunately. For what I understood, at least, this operation is not supported at all. I just wanted to drop a line as @tjanczuk suggested
