### ISSUE TITLE
Node 6

### ISSUE THREAD

**Issue by ssmninja** [tjanczuk/edge#425]
Any idea if and when Node 6 will be supported?

**Comment by blackshadev** [comment]
+1

**Comment by AleCaste** [comment]
I tried to compile it myself using ```--msvs_version=2015``` (and ASP .NET 5 RC1) and although it compiles alright and I can start EDGE without getting any errors, some calls to DLLs through EDGE do not work.
So I guess something is not right.

**Comment by NickStrupat** [comment]
Has anyone tried the Node.js 6.1.0 libraries from electron? https://github.com/electron/electron/releases

They build a `node.dll` and keep it up to date.

**Comment by tjanczuk** [comment]
I haven't tried it. There are scripts in edge.js that build a shared node.dll for any version you desire (https://github.com/tjanczuk/edge/blob/master/tools/build_double.bat#L101-L119). I think it is good idea to keep the build step independent of external projects - there are enough moving parts as is to introduce another dependency.

**Comment by BillyWM** [comment]
@AleCaste: Can you provide any information on what sorts of API calls are not working when compiled for Node 6? We use Edge and are experimenting with Node 6 compatibility

**Comment by blackshadev** [comment]
Hi,
I tried building edge for node V6 numerous times but I can't make it happen.
I run windows 10 with VS2015 community edition installed. I installed the C++ tools and the build tools which node-gyp suggested. I tried anything suggested by the node-gyp guys, but it just doesnt want to build.

when I run `build.bat release 6.2.2` i get the following error(s)
```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build t
ools for v120 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, please install v120 bui
ld tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-cli
ck the solution, and then selecting "Retarget solution". [C:\Users\Vincent\Documents\GitHub\goconnect\Core\node_modules
\edge\build\build_managed.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build t
ools for v120 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, please install v120 bui
ld tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-cli
ck the solution, and then selecting "Retarget solution". [C:\Users\Vincent\Documents\GitHub\goconnect\Core\node_modules
\edge\build\edge.vcxproj]
```

When I tried build_double.bat I get the notorious `System.IO.PathTooLongException: The specified path, file name, or both are too long` exception.

Does anyone have any idea?

**Comment by AleCaste** [comment]
@BillyWM i will send you some details in the next few days. I have been quite busy lately. 
@blackshadev , I could build edge with node v6 successfully but only after installing the latest version of visual studio community and .NET libraries

**Comment by blackshadev** [comment]
@AleCaste Could you maybe post a step by step list of the things you do to successfully build edge for node 6.x.x?
I have tried it over multiple installations now and all did not work (and resolve in the same error). I have installed VS2015 on all these installations with the C++ common tools and python 2.7.

**Comment by fredericosilva** [comment]
@blackshadev did you change msvs_version from 2013 to 2015 on https://github.com/tjanczuk/edge/blob/master/tools/build.bat#L57 ?

**Comment by AleCaste** [comment]
Hello @blackshadev, this is what I did.
I built it a few weeks ago so I don't remember now if all steps were actually needed in the end...
But well.. here it is:

• From Node v6 onwards, you will need to update Visual Studio Community 2013 to 2015 version!
  • First, uninstall current version
  • Then download new version at:
  https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx
  • ... and install it
• Open a terminal, go to EDGE module folder and then:
```
npm install -g node-gyp    (if you have not done this before!!)
npm install nan
npm install --msvs_version=2015
npm config set msvs_version 2015
node-gyp configure --msvs_version=2015
```
• Open ./tools/build.bat and replace strings...
`--msvs_version=2013`
• ... with...
`--msvs_version=2015`
• Now we are ready to build...
```
cd tools
build.bat release 6.1.0
```

• NOTE: if you get the following error:
`"dnu" not recognized`
• ... that's because you don't have ASP .NET installed on the machine.
• Install it (http://docs.asp.net/en/latest/getting-started/installing-on-windows.html) and run:
`dnvm upgrade`

• FINALLY you must update:
`[edge]\lib\edge.js`
• ... Addding a new entry to the following map:
```
var versionMap = [
  ...
    [ /^6\./, '6.1.0' ],
];
```

**Comment by blackshadev** [comment]
@AleCaste It works! The missing step here was( as @fredericosilva mentioned) the replacement of the msvs_version in the build.bat file as well as the `npm install` within the edge folder.

Thank you so much, now I can finally update from node 4.x.

Maybe it is a good idea to add these instructions to the README.md, for me the information in the README was not enough to even get close to a working Edge module. I kept searching on google and came close, but I just missed the replacing of the msvs_version in the build.bat.

**Comment by Venryx** [comment]
@AleCaste Worked for me too, thanks!

Note for others reading: I got an error about a "CL.exe" file missing. Searched it up, and to fix, just run the Visual Studio Installer and install the "Visual C++ Compiler" components.

**Comment by tjanczuk** [comment]
edge@6.5.1 with node 6.x support has shipped.
