### ISSUE TITLE
EdgeJS and VSCode

### ISSUE THREAD

**Issue by mat-mcloughlin** [tjanczuk/edge#426]
Hey Guys,

This might be a bit of stab in the dark but I'm looking for some helping regarding calling out to EdgeJS from VSCode for a small project I'm working on

I imagine the problem is regarding recompiling but I'm not sure where to go. So any help would be appreciated 

The error I'm currently getting is 

```
Activating extension `test` failed: %1 is not a valid Win32 application.
c:\Git\test\node_modules\edge\lib\native\win32\ia32\4.1.1\edge_nativeclr.node.
Activating extension `test` failed:  %1 is not a valid Win32 application.
c:\Git\test\node_modules\edge\lib\native\win32\ia32\4.1.1\edge_nativeclr.node
Here is the error stack:  Error: %1 is not a valid Win32 application.
c:\Git\test\node_modules\edge\lib\native\win32\ia32\4.1.1\edge_nativeclr.node
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:140:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:140:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.n._load (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:20:23186)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\Git\test\node_modules\edge\lib\edge.js:48:8)
    at Module._compile (module.js:434:26)
```

Thanks,

**Comment by tjanczuk** [comment]
What app are you building? Is this regular desktop CLR app, a CoreCLR app, or something else?

**Comment by mat-mcloughlin** [comment]
Ah I may not have been clear in my description. This a VsCode extension that I am building

**Comment by Huachao** [comment]
Any updates on this thread?

**Comment by 928PJY** [comment]
Hey guys:
   I have got a same error ,have you solved this problem?

**Comment by mat-mcloughlin** [comment]
utimatley I ended up approaching my problem in a different way and build a console app in which to communicate with

**Comment by Huachao** [comment]
@mat-mcloughlin, can this way work cross-platform?

**Comment by mat-mcloughlin** [comment]
It can, depending on how you build it, but takes more effort. Take a look at the https://github.com/OmniSharp/omnisharp-roslyn project for some examples. Starting up the console application and then communicating with it via stdin and stdout

**Comment by Huachao** [comment]
So we can achieve this by writing the cross platform application based on .Net Core?

**Comment by mat-mcloughlin** [comment]
yup, pretty much

**Comment by bifacil** [comment]
Same problem here.

**Comment by bifacil** [comment]
Very relevant: https://github.com/Microsoft/vscode/issues/9527

**Comment by JohnZ622** [comment]
I am also facing the same problem.
I am running VS Code version 1.36.1 which uses Node.JS version 10.11.0

I use npm to get edge and use build.bat to build "release" against "10.11.0" target.  When activating my plugin, my plugin would run require('edge').
When attempting to load the edge module, I also hit the error "not a valid Win32 Application".

**Comment by gentledepp** [comment]
any update on this? I'd much rather call my dlls from Edge.js then using stdin/stdout :-|

@mat-mcloughlin:
If stdin/stdout is the only viable option, is there a simple tutorial as how to implement this?
The code base of OmniSharp is just too big and complext for me to see through :-(
