### ISSUE TITLE
Getting Async code running using Edge

### ISSUE THREAD

**Issue by vikrantb** [tjanczuk/edge#429]
I am calling Edge from c#

Here is the c# code that I have

var func = Edge.Func(@"return require('../edgeEntryPoint.js')");
var invoke = func.Invoke("");
var x = (dynamic)invoke.Result;
return x;

in the edgeEntryPoint.js file

I have

var bower = require('C:/Users/vikrantb/AppData/Roaming/npm/node_modules/bower/lib/');
module.exports = function (data, callback) {
var result = '';
    function updateobj(r) {
result = r;
    };

    bower.commands.search('lua', {}).on('end', function(results) {
        updateobj(results);
    });

   callback(null, results);
};

But the callback returns and the object is null. I think it is some problem with managing async
Do you know if this can be done in Edge?

**Comment by glennblock** [comment]
You call to callback needs to be moved to right after updateobj(results).
You are calling it now immediately not when 'end' is called hence results
has not been initialized.

**Comment by tjanczuk** [comment]
Please reactivate if any questions remain.
