### ISSUE TITLE
run as node 6.2.0

### ISSUE THREAD

**Issue by longang520** [tjanczuk/edge#438]
My project using node version 6.2.0 I want to how to compile the corresponding version

**Comment by forensicsguy20012004** [comment]
I would tend agree with you, whatever the newest version of Node would be.

**Comment by marcobarcelos** [comment]
Hello there,
I've added support for node versions 6.x in pull request #437 .
If you want to compile though you can run the script **tools/build.bat release \<node_version\>** on windows.
Please check https://github.com/tjanczuk/edge/blob/master/README.md#building-on-windows for more info.

**Comment by longang520** [comment]
error info:
`Building edge.node release for node.js x64 v6.2.0
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@6.2.0 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\78967\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2013',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\edge-master\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\78967\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\78967\\.node-gyp\\6.2.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\78967\\.node-gyp\\6.2.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\78967\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\edge-master',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\edge-master\\build',
gyp info spawn args   '-Goutput_dir=.' ]
module.js:440
    throw err;
    ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:541:32)
    at node.js:329:29
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\78967\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.14352
gyp ERR! command "C:\\edge-master\\lib\\native\\win32\\x64\\6.2.0\\node.exe" "C:\\Users\\78967\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build" "--msvs_version=2013" "-release"
gyp ERR! cwd C:\edge-master
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
Error building edge.node release for node.js x64 v6.2.0`

**Comment by longang520** [comment]
npm install nan

error:
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/RuntimeLibrary to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  utils.cpp
  clrfunc.cpp
  clrfuncinvokecontext.cpp
  nodejsfunc.cpp
  nodejsfuncinvokecontext.cpp
  persistentdisposecontext.cpp
  clrfuncreflectionwrap.cpp
  clractioncontext.cpp
  v8synchronizationcontext.cpp
  edge.cpp
     正在创建库 C:\edge-master\build\Release\edge_nativeclr.lib 和对象 C:\edge-master\build\Release\edge_nativeclr.exp
  LINK : 已指定 /LTCG，但不需要生成代码；从链接命令行中移除 /LTCG 以提高链接器性能
  edge_nativeclr.vcxproj -> C:\edge-master\build\Release\\edge_nativeclr.node
  v8synchronizationcontext.cpp
  edge.cpp
  coreclrembedding.cpp
  coreclrfunc.cpp
  coreclrnodejsfunc.cpp
  coreclrfuncinvokecontext.cpp
  coreclrnodejsfuncinvokecontext.cpp
  utils.cpp
                                                                                                                  正在创建库 C:\edge-master\build\Release\edge_coreclr.lib 和对象 C:\edge-master\build\Release\edge_coreclr.exp
  正在生成代码
  已完成代码的生成
  edge_coreclr.vcxproj -> C:\edge-master\build\Release\\edge_coreclr.node
  compile_coreclr_embed
  'dnu' 不是内部或外部命令，也不是可运行的程序
  或批处理文件。
  'dnu' 不是内部或外部命令，也不是可运行的程序
  或批处理文件。
  系统找不到指定的路径。
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6006: “cmd.exe”已退出，
代码为 1。 [C:\edge-master\build\build_managed.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\78967\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.14352
gyp ERR! command "C:\\edge-master\\lib\\native\\win32\\x64\\6.2.0\\node.exe" "C:\\Users\\78967\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build" "--msvs_version=2013" "-release"
gyp ERR! cwd C:\edge-master
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
Error building edge.node release for node.js x64 v6.2.0

**Comment by longang520** [comment]
https://github.com/frankhale/nwjs-edge-example1/issues/6
and
lib\edge.js add
var versionMap = [
    [ /^0\.8\./, '0.8.22' ],
    [ /^0\.10\./, '0.10.0' ],
    [ /^0\.12\./, '0.12.0' ],
    [ /^4\./, '4.1.1' ],
    [ /^5\./, '5.1.0' ],
    [ /^6\./, '6.2.0' ],
];

**Comment by marcobarcelos** [comment]
Do you have dnx/dnvm installed?
If so, try running **dnvm upgrade**.
You should be able to run the 'dnu' command in your cmd in order to build the coreclr version of edge.

**Comment by eblumenfeld** [comment]
Any news about when support for 6.x will be merged in the npm package
without the need to compile?

**Comment by EricSmekens** [comment]
@eblumenfeld, it assume that will land as soon this PR is through:
https://github.com/tjanczuk/edge/pull/442

**Comment by sickboy** [comment]
I have a 6.3.1 fork at https://github.com/sickboy/edge
(and for those interested, a 1.3.1 Electron fork at https://github.com/sickboy/edge/tree/electron)

So far no double-edge, just Node -> C#

**Comment by tjanczuk** [comment]
Official edge@6.5.1 with support for node 6.x is now on NPM.
