### ISSUE TITLE
StackOverflowException

### ISSUE THREAD

**Issue by eblumenfeld** [tjanczuk/edge#441]
Hi,

I'm finding a problem with edge compiled for node 6.2

With edge-sql, when the connection string is incorrect,
edge throws:
Process is terminated due to StackOverflowException.

and terminates the program...

**Comment by EricSmekens** [comment]
Can you post some code? I've encountered this error myself, but that was due to an error on my side, not edge. If you can post it, we might be able to see where the error is caused.

**Comment by eblumenfeld** [comment]
It just happens when the connection string is wrong:

`
var edge = require('edge');
var sqlconn = "Server=xxx;..."
var par = {}
var edgefunc = edge.func('sql',{source: "SELECT top 2 * FROM table", connectionString: sqlconn})
edgefunc(par, function (err,data) {
   if (err) { console.log(err)
  } else {
     console.log(data)
  }
}
`
This is an excerpt of the code,
when the connection string is correct, the code runs,
but when the connection string is wrong (i.e. additional character in the server name, wrong password, etc.) it just gives the message:
Process is terminated due to StackOverflowException.

**Comment by tjanczuk** [comment]
Official edge@6.5.1 with support for node 6.x just shipped. If you continue experiencing this issue please reopen.

**Comment by Vishnu-Sankar** [comment]
Hello All,

I am getting same error for node 7.1, do i need to downgrade.

-Vishnu

**Comment by Vishnu-Sankar** [comment]
Hi All,

Got worked, downgraded to 6.1.1.
Thanks anyway.
-Vishnu
