### ISSUE TITLE
Is it possible to catch async javascript exceptions in .net using edge.js?

### ISSUE THREAD

**Issue by ashelley** [tjanczuk/edge#444]
I was hoping to try to use edge.js because i don't like that I can't prevent node from crashing.  Is it possible to use edge.js to run a program so that the program does not completely fail if an asynchronous javascript error is thrown?

Currently it seems any asynchronous javascript error will kill the .net process (in a console app or while running in iis).  

Edge.js 5.9.1

Steps to reproduce:

1) Run this program
2) See that no exception handler is caught and the process dies.

```
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                MainAsync().Wait();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Exception: " + ex.Message); // never gets here
            }
            Console.ReadLine();
        }

        static async Task MainAsync()
        {
            var func = Edge.Func(@"
                return function(arg, done) {
                    setTimeout(function() {
                        throw new Error('test');          
                    }, 0)
                }
            ");
            try
            {
                var text = await func("hello");
                Console.WriteLine("text is " + text); 
            }
            catch (Exception ex)
            {
                Console.WriteLine("js exception was caught " + ex.Message); // never gets here
            }
            Console.WriteLine("javascript finished");
        }
    }
```

**Comment by tjanczuk** [comment]
Not crashing the process when an unhandled asynchronous exception is thrown is generally speaking a bad idea. At this point you don't know what is the state of in-memory resources in your app. It is very likely you are leaking some of them (memory, handles, etc). 

Only valid reason I am aware of to prevent the process from immediately crashing is to give it a second or two to flush out any buffers, and then exit. This is how it can be done in Node:

```
process.on('uncaughtException', (e) => {
  // do some logging, say goodbye
  setTimeout(() => process.exit(1), 500);
});
```

**Comment by eoconnor77** [comment]
Hi - wondering if a work around was ever found for this ?

We are experiencing similar with similar setup but in our case when the async execution raises an error we are seeing node processes being orphaned when the handling process for ,net crashes 

IIS is handling our node basis - and the crash is resulting in app pool crashing and restarting but causing the original process to become orphaned
