### ISSUE TITLE
EdgeJs hangs when calling from an ASP.NET Web API controller running IIS

### ISSUE THREAD

**Issue by SpiegelSoft** [tjanczuk/edge#445]
I have a .NET API Controller that is just this:

`    public class EdgeTestController : ApiController
    {
        public async Task<IHttpActionResult> Post()
        {
            var func = Edge.Func(@"
                return function (data, callback) {
                    callback(null, 'Node.js welcomes ' + data.text);
                }");

```
        var value = await func(new { text = ".NET" });
        return Ok(value);
    }
}
```

`

If I launch the project in IIS Express, this basic endpoint works without a problem.  If I change the project to run on IIS, the call to `Edge.Func` hangs and then IIS crashes.

I have IISNode installed: version 0.2.21 (x64).

I have tried to build the latest version of IISNode from the GitHub project, but the compiler falls over with these errors:

debugger_autogenerated.rc(6): error RC2148: expected numeric constant in string table [C:\Users\Rob\Documents\GitHub\iisnode\src\iisnode\iisnode-inspecto
r.vcxproj]

debugger_autogenerated.rc(6): error RC2110: expected numerical string id [C:\Users\Rob\Documents\GitHub\iisnode\src\iisnode\iisnode-inspector.vcxproj]

debugger_autogenerated.rc(6): error RC2150: expected string in STRINGTABLE [C:\Users\Rob \Documents\GitHub\iisnode\src\iisnode\iisnode-inspector.vcxproj]

Done Building Project "C:\Users\Rob\Documents\GitHub\iisnode\src\iisnode\iisnode-inspector.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\Users\Rob\Documents\GitHub\iisnode\src\iisnode\iisnode-inspector.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\Users\Rob\Documents\GitHub\iisnode\src\iisnode\iisnode.vcxproj.metaproj" (default targets) -- FAILED.

Done Building Project "C:\Users\Rob\Documents\GitHub\iisnode\src\iisnode\iisnode.sln" (default targets) -- FAILED.

Build FAILED.

"C:\Users\Rob\Documents\GitHub\iisnode\src\iisnode\iisnode.sln" (default target) (1) ->
"C:\Users\Rob\Documents\GitHub\iisnode\src\iisnode\iisnode.vcxproj.metaproj" (default target) (2) ->
"C:\Users\Rob\Documents\GitHub\iisnode\src\iisnode\iisnode-inspector.vcxproj" (default target) (3) ->
"C:\Users\Rob\Documents\GitHub\iisnode\src\iisnode\iisnode-inspector.vcxproj" (default target) (3:2) ->
(ResourceCompile target) ->
  debugger_autogenerated.rc(6): error RC2148: expected numeric constant in string table [C:\Users\Rob\Documents\GitHub\iisnode\src\iisnode\iisnode-inspec
tor.vcxproj]
  debugger_autogenerated.rc(6): error RC2110: expected numerical string id [C:\Users\Rob\Documents\GitHub\iisnode\src\iisnode\iisnode-inspector.vcxproj]
  debugger_autogenerated.rc(6): error RC2150: expected string in STRINGTABLE [C:\Users\Rob\Documents\GitHub\iisnode\src\iisnode\iisnode-inspector.vcxproj
]

**Comment by cdcdcdcdcd** [comment]
Direct calls from my controller thread hang but, if I wrap the calls in a Task.Factory.StartNew() it works.
