### ISSUE TITLE
In every way I  tried, edge.js, I failed for external dll scenerio :(, need help and step by step description.

### ISSUE THREAD

**Issue by tsiddikee** [tjanczuk/edge#447]
Dear Janczuk and other contributors friends of edge.js,
It will be a big help, if some one help me out.
This is a letter specially written for Janczuk :)
--Would you please give a clear documentation, step by step explanation for working with external dll ?
--If the external dll has 3rd party dependency which is not included in GAC, then will it work?.
just by few bullet points please explain.
--Is it necessary to add the dll to GAC?
--if not then is it a must to add the dll to the directory where nodejs exe is?
--When you said edge.js only can read proper strong name dll, what do you mean by that ? Does that mean snk and GAC is a must?
--I have big software engine as dll for my small plugin dll, so how I will call that additional dependency(big software engine as dll) for newly created small plugin dll, which is not included in GAC, to edge.js ?

If you say , you have explained all above question, then I would say, you have answered fractional in many places, as bits and pieces in many places,  so it is highly confusing for a beginner.
So my humble request to you, please please, give a description with some bullet points for 3rd party c# dll integration in edge.js.
I have already invested my two weeks on this struggle :( Please help. 
My hundreds of c# dll will be in use, if this works well. 
Best regards
T

**Comment by SeanHogg** [comment]
hi @tsiddikee below is a sample using an external DLL.

```
var edge = require('edge');
 
 
 var dto = edge.func(
    {
        source: function() {/*
            async (dynamic input) =>
         {
             UrbanScience.S4.CM.DTO.Report.ActionItem action = new UrbanScience.S4.CM.DTO.Report.ActionItem();
             System.Diagnostics.Debugger.Break();
             return action;
         }
      */},
      references: ["System.Linq.dll","C:\\Training\\NodeJSEdgeJS\\SomeExternalDll.dll"]
    });

module.exports = dto;

```

All you need to do is add your external DLL to the references property.
references: ["System.Linq.dll","C:\\Training\\NodeJSEdgeJS\\SomeExternalDll.dll"]

If you don't specify the full path then you must GAC the assembly. I'd recommend against doing this.
Hope this helps.

**Comment by tjanczuk** [comment]
It is documented in more depth here: https://github.com/tjanczuk/edge#how-to-specify-additional-clr-assembly-references-in-c-code
