### ISSUE TITLE
Edge.js handling of TimeSpan instances

### ISSUE THREAD

**Issue by JohnVolkar** [tjanczuk/edge#448]
We have been using Edge.js successfully with a C# based domain model but have recently encountered an unpleasant issue.  We have a domain object that has a property called Duration of type TimeSpan.   We generally have been using JSON.NET JsonConvert (with some DefaultSettings) to result in TimeSpans serialized as "HH:MM:SS.fff" format in other areas of our application.   

We had (perhaps naively/wrongly) assumed that Edge.js was using JsonConvert and those settings would apply and that the duration property being sent to the client side would look like Duration: "00:01:24".   However we instead see a very ugly and awkward representation of a TimeSpan like:

"Duration": {
                "Ticks": 840000000,
                "Days": 0,
                "Hours": 0,
                "Milliseconds": 0,
                "Minutes": 1,
                "Seconds": 24,
                "TotalDays": 0.0009722222222222222,
                "TotalHours": 0.02333333333333333,
                "TotalMilliseconds": 84000,
                "TotalMinutes": 1.4000000000000001,
                "TotalSeconds": 84
              },

While this can be kinda used by the client side by just telling them to work with one of the TotalXXX fields, we have an issue when the data is sent back to the server and then back into C# via an edge call.  When the data comes back into the C# side, we "sanity check" it by essentially forcing it to a Json representation and then deserializing into the expected strongly type C# class.   Deserialization of the verbose TimeSpan format above of course fails.

Is there any way to instruct Edge.js to render TimeSpan instances as javascript friendly "HH.MM.SS" so that client side can be more clean and so that round tripping works reasonably?

Any suggestions for handling this situation are welcome.  (No, we cannot easily change the domain model classes to not use TimeSpan values.)

**Comment by JohnVolkar** [comment]
Abandoned.

**Comment by agracio** [comment]
Moved to https://github.com/agracio/edge-js
