### ISSUE TITLE
.NET 4.6.1 support 

### ISSUE THREAD

**Issue by sergiusignacius** [tjanczuk/edge#457]
Hey guys, 

Are there any plans to support the latest version of .NET (4.6.x)?

Cheers,

**Comment by forensicsguy20012004** [comment]
I agree with you. Will the eventual release that supports 4.6.x also support Node 6.x.x and visual studio 2015? Thanks

**Comment by tjanczuk** [comment]
edge@6.5.1 with support for node 6.x and a nuget package that works with VS 2015 shipped.
