### ISSUE TITLE
vscode Extension with edge Problem

### ISSUE THREAD

**Issue by 928PJY** [tjanczuk/edge#460]
Hi 

this problem maybe relate to [#426](https://github.com/tjanczuk/edge/issues/426)  ,but there is something different.

In the beginning , I tried to require the edge like [#426](https://github.com/tjanczuk/edge/issues/426),and then I got a same problem .

But when I run "npm install edge --arch=ia32" ,and then I got a error as followed:

```
The specified module could not be found.
\\?\e:\Docfx\test\extensionTest\jscallTest\node_modules\edge\lib\native\win32\ia32\5.1.0\edge_nativeclr.node
```

Any guidance would be appreciated!

**Comment by mikeebowen** [comment]
Any updates on this? I have the same error in 2021 :-(
