### ISSUE TITLE
build_double.bar download error

### ISSUE THREAD

**Issue by raffaeler** [tjanczuk/edge#462]
I had a 404 when running build_double.bat on:
https://github.com/nodejs/node/archive/v%1.zip ==> vrelease.zip
And in fact the browser gives the same error.

Does anybody know what is the new URL?

TIA

**Comment by tjanczuk** [comment]
Which version were you trying to build?

**Comment by raffaeler** [comment]
I resolved this issue when re-cloning the newest release last week.
My new problem is with .NET Core (#463)
Thank you anyway
