### ISSUE TITLE
node.dll dependency not being moved to bin folder

### ISSUE THREAD

**Issue by mattclaess** [tjanczuk/edge#472]
I noticed this issue when I tried to install this package through the nuget package manager in VS. 

On build it was not copying the node.dll to the output directory. This caused the program to throw a missing node.dll exception when run. (should be copying the folder named "edge" which contains node.dll to the output folder). 

I believe the Edge.js nuget package is setup incorrectly for moving these dependencies.

A good example of how this should be done is how JavaScriptEngineSwitcher.V8 moves its dependency ClearScript.V8.
Can you please take a look at how this nuget package moves its dependencies and update the Edge.js package? 
Let me know if you have any questions, I am willing to help.

**Comment by koltyakov** [comment]
I'm wondering, any update on this?
