### ISSUE TITLE
SignalR not working on Microsoft Edge browser windows 10

### ISSUE THREAD

**Issue by rishidevendra** [tjanczuk/edge#478]
I am working on an application which uses SignalR library to communicate between client and server (basically pushing contents from server to multiple clients). Everything is working fine in all the major browsers except Microsoft Edge v20.1.

Giving some more details -

this application is running on a remote machine(server inside our intranet) that can be accessed by my team's local machines. Hub in this case is running at local machines. putting this in perspective, in order to run our application we require private resources from local machines or hubs.

We have taken care of the CORS permissions also (using HubConfiguration). I know edge supports websocket but it is showing some network error while negotiating with the hub.

    SCRIPT7002: XMLHttpRequest: Network Error 0x2efd, Could not complete the >operation due to error 00002efd.

I want to know whether edge supports this kind of access to resources in cross domain, because from what i have understood, for security purposes it runs in a sandbox environment (in an appcontainer) which do not have access to private resources.

**Comment by tjanczuk** [comment]
This project (Edge.js) is unrelated to Microsoft Edge browser. Edge.js allows in-process interop between Node.js and CLR.
