### ISSUE TITLE
Hang on Promise.resolve(...)

### ISSUE THREAD

**Issue by mamaso** [tjanczuk/edge#485]
This seems to be related to #329 #373 #381 

I'm able to get around the problem if I initiate a dummy call to setImmediate or setTimeout which gets the event loop flowing.

Is there a known root cause or fix for this issue in the works?

Sample code below:

``` c#
    class Program
    {
        public static async Task Start()
        {
            var func = Edge.Func(@"
                return function (data, callback) {

                    // UNCOMMENT TO AVOID HANG
                    // setImmediate(() => {});

                    Promise.resolve('resolve').then((d) => {
                            callback(null, d);
                        })
                        .catch(callback);
                }
            ");

            Console.WriteLine(await func(".net"));
        }
        static void Main(string[] args)
        {
            Start().Wait();
        }
    }
```

**Comment by davideicardi** [comment]
Is there any news on this topic? I have the same problem....

**Comment by arnaudbzn** [comment]
We do have the same issue.

We use the same workaround:
```  setImmediate(() => {}); ```

**Comment by dpolivy** [comment]
This is related to #325. I'm working on a fix; you can follow along in that issue for details.

**Comment by dpolivy** [comment]
A fix was just released which should address this. See if the latest release (`edge@7.10.0`) fixes the problem and report back!
