### ISSUE TITLE
Return a JSON string from C# to NodeJS

### ISSUE THREAD

**Issue by fforjan** [tjanczuk/edge#497]
Dear people,

My C# code is already having a JSON object as a string and I would like to return it to the NodeJS.

```
void string DoSomething() {
    return "[ { 'myObject': 1}, {'myObject':2}]";
}

Is there a way to not escape the string so I don't need to parse it in NodeJS side and so it can be see as a JSon object ?
```

**Comment by hosseinsalemi** [comment]
Did you find any answer?

**Comment by fforjan** [comment]
Nop, I endup doing the extra json parse  on the consumer side...

**Comment by therightstuff** [comment]
If you want edge.js to return a JSON object, you'll need to return an ExpandoObject that's correctly JSON-formatted (keys must be strings). Otherwise, you'll need to do that "extra" parsing.
