### ISSUE TITLE
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by kevlangdo** [tjanczuk/edge#499]
I can't install electron-edge in VS2015. I am using node v 4.6.0

====Executing command 'npm install electron-edge --save '====

npm WARN package.json edgy@0.0.0 No repository field.
npm WARN package.json edgy@0.0.0 No license field.

> electron-edge@6.5.2 install c:\users\kevla\documents\visual studio 2015\Projects\edgy\edgy\node_modules\electron-edge
> node tools/install.js
> c:\users\kevla\documents\visual studio 2015\Projects\edgy\edgy\node_modules\electron-edge\tools\install.js:80
>             let electronPath;
>             ^^^
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Function.Module.runMain (module.js:441:10)
>     at startup (node.js:139:18)
>     at node.js:974:3
> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "electron-edge" "--save"
> npm ERR! node v4.6.0
> npm ERR! npm  v2.15.9
> npm ERR! code ELIFECYCLE
> npm ERR! electron-edge@6.5.2 install: `node tools/install.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the electron-edge@6.5.2 install script 'node tools/install.js'.
> npm ERR! This is most likely a problem with the electron-edge package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node tools/install.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs electron-edge
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR! 
> npm ERR!     npm owner ls electron-edge
> npm ERR! There is likely additional logging output above.
> npm ERR! Please include the following file with any support request:
> npm ERR!     c:\users\kevla\documents\visual studio 2015\Projects\edgy\edgy\npm-debug.log

====npm command completed with exit code 1====

**Comment by MikeGitIt** [comment]
I am having the same problem as mentioned above and am only stating it here to help provide some scope to the extent of the problem itself.  I am using the npm to attempt an install to a regular electron project. In other words, I am not doing this within a Visual Studio project.

**Comment by JoaoGabrielBrasil** [comment]
am having the same problem as mentioned with version electron-edge 6.5.2

What I do?

**Comment by dougludlow** [comment]
Running in to this as well with node v4.4.5 using electron-edge v6.5.2:

```
> electron-edge@6.5.2 install C:\project\node_modules\electron-edge
> node tools/install.js

C:\project\node_modules\electron-edge\tools\install.js:80
                        let electronPath;
                        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
npm WARN install:electron-edge@6.5.2 electron-edge@6.5.2 install: `node tools/install.js`
npm WARN install:electron-edge@6.5.2 Exit status 1
```
