### ISSUE TITLE
Node.js 7.0.0 Support?

### ISSUE THREAD

**Issue by forensicsguy20012004** [tjanczuk/edge#507]
Any chance we will see this support coming coming soon with the next PR merge?

**Comment by forensicsguy20012004** [comment]
I believe there is a PR to support node 7.0.0 and it looks like all checks are passing...just need to get it merged in with the main branch.

**Comment by forensicsguy20012004** [comment]
So, a month has now passed by...I see two other folks would like node 7.x.x support as well. Any thoughts of when this might make it in?

**Comment by sylvain-hamel** [comment]
Hi, I also need node 7 support. Any news on this?

**Comment by forensicsguy20012004** [comment]
Any movement on the node 7 support?

**Comment by wtchangdm** [comment]
Is this project abandoned?

**Comment by forensicsguy20012004** [comment]
I tend agree...is this project dead? If not let's get working on some of these issues.

**Comment by jdzurik** [comment]
It looks like some of the .net to node tooling is being adopted by 
https://github.com/aspnet/JavaScriptServices

looks similar to edgejs but i have seen nothing from node to c# version.

**Comment by cobarx** [comment]
It seems like the maintainers haven't been active in about 5 months. I would think the best bet would be for someone familiar with the code to fork the project and merge many of the PRs. Then if the original maintainer returns, they can grab all the changes off the fork and continue development.

**Comment by sylvain-hamel** [comment]
I sent an email to Tomasz today about this. I mentioned this thread so he might reply here or I'll let you if he replies to my email.

**Comment by forensicsguy20012004** [comment]
Thank you everyone for helping out

**Comment by forensicsguy20012004** [comment]
Has anyone heard from any of the repository owners or maintainers? I am hoping someone could get this project moving forward. There are a lot of questions out there that need answers and I see some pull requests.

**Comment by sylvain-hamel** [comment]
Tomasz did not reply to my email.

**Comment by forensicsguy20012004** [comment]
Ok, thanks for the update. So does anyone have the time and resources to pick up the repository and get it rolling agaon?

**Comment by radencode** [comment]
Look like no one is working on this project anymore

**Comment by forensicsguy20012004** [comment]
Yeah, I know. Can someone pick up and at the least compile something for v7.x?

**Comment by wtchangdm** [comment]
https://github.com/tjanczuk/edge/commit/be779036f291ff2422932321cff7e3cda0633c6d

**Comment by forensicsguy20012004** [comment]
Thank you, I am closing.
