### ISSUE TITLE
NetFx40_LegacySecurityPolicy in node.exe.config crashes node

### ISSUE THREAD

**Issue by alejandrocibilich** [tjanczuk/edge#513]
I'm trying to integrate a .NET assembly written for .NET v3.5 to node. To be able to run this assembly on .NET v4.5, app.config (node.exe.config) should contain theese lines:

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <NetFx40_LegacySecurityPolicy enabled="true"/>
  </runtime>
</configuration>`

This is crashing node when calling `require('edge')`.

Win7 x64
Node v6.9.1 x64
Edge.js v6.5.1

**Comment by kluce41** [comment]
Hi, 

I'm trying to do same thing, and it's also crash.
I'm using "NetFx40_LegacySecurityPolicy enabled" to use PosExplorer in C# code
Is there a workaround to use PosEplorer in C# code ?

Thanks
