### ISSUE TITLE
Stackoverflow error

### ISSUE THREAD

**Issue by aguarino77** [tjanczuk/edge#517]
I am stuck with a mysterious Process is terminated due to StackoverflowException error. 

My node.js code:
```
var edge = require('edge');

var clrMethod = edge.func({
    assemblyFile: 'CasaleThermoLibProxy.dll'
})

clrMethod(null, function (error, result) {
        console.log(__dirname);
        if (error) throw error;
        console.log(result);
    });

```

Where the .dll is a .NET dll very simple and works as a charme when called from .NET console programs:

```c#
using ThermoNET;

namespace CasaleThermoLibProxy
{

    public class Startup
    {
        public async Task<object> Invoke(dynamic input)
        {
            CTPackage pack = new CTPackage(CTPackageType.ACSRK);
            double[] flows = new double[] { 134.210480475601, 44.6238443375161, 26.4768768323874, 0.000000000000000, 49.3687983544959, 0 };
            flows = flows.Select(x => x / 3.6 * 0.743).ToArray();
            CTFluid feed = new CTFluid(pack, 297e5, 375 + 273.15, flows);
            return null;
        }
    }
}
```

ThermoNET is a C++/CLI dll which works in any .NET environment and is correctly found by the code.
The "killer" is the CTFluid constructor. Although **there are no circular references** in the CTFluid class. Inspecting the call stack I see that a recursive call appears between

```
...
 	edge_nativeclr.node!ClrFunc.MarshalCLRObjectToV8() + 0x243 bytes	
 	edge_nativeclr.node!ClrFunc.MarshalCLRToV8() + 0xc04 bytes	
```

=> Why is edge.js trying to marshal data if it is not in the return object?
=> How can I discover what is the object that triggers this circular call? CTFluid is quite complicated, but the only member that is "suspicious" is 
=> Is a C++/CLI class supported?
```c++
		array<CTPhase^> ^Phases;
```

but CTPhase is a simple class (and by the way can get called by edge.js very fine)

**Comment by aguarino77** [comment]
Can this be because the referred library is compiled with .NET 4.0?

**Comment by SeanSnyders** [comment]
@aguarino77 have you solved your issue? I'm having a similar `StackOverflowException`, but the c# code I'm calling from Edge is compiled using .Net Core.
Check out my issue here: https://github.com/kexplo/electron-edge/issues/31
