### ISSUE TITLE
Link to edge node.dll for native modules

### ISSUE THREAD

**Issue by mamaso** [tjanczuk/edge#518]
I've compiled a basic 'hello world' native module via node gyp for ia32 v6.5.0 on windows.  The module works correctly when running with node exe.  However, when I try to require the module inside an edge script, I get the error: `A dynamic link library (DLL) initialization routine failed`.

A look at edge's readme shows this relevant section: https://github.com/tjanczuk/edge#how-to-use-external-nodejs-modules, in particular `Native binary modules will not run in Edge unless they are rebuilt to link against the NodeJS dll that Edge uses`.

I assume that the dll error is due to not linking against the x86/node.dll that edge provides.  I tried adding the dll to the 'delay loaded dlls' section in the vs project linker properties, but that did not resolve the errors.

How can I correctly link against the edge node.dll for my native module?  Are there any examples of such native modules?

**Comment by sergiomieic** [comment]
Is there any update on this? A workaround at least? @mamaso
