### ISSUE TITLE
install edge

### ISSUE THREAD

**Issue by manuvnath** [tjanczuk/edge#531]
I am a .NET developer and new to electron and node.js.

From my electron application, I need to call one function inside a .NET class library DLL which will generate some document and will send to print.

I need to use this electron application only on the windows machine. But am not sure this will work for me and also don't know how to include in my project.

**Comment by FairSite2C** [comment]
What does only on windows mean? Includes in your node or c#?

**Comment by manuvnath** [comment]
https://www.npmjs.com/package/edge-js
