### ISSUE TITLE
Using edge with latest node 7 question

### ISSUE THREAD

**Issue by FairSite2C** [tjanczuk/edge#532]
Not an issue but more of an info quest. I am using node 6.9.5 and promises seem to work ok. I want to use the await keyword but it is available in node. 7.6 which was released Feb 2017. Seems to be some questions of edge comparability with node 7. Has anyone used edge with await? 

If I can figure out how to install 7 as an experimental local version I will answer my own question and post it here.

Thanks for any consideration.

**Comment by FairSite2C** [comment]
Decided to do a hey man hold my beer and installed node globally and  built edge with version 7.7.3
this thread got me good with the python part

http://stackoverflow.com/questions/15126050/running-python-on-windows-for-node-js-dependencies

npm install --global --production windows-build-tools

npm install --global node-gyp

there was some persnickery with the python environmental variable but all was well.

build.bat version 7.7.3 worked out until the c++ compile and it bombed. Seems could not open build\edge_nativeclr.vcxproj. LINK: fatal error LNK1104.

I loaded the project into visual studio 2015 and compiled from there. 

WORKED!!

Haven't extensively tested but it did load and interact with edge and promises worked. So far so good. Still green but will be testing await plus other things.

**Comment by agracio** [comment]
Actually worked for me just using the build script, without opening it in VS. However only works in `release` mode.

**Comment by dpolivy** [comment]
`edge@7.10.0` now supports node v7, and fixes the debug build issue.
