### ISSUE TITLE
Is this module/repo dead?

### ISSUE THREAD

**Issue by hajikelist** [tjanczuk/edge#533]
Calling node.js from .net
#522 by harivasista was closed on Feb 16

Looks like the last closed issue in this module was several months ago! That's not a good sign.

**Comment by agracio** [comment]
I looked at tjanczuk twitter and other projects he is working on and it appears that he is very active elsewhere, but is ignoring `edge` project. It is not clear why, official statement from him on this matter would have helped.
I have created a fork of the repo and published it to npm, you can take a look here: https://github.com/tjanczuk/edge/issues/541

**Comment by hajikelist** [comment]
We're bailing on this hard. No sense in trying to use something of this level of complexity that isn't actively supported. Way too mission critical...
