### ISSUE TITLE
Node 7.x support using edge repo fork

### ISSUE THREAD

**Issue by agracio** [tjanczuk/edge#541]
As I needed Node 7.x support in our internal production apps, I have created a fork of the current edge repo and added Node 7.8 support to it. It is published to npm as `edge-js` and version 6.5.8 was tested to work in our apps. We will work on version 6.5.9 testing today.
If anyone interested, take a look at https://github.com/agracio/edge.
If there are issues that you need addressed, feel free to submit a PR and I will do my best to test and publish it ASAP.

**Comment by agracio** [comment]
Release 6.6.1 addresses a few issues including Mono 4.8 support on MacOS/Linux https://github.com/agracio/edge/releases.

**Comment by bravomikekilo** [comment]
how about publish a new package to npm?

**Comment by agracio** [comment]
It is published as `edge-js`

**Comment by agracio** [comment]
Release 6.6.2 resolves `StackOverflowException` on all platforms. https://github.com/agracio/edge/releases.

**Comment by agracio** [comment]
Release 6.6.4 adds support for .Net Core 1.0.1 and above. https://github.com/tjanczuk/edge/issues/544, https://github.com/tjanczuk/edge/issues/529

**Comment by agracio** [comment]
If anyone is still looking to use this fork, it was moved to https://github.com/agracio/edge-js.
