### ISSUE TITLE
EdgeJS does not support user impersonation

### ISSUE THREAD

**Issue by GJaura** [tjanczuk/edge#542]
In sql server if I have to run the stored procedure by impersonating another user then we use following command
exec as login='username'; exec StoredProcedureName

But when we try to execute this whole statement then it treats all the strings after exec command as a stored procedure which obviously does not exists.

Is there any workaround for this?

**Comment by agracio** [comment]
`edge-sql` package can only executed simple stored proc call. You need to use `edge` package instead with an appropriate c# method call.
