### ISSUE TITLE
Illegal characters in path

### ISSUE THREAD

**Issue by mind84** [tjanczuk/edge#554]
Hi,
first of all, thanks for your work.

We work on Windows Server 2012 R2 with Node.js -v 6.10.2 x64, edge -v 4.5.0, Microsoft .NET Framework 4.7 SDK and Windows 10 SDK installed.

To perform some tasks, we have to work with external (and obsolete) .dll library with an ActiveX interface (x86) and call it from our node.js code. 
Actually, the vendor can't provide a new version of this .dll and so we had to manipulate it in order to use it on .NET Framework (COM --> .NET, to clarify).

So, we create a wrapper around this library with tlbImp (works fine) and update system registry so as to allow our 64 bit sistem to "see" the x86 wrapper.

Our code has "edge-basic" syntax and looks like:

```
var edge = require("edge");
var path = require("path");
var util = require("util");

var sign = edge.func(function() {/*

		#r "System.Windows.Forms.dll"
		#r "C:/Program Files (x86)/Vendor/interop.ext.dll"   //this is our wrapper
		
		using System;
        using System.Threading.Tasks;
		using System.Windows.Forms;
		using ext; 
		
        public class Startup
        {
            public async Task<object> Invoke(object input)
            {
				extCore extcore = new extCore();//....error?
				
				//no matter what we write here (syntax apart, obviously), the error "is" in above line
				string msg = "ok";   
				return msg;//we must return something
            }
        }
	*/
});

sign('JavaScript', function(error, result) {
    if (error) {
		console.info(util.inspect(error, showHidden=true, depth=99, colorize=false));
		return;
	}
	else console.info(result + ", Done it" );
});
```

The script fails and we get an "Illegal characters in path" error:

{ Error: Illegal characters in path
    at Error (native)
    at <anonymous>:1:55
    at Object.<anonymous> (C:\COMP\Company\myScript.js:30:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
  Message: 'Illegal characters in path.',
  ParamName: null,
  Data: {},
  InnerException: null,
  TargetSite: {},
  StackTrace: '  
  in System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
  in System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
  in System.IO.FileInfo.Init(String fileName, Boolean checkHost)
  in System.ComponentModel.Design.RuntimeLicenseContext.GetSavedLicenseKey(Type type, Assembly resourceAssembly)
  in System.ComponentModel.LicenseManager.LicenseInteropHelper.GetCurrentContextInfo(Int32& fDesignTime, IntPtr& bstrKey, RuntimeTypeHandle rth)
  in Startup.<Invoke>d__0.MoveNext()',
  HelpLink: null,
  Source: 'mscorlib',
  HResult: -2147024809,
  message: 'Illegal characters in path.',
  name: 'System.ArgumentException' }

 We try several fix approach:
 
  - different syntax of node script, i.e. write `edge.func({source: function(){/*C# code*/}, reference:['....','...']})`
  - try to reference dll with full path, i.e. "C:/Windows/Microsoft.NET/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll"
  - try to write path usign "/" and "\\" 
  - try to reference dll with no path
  - create wrapper using tlbImp with /unsafe parameter
  - combine the whole things above in every possible scenario
  
  but we can't figure out what is the problem.
  
  Any help would be very very very appreciated
  
  Thanks

**Comment by AleCaste** [comment]
Hello @mind84 , I am facing the very same issue. Did you manage to get this working?

**Comment by mind84** [comment]
Hi @AleCaste, since we have not received any support for this we have followed another way.  Vendor provided us a CLI solution, so we could call the dll indirectly using node child process. probably for performance this is not the best practice, but for our needs it was a good compromise

**Comment by justinTM** [comment]
Bump! @tjanczuk

**Comment by Yaroslav-Kuznetsov** [comment]
Hi,
Is there any update on this issue? `RuntimeLicenseContext` fails as it checks `Assembly.EscapedCodeBase` of each loaded assembly (`AppDomain.CurrentDomain.GetAssemblies`). This code does not work correctly for the **edge_nativeclr.node** assembly:
file:///?/C:/some_folder/node_modules/edge-js/lib/native/win32/x64/12.13.0/edge_nativeclr.node

What's special about this node assembly and why the returned URI is incorrect?

**Comment by justinTM** [comment]
there’s a question mark in the path

**Comment by jprakashgithub** [comment]
does anyone have any updates on this? I'm facing the same issue....
