### ISSUE TITLE
Nuget Edge.js (7.10.1) on OSX .Net Core  results in Error CS0246: The type or namespace name 'EdgeJs' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by gofreddo** [tjanczuk/edge#563]
macOS Sierra Version 10.12.5
Nuget install Edge.js (7.10.1) 
Microsoft.NETCore.App 1.1.1
Node v7.7.3

Build results in Error CS0246: The type or namespace name 'EdgeJs' could not be found (are you missing a using directive or an assembly reference?)

All the code is below.

using System;
using EdgeJs;
namespace ConsoleTest
{
    
    internal class Program
    {
        
        private static void Main()
        {

            var func = EdgeJs.Edge.Func(@"
                return function (data, callback) {
                    callback(null, 'Hello, ' + data);
                }
            ");

		}
    }
}

**Comment by thedumbtechguy** [comment]
Similar issue in NetStandard 2.0 library

**Comment by LucidObscurity** [comment]
same issue netcore2.0 & 2.1
