### ISSUE TITLE
Unable to load DLL 'node.dll'

### ISSUE THREAD

**Issue by paulomunoz** [tjanczuk/edge#565]
Hi there, I created a very simple demo application, and when I run it I get this error:

```
An unhandled exception of type 'System.DllNotFoundException' occurred in EdgeJs.dll

Additional information: Unable to load DLL 'node.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

This is the whole application code:
```
using System;
using System.Threading.Tasks;
using EdgeJs;

class Program
{
    public static async Task Start()
    {
        var func = Edge.Func(@"
            return function (data, callback) {
                callback(null, 'Node.js welcomes ' + data);
            }
        ");

        Console.WriteLine(await func(".NET"));
    }

    static void Main(string[] args)
    {
        Start().Wait();
    }
}
```

I found a message from glennblock in here: https://github.com/tjanczuk/edge/issues/17 where he mentions the same error, and the reply was just `@glennblock This is unfortunate. I suppose I will call the module Edge.js`. I don't really understand this answer and I'm stuck with this right now. Can any of you guys could shed some light?

I'm running this on a Windows machine.

**Comment by paulomunoz** [comment]
Whenever I don't get this error, I get the following one.
![pasted image at 2017_06_14 05_46 pm](https://user-images.githubusercontent.com/1202698/27144592-61bfeed6-512a-11e7-998e-fc40532651cb.png)

**Comment by paulomunoz** [comment]
Can I please get some help with this? I haven't been able to resolve it yet, some help would be VEEERY appreciated. Thank you.

**Comment by agracio** [comment]
A quick search brings back this issue: https://github.com/tjanczuk/edge/issues/503, are you missing  dlls in your app /bin folder?

**Comment by paulomunoz** [comment]
@agracio Thank you for your answer, copying the folder "edge" to the bin folder did solve problem number 1.
Now for problem number 2 (AccessViolationException) I solved it by downgrading to EdgeJS v6. I wonder if there is still a way to get it working with version 7, to be honest I haven't read the changelogs so I don't know what I'm missing by downgrading it, but everything appears to be working fine this way.

Thank you for shedding some light!
