### ISSUE TITLE
Error: The edge module has not been pre-compiled for node.js version v8.1.1.

### ISSUE THREAD

**Issue by sz30313484** [tjanczuk/edge#567]
npm install edge

> edge@7.10.1 install D:\demo\project\Web\node4\app\node_modules\edge
> node tools/install.js
***************************************
Error: The edge module has not been pre-compiled for node.js version v8.1.1. You must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge for building instructions.
    at determineVersion (D:\demo\project\Web\node4\app\node_modules\edge\lib\edge.js:20:11)
    at Object.<anonymous> (D:\demo\project\Web\node4\app\node_modules\edge\lib\edge.js:32:102)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\demo\project\Web\node4\app\node_modules\edge\tools\checkplatform.js:2:2)
***************************************
Success: platform check for edge.js: node.js ia32 v8.1.1
+ edge@7.10.1

**Comment by sz30313484** [comment]
install node-v6.11.0-x64.msi!Resolved!

**Comment by borgold** [comment]
This is not a fix to go back on the Node.js version! I received the same error while installing dependent module for Node version 9.2.

Please provide instructions on how to precompile edge for any version.

**Comment by xulayen** [comment]
i was success,but a month later ,tips me The edge module has not been pre-compiled for node.js version v8.9.4

**Comment by agracio** [comment]
You can use https://github.com/agracio/edge-js that has been precompiled for version 8.x and 9.x.

**Comment by Tahertito** [comment]
> You can use https://github.com/agracio/edge-js that has been precompiled for version 8.x and 9.x.

plz plz, now in 2020 it's not working either.
i'v read all ur answers in another problems such this but still didn't know to precompile this library. 
plz if u can make a video it would be much clearer than writing i'll be thankful for u

**Comment by gbrcmg** [comment]
Same problem here..

Application has thrown an uncaught exception and is terminated:
Error: The edge module has not been pre-compiled for node.js version v12.18.1. You must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge for building instructions.

**Comment by agracio** [comment]
This has been discussed many times already, you should use https://github.com/agracio/edge-js that is precompiled for all modern versions of NodeJs. Building instruction are very clear in the README so its rather simple to compile your own version.
