### ISSUE TITLE
Where does the error “Invalid access to memory location” come from? 

### ISSUE THREAD

**Issue by TheNeis** [tjanczuk/edge#568]
I tried to use electron together with edge.js and ran into the issue "Invalid access to memory location". Searching on the internet showed, that this is a common issue and can't be solved, so i shoud just use the package electron-edge. Fine, but nobody could came up with a usefull explanation of where the exception comes from or why it is thrown. I solved my problem in another way and everything works fine now, but can anyone explain in detail why this exception is thrown?

Thank you in advance

**Comment by lilinghui** [comment]
the edge-7.10.1 only can invoke in default domain,if you create another Domain , you must fix some code

clrfunc.cpp 
#pragma managed(push, off)
static Nan::Persistent<v8::Function> proxyFactory;
static Nan::Persistent<v8::Function> proxyFunction;
#pragma managed(push, pop)

nodejsfuncinvokecontext.cpp
#pragma managed(push, off)
static Nan::Persistent<v8::Function> callbackFactory;
static Nan::Persistent<v8::Function> callbackFunction;
#pragma managed(push, pop)

then complie the edje code, it work's fine for me.

**Comment by TheNeis** [comment]
Thank you for the answer, this brought me a lot closer to understand the problem! I need to write a little report about my work and i have to explain, why i decided to move away from writing everything together in one application to an internal client-server-structure. This was my workaround to the problem, because i couldn't get electron-edge to run stable...

So let my try to explain how i now understood the problem:
Electron creates an own application domain to share some ressources with it's processes, because electron forks a new process for each new Browserwindow. If i now try to use edge from one of these processes, the exception is thrown because edge can't access the memory to load the managed code from other domains than the default domain.

Is this right? If not, can you please explain the problem to me a little more detailed?

**Comment by lilinghui** [comment]
yes, your are right.
