### ISSUE TITLE
CLR to Node.js works in w\ Edge.js ver 6.5.1 but fails after updating to 7.10.1

### ISSUE THREAD

**Issue by JasonWollamAT** [tjanczuk/edge#569]
Have the following CLR method that calls the following Node.js that works in Edge.js 6.5.1 but fails with invalid memory error with 7.10.1.

The error message is. "System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'"

CLR
        private string Seed(RootSeedOptions seedData)
        {
            var func = Edge.Func($@"return require('{_pathToFrameworkRequirements}')");
            var invoke = func.Invoke(seedData);
            var response = (dynamic)invoke.Result;

            invoke.Dispose();

            return response.ToString();
        }

Node.js
var BrozartHandler = require("./brozart-init.js").BrozartHandler;

module.exports = function (data, callback) {
    return BrozartHandler.SeedEngagement({
        directory: data.Directory,
        keyMap: data.KeyMap,
        options : {
            logger: data.Options.Logging,
            noseed: data.Options.NoSeed,
            username: data.Options.User,
            env: data.Options.Environment,
            protocol: data.Options.Protocol,
            }
        }, data.Options.PathToBrozart).then(function (data) {
            return callback(null, data[0]["0"].commands["0"].value.id);
        },
    "");
};

**Comment by lilinghui** [comment]
the edge-7.10.1 only can invoke in default domain,if you create another Domain , you must fix some code
clrfunc.cpp
#pragma managed(push, off)
static Nan::Persistentv8::Function proxyFactory;
static Nan::Persistentv8::Function proxyFunction;
#pragma managed(push, pop)
nodejsfuncinvokecontext.cpp
#pragma managed(push, off)
static Nan::Persistentv8::Function callbackFactory;
static Nan::Persistentv8::Function callbackFunction;
#pragma managed(push, pop)
then complie the edje code, it work's fine for me.
