### ISSUE TITLE
Edge problems when running unit tests.

### ISSUE THREAD

**Issue by ghost** [tjanczuk/edge#571]
Hi!

I'm running Node.js into C#, and I'm having some problems when I try to unit test it.

**First problem: Access violation using version 7.10.1.**
I really do not understand this error, just happens when I try to unit test that version.
Solved with downgrade to version 6.5.1.

**Second problem: Unit test pass but still running on version 6.5.1.**
When I downgrade the version, Edge works fine, but after I run some unit test, the process get stuck for some time, even after the test have passed, and then ends.

I don't know why this is happen too, hope you guys could help me.

**Steps to get the errors:**
1 - Create a Unit Test project on Visual Studio.
2 - Create a unit test just like that and run it:
```
[TestMethod]
public void MyTestMethod()
{
    var func = Edge.Func(@"
        return function (data, callback) {
            callback(null, 'Node.js welcomes ' + data);
        }
    ");

    Assert.AreEqual(func(".NET").Result, "Node.js welcomes .NET");
}
```

If you are using version 7.10.1 you'll get the first error.
And if you are using version 6.5.1 you'll get the second error (this is an error?).

P.S.: I'm running .NET 4.6.1 on Visual Studio 2015 Enterprise (Same problems with VS2017 Enterprise).

**Comment by me0262** [comment]
Confirmed that downgrading to 6.5.1 works.
My code does not hang.
`[Test]
        //[Ignore("Freezes testing with error: ClrFunc.Initialize: Attempted to r/w to protected memory.")]
        public async System.Threading.Tasks.Task rjf_09_file_data_is_received_by_js_as_object()
        {
            // testing this because this was a thing...
            var jsCheckForObject = Edge.Func(@"
                return function(payload, callback) {
                    var error = null;   // null or undefined if no error.
                    var is_array = Array.isArray(payload);
                    callback(error, is_array);
                }
            ");

            returnObject = General.Preferences.ReadJSONFile("json_reader_test_data/standard.json");
            bool isArray = await jsCheckForObject(returnObject);
            // IF THIS IS TRUE THAT MEANS YOUR DESERIALIZER IS NOT RETURNING CORRECT RESULTS.
            // THIS SHOULD BE AN OBJECT, NOT AN ARRAY. TRY ANOTHER ONE, OR STICK WITH Windy.Json.
            Assert.That(isArray, Is.False);
        }`
