### ISSUE TITLE
MSBuild error when installing edge, conflicts with .Net Core

### ISSUE THREAD

**Issue by nicholas-campagna** [tjanczuk/edge#572]
I was trying to install the edge package but I kept getting the following error:

> 
> > edge-cs@1.2.1 install C:\<mypath>\node_modules\edge-cs
> > node tools/install.js
> 
> MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
> Microsoft (R) Build Engine version 15.1.1012.6693
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
> 
> > edge@7.10.1 install C:\<mypath>\node_modules\edge
> > node tools/install.js
> 
> MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
> Microsoft (R) Build Engine version 15.1.1012.6693
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
> Success: platform check for edge.js: node.js x64 v5.7.0
> otto@1.0.0 C:\<mypath>
> `-- edge@6.5.1
>   +-- edge-cs@1.2.1
>   `-- nan@2.6.2

I was confused by this because the install worked fine on several of my coworkers machines.  After some troubleshooting I determined that the key difference was that the error was occurring on machines that had .Net Core installed on them.  We uninstalled that package and edge now installs successfully, but I hope you can get that conflict resolved soon so that we can start using some of the new stuff from the .Net Core library.

**Comment by agracio** [comment]
Edge does not support newer versions of .Net Core that use .csproj files instead of project.json.
You can try 'edge-js' npm instead.

**Comment by floydpink** [comment]
Thank you @agracio - `npm install edge-js` worked with the current version of .NET Core on macOS High Sierra. 👍
