### ISSUE TITLE
AccessViolationException occured in calling DLL function

### ISSUE THREAD

**Issue by kesokeso621** [tjanczuk/edge#575]
I have an external DLL, XXXLib.dll, provided by a company.
The DLL is communicate with a server through Ethernet.
I already have C# application with the DLL.
The application works well with the DLL. 
Now, I'm trying to transplant the application to Node.js web application.

When NumberOfData in DataStructure is under 4,
the following code works well.
However, NumberOfData in DataStructure is over 5,
access violation exception is occured in the read function.

In addition, NumberOfData in DataStructure is over 20,
access violation exception is not occured but the read function process is skipped or node.exe assert failure.
The message of the failure is following.

Expression:[mscorlib resoursive resource lookup bug] 
Description:Indinite recursion during resource lookup within mscorlib.
Resource name:Arg_AccessViolationException.

Does edge have some limitations of return array value?
Or more better way to access DLL functions?

**js**
```

var edge = require('edge');

var com = edge.func({	
	source: "mxc.cs",
	references: ['XXXLib.dll']
	//Load External DLL provided by a company.
	//Communicate with a server.
});

var DataStructure={
	DeviceNames:"D0",
	NumberOfData:10//1~4->OK, over5->Exception
}

var mxc=com(1, true);
console.log(mxc.load(null, true));
var read=mxc.read(DataStructure, true);
console.log(read.ReturnCode);
console.log(read.Val);
```

**mxc.cs**

```
using System;
using System.ComponentModel;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using System.Linq;
using System.Collections;
using System.Collections.Generic;


public class Startup
{
	public static XXXLib.XXXTypeClass lpcom;	
	public async Task<object> Invoke(int Num)
	{
		var com = new Com(Num);
		return new {
			load = (Func<object,Task<object>>)(
				async (dynamic i) => 
				{ 						
					lpcom = new XXXLib.XXXTypeClass();
					lpcom.Num=Num;
					return new{ReturnCode=0};
				}
			),
			read = (Func<object,Task<object>>)(
				async (dynamic rdev) => 
				{ 
					int res;
					int[] arrDeviceValue=new int[rdev.NumberOfData];
					
					res = lpcom.Read( rdev.DeviceNames,
								     rdev.NumberOfData,
								     out arrDeviceValue[0]);
					return new{ ReturnCode=res,Val=arrDeviceValue};
				}
			)
		};
	}	
}

public class Com
{
	public int StNum{ get; private set; }		
	public Com(int Num)
	{
		this.StNum = Num;		
	}
}


```

**Comment by agracio** [comment]
Result marshalling from C# to V8 formats might be the issue. Edge is fine with converting native .Net objects to V8 format, but if your dll returns some kind of unconventional object it will struggle.
Have you tried converting results to some kind of readable format on C# side first and then returning them?

**Comment by kesokeso621** [comment]
Thank you. I'll try converting results to another formats.
In addition, I'll try  wrapping the dll and calling from the wrapped one.

**Comment by agracio** [comment]
There is also another possibility, quick google search shows that in some cases dlls will behave incorrectly depending on locale and switching to US-English resolves all issues.
