### ISSUE TITLE
Access Violation from web.API when using async call

### ISSUE THREAD

**Issue by pfigueiredo** [tjanczuk/edge#578]
using a none async call it works fine:

`[Route("api/Edge/Test"), HttpGet]
        public string Test() {

            var func = Edge.Func(@"
                return function (data, callback) {
                    callback(null, 'Node.js welcomes ' + data);
                }
            ");

            var ret = func(".Net") as Task<object>;

            ret.Wait();
            return ret.Result as string;
        }`

but when using an async call I get an Access Violation and the IIS process terminates

`[Route("api/Edge/Test"), HttpGet]
        public async string Test() {

            var func = Edge.Func(@"
                return function (data, callback) {
                    callback(null, 'Node.js welcomes ' + data);
                }
            ");

            return await func(".Net") as string;
        }`

**Comment by pfigueiredo** [comment]
Well actually it always give's back an AccessViolation... I was able to run it one time in debug mode in the first form (with ret.Wait()).

Then I thinked that it would run in debug (F5 in VS) and not (Ctrl+F5).

I'm using VS 2017 targeting .net framework 4.5 and Edge.js 7.10.1

**Comment by dmpratt** [comment]
I am also experiencing this issue with an existing project.  It works fine under Edge 6.5.1, but when I upgrade to anything later my application crashes immediately upon executing the Edge.Func.  System.AccessViolationException.  No native modules, actually tried with just a very basic return like the hello world.  I am running this async within a web.api call and I am coding my initial function js as a node module.  Also, if it helps, targeting .Net 4.5.2.  Thanks!

**Comment by SpicySyntax** [comment]
Any Update on this? I am having the same issue
