### ISSUE TITLE
throw System.AccessViolationException from edge.js 8.2.1

### ISSUE THREAD

**Issue by simpleway2016** [tjanczuk/edge#581]
if i use edge.js in wpf application，it works.
but i use edge.js in UnitTest project，it throw System.AccessViolationException

**Comment by mmanela** [comment]
I have the same issue. Was trying to use it in my integration unit tests and I get this exception.

**Comment by OndraM-Kentico** [comment]
I'm experiencing the same exception with test project (NUnit) and edge.js v8.2.1:
`System.AccessViolationException was unhandled
Message: An unhandled exception of type 'System.AccessViolationException' occurred in edge_nativeclr.node
Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
`
When the code in run console app, no exception occurs. I'd very appreciate if it was fixed as the issue makes edge.js completely unusable.

**Comment by agracio** [comment]
The fix requires https://github.com/tjanczuk/edge/pull/573 pull request to be merged. There is some more discussion on this thread: https://github.com/tjanczuk/edge/issues/586

**Comment by zenglo** [comment]
I also encountered this problem, it encountered in the asp.net mvc, I indirectly through a console program calls the edge, to circumvent the AccessViolationException, I wrote a demo, if you want to know, can see EdgeJsDemo. Of course, the hope is that author can fundamentally solve the problem.

**Comment by agracio** [comment]
The fix requires https://github.com/tjanczuk/edge/pull/573, I have merged it to my fork at https://github.com/agracio/edge-js, take a look at https://github.com/tjanczuk/edge/issues/586 for reference.

**Comment by OndraM-Kentico** [comment]
Unfortunately, in my NUnit tests project, I haven't managed to make it work with pre-compiled binaries. @agracio , could you provide NuGet package, please?

**Comment by agracio** [comment]
I know its been over a month, but I have finally published NuGet packages for https://github.com/agracio/edge-js fork. Take a look at release page for details: https://github.com/agracio/edge-js/releases

**Comment by fforjan** [comment]
@agracio  is your fork become a official release ? because I see more update on your branch than  here

**Comment by agracio** [comment]
It is not official, however @tjanczuk is no longer active on this project and did not provide any updates about its future. I have not attempted to contact him myself, but I understand that noone had any luck. Since he is active on other projects it is not clear why he ignores this one. 
Initially I forked this repo to address a blocking issue with some of our apps, but now it became one of my main home projects.
Incidentally there is some discussion about this particular issue as the fix does not appear to work for all users, you might want to take a look: https://github.com/agracio/edge-js/issues/17

**Comment by SpicySyntax** [comment]
@agracio I am still having this exact issue when running NUnit tests. Has there been any progress made in this effort?

**Comment by agracio** [comment]
This PR is merged to https://github.com/agracio/edge-js
