### ISSUE TITLE
Edge Compile Failure on Mac OS 10.12.6

### ISSUE THREAD

**Issue by MichaelWhite63** [tjanczuk/edge#582]
I have installed Mono and am able to run a simple HelloWorld.cs at the command line so I know my install of mono is working.

I used the universal installer for mono that is on the download page of the http://www.mono-project.com/download/ site.  Note: the 5.2.0 version has just been released as the stable version but I have already downloaded am using the 5.0.1 version.  I did try the 5.2.0 version and it has the same problem that I describe below.

$ mono -V
$ Mono JIT compiler version 5.0.1.1 (2017-02/5077205 Thu May 18 16:11:37 EDT 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-master/8b1520c)
	GC:            sgen (concurrent by default)

I have my environment variable set for PKG_CONFIG_PATH
$ pkg-config --variable pc_path pkg-config
$ /usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12

When I execute npm install edge it won't install cleanly.  

> edge@7.10.1 install /Users/michaelwhite/Documents/xcodeDevelopment/Node/meanjs/node_modules/edge
> node tools/install.js

  CXX(target) Release/obj.target/edge_nativeclr/src/mono/clractioncontext.o
./Release/.deps/Release/obj.target/edge_nativeclr/src/mono/clractioncontext.o.d.raw Stats {
  dev: 16777217,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 74589170,
  size: 2558,
  blocks: 8,
  atimeMs: 1502796295000,
  mtimeMs: 1502796295000,
  ctimeMs: 1502796295000,
  birthtimeMs: 1502796295000,
  atime: 2017-08-15T11:24:55.000Z,
  mtime: 2017-08-15T11:24:55.000Z,
  ctime: 2017-08-15T11:24:55.000Z,
  birthtime: 2017-08-15T11:24:55.000Z }
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/clrfunc.o
../src/mono/clrfunc.cpp:365:13: warning: 'SetPrototype' is deprecated [-Wdeprecated-declarations]
    result->SetPrototype(v8::Exception::Error(message));
            ^
The above statements print for each .o it is trying to build.

I brought up the Node application and execution got past the var edge = require('edge'); statement so it is finding the 'bad' version of edge.  The code stack dumps when I call edge.func().  I expect the reason for this is that the build of edge is not correct.
I am using Node version 8.3.0, which should not influence the build of edge.  

Has anyone seen this before?

**Comment by yamachu** [comment]
I also can't build Edge.js with mono 5.x .
You should mono 4.8.x .

When install edge.js, try below command
`PKG_CONFIG_PATH=/Library/Frameworks/Mono.framework/Versions/4.8.1/lib/pkgconfig npm i edge`

**Comment by MichaelWhite63** [comment]
I uninstalled mono 5.x then installed 4.8.1.  I got 4.8.1 from here https://download.mono-project.com/archive/4.8.1/macos-10-universal/

I used your command to start the build.  The following is message received:

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
make: *** [lib/bootstrap/project.lock.json] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/michaelwhite/Documents/xcodeDevelopment/Node/researchPortal/node_modules/edge
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN eslint-config-airbnb@6.0.2 requires a peer of eslint@^2.2.0 but none was installed.
npm WARN eslint-config-airbnb@6.0.2 requires a peer of eslint-plugin-react@^4.0.0 but none was installed.

**Comment by agracio** [comment]
Looks like an error for .NET Core build, not Mono. Make sure your system recognises Mono install.

**Comment by MichaelWhite63** [comment]
I must be missing something.  What is the .NET Core build?

I can build and execute a HelloWorld.cs.  This makes me expect that Mono is installed correctly.

Michaels-iMac:Node michaelwhite$ mcs HellowWorld.cs
Michaels-iMac:Node michaelwhite$ mono HellowWorld.exe
Hello, World!
Michaels-iMac:Node michaelwhite

Also, I get the following when I check the version of Mono

Michaels-iMac:researchPortal michaelwhite$ mono -V
Mono JIT compiler version 4.8.1 (mono-4.8.0-branch/22a39d7 Fri Apr  7 12:00:08 EDT 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-master/8b1520c)
	GC:            sgen
