### ISSUE TITLE
The specified module could not be found edge_nativeclr.node

### ISSUE THREAD

**Issue by fabriciolelis** [tjanczuk/edge#583]
I have this problem when I use edge.
**Windows 8.1 and Windows 7**
<img width="362" alt="1503344465234-image" src="https://user-images.githubusercontent.com/8815495/29587280-dd627814-8763-11e7-96d8-3c6e00f4055a.png">

**Comment by KaiWalter** [comment]
If have the same problem running [Azure Functions CLI in a Windows Server container with .NET Framework 4.6.2](https://github.com/Azure/azure-functions-cli/issues/163)
I have VC2013 x86 redist installed - are there other dependencies on Windows when starting from a bare installation?

**Comment by agracio** [comment]
When does it happen, during `npm install edge`?

**Comment by KaiWalter** [comment]
@agracio - the edge runtime components seem to be delivered together with the Azure Functions runtime.  The problem happens when the Azure Functions runtime tries to call egde the first time I guess.
But thanks for the hint, I will try to install edge explicitly.

**Comment by dreamdevil00** [comment]
Have you installed ```Visual C++ Redistributable for Visual Studio 2015```? This package needs 2015 or higher. Hope this will help you.

**Comment by SelvarajKaruppusamy** [comment]
I was debugging a very similar problem for a while, then this thread made me check VC++ installation. VC++ installation was missed due to a bug in the installer. Once I installed VC++, the app started to work fine.

I guess this issue can be closed. @fabriciolelis your thoughts.

**Comment by zwdgit** [comment]
> Have you installed `Visual C++ Redistributable for Visual Studio 2015`? This package needs 2015 or higher. Hope this will help you.

Do I need to install Visual C ++ Redistributable on the customer's PC when it is delivered to the customer?

**Comment by dreamdevil00** [comment]
@zwdgit Yes, or install [windows-build-tools](https://www.npmjs.com/package/windows-build-tools)

**Comment by Allyday** [comment]
If you still encounter the problem, consider going to Control Panel > System and Security > Windows Update > Run the updates & restart your computer when asked.

[Source](https://stackoverflow.com/questions/52586614/error-a-certificate-chain-processed-but-terminated-in-a-root-error-net-framewo)

**Comment by viltbalint** [comment]
I've the same problem, even if I install the Visual C++ Redistributable. Do you have any suggestion to solve this issue?
