### ISSUE TITLE
Can't compile for node 8.3.0 on Windows 10

### ISSUE THREAD

**Issue by stockviz** [tjanczuk/edge#584]
Followed instructions to install node-gyp under windows build tools (npm install --global --production windows-build-tools) and ran the build.bat file in the tools sub directory (build.bat release 8.3.0). Landed with the following error:

C:\Users\shyam\.node-gyp\8.3.0\include\node\v8.h(4081): error C2664: 'std::pair<std::unique_ptr<const uint8_t[],std::default_delete<_Ty>>,std::size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::size_t> &&)': cannot convert argument 1 from 'nullptr' to 'nullptr &&' [C:\Users\shyam\Documents\Visual Studio 2017\Projects\StockVizNT\WebRT\node_modules\edge\build\edge_nativeclr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\common\edge.cpp)
  C:\Users\shyam\.node-gyp\8.3.0\include\node\v8.h(4081): note: nullptr can only be converted to pointer or handle types (compiling source file ..\src\common\edge.cpp)

**Comment by smx-smx** [comment]
Have the same problem, and it seems to be related to MSVC because it builds fine with GCC. I found (and tried out) this commit (https://github.com/janeasystems/node/commit/27fb4bb0ed8620f0a01c2cffe62b53acaaffd6dc), but it doesn't completely fix the problem in this case.

**Comment by agracio** [comment]
Changing `--msvc_version` from 2015 to 2017 in `tools/build.bat` fixes the problem for me. Compiling v8.2.1 works using msvc_version 2015.

**Comment by smx-smx** [comment]
I have msvc 2017 too but it was failing for some reason.
I'm not too sure why, but when i issued a gyp rebuild again in the edge folder it went through.

**Comment by agracio** [comment]
I was referring to setting it to 2017 in `tools/build.bat` and then building using that command line `build.bat release 8.3.0` but looks like you solved it anyway :)

**Comment by smx-smx** [comment]
Forgot to mention that i'm building it for Electron 1.8.1 / Node 8.2.1, so there might be some differences but i was initially having the same error.

**Comment by agracio** [comment]
I've done that already: https://github.com/agracio/electron-edge-js. Look at `tools/build.bat`.The problem with 1.8.1 is exactly the same as with Node 8.3+.
