### ISSUE TITLE
mssql windows authentication using edge.js on Linux

### ISSUE THREAD

**Issue by javidaslan** [tjanczuk/edge#585]
Hi,

I am developing API using Node.js which connects to MS SQL. using windows authentication and on windows platform everything is working very well. But API will be deployed to Linux server and I am not sure if edge does have the feature to perform windows authentication on linux platform. My question is that can I do it on Linux server using edge.js or edge-sql?

**Comment by agracio** [comment]
Try creating a simple .NET console app to see if it works on Linux. If it does you will be able to do the same with edge. This is assuming that your Linux environment is integrated with Windows Active Directory.
Although I do not have experience with windows authentication from Linux but sounds like it could get tricky.
You also have to consider the .NET library that you going to use on your Linux server. Mono 5.x is proving to be problematic with edge, you should consider Mono 4.8.x. On the other hand edge does not support latest .Net Core.
You can try `edge-js` fork that does offer .NET Core support.
