### ISSUE TITLE
New npm release for node v8

### ISSUE THREAD

**Issue by cloudkite** [tjanczuk/edge#587]
Hi @tjanczuk firstly thanks for this awesome lib 😍  ❤️ 

Is there any chance of getting the latest published to npm? I think this would resolve alot of issues
https://github.com/tjanczuk/edge/issues/584
https://github.com/tjanczuk/edge/issues/541
https://github.com/tjanczuk/edge/issues/580
https://github.com/tjanczuk/edge/issues/574

Thanks

**Comment by atrauzzi** [comment]
Yeah, would be great to see this on NPM so that I can try it out!

**Comment by codepunkt** [comment]
@tjanczuk please release 8.2.1 on npm.

**Comment by javahaxxor** [comment]
Any news on a version that supports node 7.6 or higher ?

**Comment by agracio** [comment]
Edge.js already includes 7.10.0 in the latest npm release

**Comment by fforjan** [comment]
@tjanczuk  do you have any plan to publish the v8.2.1 release to npm ? 
if not, how could we consume it ?

**Comment by codepunkt** [comment]
Edge.js should probably support the latest LTS each year.
8.9.1 LTS for 2017.
