### ISSUE TITLE
Error installing on Mac OSX

### ISSUE THREAD

**Issue by vgaltes** [tjanczuk/edge#593]
Hi,

I'm trying to follow the instructions to install NPM on a Mac. I've got .Net core installed, I've updated pkg-config. My version of node is 8.1.3 and the version of .Net core is 1.0.4.

When I run npm install edge I've got the following error:
```
> edge-cs@1.2.1 install /Users/vgaltes/Tests/edge/node_modules/edge-cs
> node tools/install.js

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

> edge@7.10.1 install /Users/vgaltes/Tests/edge/node_modules/edge
> node tools/install.js

internal/child_process.js:317
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:317:11)
    at exports.spawn (child_process.js:491:9)
    at Object.<anonymous> (/Users/vgaltes/Tests/edge/node_modules/edge/tools/install.js:81:2)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
npm WARN edge-test@1.0.0 No description
npm WARN edge-test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! edge@7.10.1 install: `node tools/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the edge@7.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

What I'm doing wrong?

Thanks,
Vicenç

**Comment by agracio** [comment]
Are you using .NET Core or Mono?

**Comment by vgaltes** [comment]
I'm using .NET Core.

**Comment by agracio** [comment]
`edge` does not support modern .NET Core implementation based on .csproj rather than older project.json. You can try `edge-js` for instead.

**Comment by MichaelPaulukonis** [comment]
I'm getting the same error when attempting to install the packages for the VS Code extension [JS Refactor](https://github.com/cmstead/js-refactor)

It looks like next.js [had the same issue](https://github.com/zeit/next.js/issues/2228) - but their workaround (adopted for path changes) did not work for me.

A [solution on StackOverflow](https://stackoverflow.com/questions/25258361/npm-wont-install-any-package-on-mac-new-clean-build-eacces-other-errors) also failed to solve.

**Comment by agracio** [comment]
@MichaelPaulukonis https://github.com/cmstead/js-refactor extension is not in any way related to `edge`, it does not use it as one of the dependencies so any error you getting when trying to install it is not really relevant to `edge`. I would suggest opening an issue with the relevant repo.
