### ISSUE TITLE
Error: Could not load file or assembly 'ClassLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by kutuev93** [tjanczuk/edge#595]
Hello,

I have an issue which related to an additional dependency for executable dll file.
Env: Linux, .net core 1.0.0

My executable dll has the following code:

```
using ClassLibrary;
using System.Threading.Tasks;

namespace NetCoreLibrary
{
    public class MyMath
    {
        public async Task<object> GetResult(object numberObj)
        {
            if (numberObj is int)
            {
                var math = new Science();
                var number = (int) numberObj;

                var result = math.CalculateValue(number);

                return result;
            }

            return numberObj.ToString();
        }
    }

}
```

I use it as:

```
var edge = require('edge');
var path = require('path');

var clrMethod = edge.func({
	assemblyFile: 'NetCoreLibrary.dll',
	typeName: 'NetCoreLibrary.MyMath',
	methodName: 'GetResult',
});

clrMethod(234, function (error, result) {
	if (error) {
		console.log(error);
		throw error
	};
})
```

But here I have the following error: 

> Error: Could not load file or assembly 'ClassLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

NetCoreLibrary.dll and ClassLibrary.dll lie in the same folder in project root.

I tried to use `references: [('ClassLibrary.dll')] ` and` references: [ __dirname + '/ClassLibrary.dll'], `but the same result.

I believe it's a common issue and there is just my mistake at something 

Thank you in advance

**Comment by kutuev93** [comment]
Ok, the same issue if I create .js file with C# code which refers to this dll:

var edge = require('edge');
var path = require('path');

var hello = edge.func({
    references: [ path.join(__dirname, 'ClassLibrary.dll')],
	source: function () {/*
        using ClassLibrary;
		using System.Threading.Tasks;

		public class Startup
		{
			public async Task<object> Invoke(object numberObj)
			{
				if (numberObj is int)
				{
					var math = new Science();
					var number = (int) numberObj;

					var result = math.CalculateValue(number);

					return result;
				}

				return numberObj.ToString();
			}
    }
    */}
});

hello(5675, function (error, result) {
    if (error) throw error;
    console.log(result);
});

**Comment by p-gebhard** [comment]
I have exactly the same issue.

Did anybody resolve the issue?

**Comment by p-gebhard** [comment]
I was able to resolve the problem using VS 2015 and not VS 2017 for the NetCoreLibrary.
I created the ClassLibrary with VS 2017 and a local nuget repository.

My project.json is the following:
```
{

  "version": "1.0.0-*",

  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.DotNetHost": "1.0.1",
    "Microsoft.NETCore.DotNetHostPolicy": "1.0.1",
    "NETStandard.Library": "1.6.0",
    "ClassLibrary": "0.0.1",
    "Edge.js": "6.5.1"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dnxcore50"
      ],
      "dependencies": {
        "Microsoft.NETCore.App": "1.0.0"
      }
    }
  },

  "runtimes": {
    "win7-x64": {},
    "ubuntu.16.04-x64": {}
  }
}
```
