### ISSUE TITLE
Edge not creating 32 bit executable 

### ISSUE THREAD

**Issue by SwadX** [tjanczuk/edge#596]
Hi I am bit new to C# and also Node.js. 
I have a 64bit windows server 2012 machine ( AWS instance ).
I have node 32 bit installed .
 I am trying to call a C# DLL from node.js thru edge.js like below
var getModel_info = edge.func({
			assemblyFile:'../Test/DLLs/test.dll',
			typeName: 'com.xxx.test.Startup',
			methodName: 'Invoke'
			});

the test.dll has been compiled with /platform:x86 option using csc compiler.
test.dll references another 3rd party dll which also expects 32bit .
Now if I create .exe with /platform:x86 compile option and call test.dll from it , everything works fine and the 3rd party dll runs fine.

But if I call it from edge it doesn't work . I have kept all the dependent DLL in the /Test/DLLs/ folder.

So my issue is how do I force edge.js to create the executable in 32bit only . is there a way to know what edge.js is creating i.e. 32bit or 64bit ?

I apologize if my question is not clear

**Comment by tjanczuk** [comment]
Hello World!

**Comment by SwadX** [comment]
Hello World ! tjanczuk !!

**Comment by SwadX** [comment]
@tjanczuk , can you please provide any light on this .

**Comment by agracio** [comment]
If you running on Windows with .NET 4.5+ Edge uses pre-compiled binaries located in native/lib folder. It has binaries for both 32 and 64 bit architectures. 
What do you mean by 'it doesn't work', what kind of error are you getting? Please provide more details.

**Comment by SwadX** [comment]
Hi agracio thank you for your explanation. 
What happens is the third party DLL does a license check with a 32 bit license server service running in the system. When I run the C# exe this third party DLL is able to communicate with this license server service properly and authorize the third party DLL's use. But when I create a parent DLL instead exe and call that parent DLL from Node thru Edge.js the communication to the license server is failing .  

So if I want edge.js to always use the 32bit binaries , how can I achieve this ? 

As the C# exe is compiled with platform:x86 and works fine I belive if Edge also generates 32bit then the license server communication will work.

**Comment by SwadX** [comment]
any help guys !!

**Comment by agracio** [comment]
Edge uses 32 bit binaries when it executes x86 C# code. You will need to provide some more details on this. What "communication to the license server is failing" means exactly, are you getting errors from C# or Edge.js?
