### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mafintosh** [tjanczuk/edge#597]
Could you cut a new release off master?
Currently you have to require this from git to get the node 8 support.

**Comment by tjanczuk** [comment]
Hello World!

**Comment by agracio** [comment]
I might be wrong but I think @tjanczuk created an auto-reply that posts `Hello World!` on any new issues on this repo. You can try my `edge-js` fork that has support for 8.2.1

**Comment by EricSmekens** [comment]
Agreed, I hope @tjanczuk has time for this soon.
But on the other hand, there will be a new version of Node.js soon to resolve a security issue.

https://nodejs.org/en/blog/vulnerability/oct-2017-dos/
Still, releasing now is better than nothing at all.

**Comment by kendfrey** [comment]
@agracio Will you be providing regular releases for Node updates? v9 isn't supported yet, but I was hoping to use it.

**Comment by agracio** [comment]
Yes, I've already updated to 8.8.1 and 6.11.5 to address latest security issues in NodeJs. Planning to look at 9.x over the weekend.

**Comment by agracio** [comment]
Just released new package with support for Node 9.0.0
