### ISSUE TITLE
Cannot find .dll that is in GAC

### ISSUE THREAD

**Issue by TheGuywithTheHat** [tjanczuk/edge#598]
I'm trying to reference System.Printing.dll in my node.js code like so:

```
edge.func({
    source: path.join(__dirname, 'print.csx'),
    references: ['System.Drawing.dll', 'System.Windows.Forms.dll', 'System.Printing.dll']
});
```
but get the error `error CS0006: Metadata file 'System.Printing.dll' could not be found` when running it.

For some reason, System.Printing is the only issue, System.Drawing and System.Windows.Forms work just fine. I have verified that System.Printing.dll exists and is functional by including the fully qualified path (`C:\Windows\Microsoft.NET\assembly\GAC_64\System.Printing\v4.0_4.0.0.0__31bf3856ad364e35\System.Printing.dll`), and verified that it is registered in the GAC:

```
C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools>gacutil.exe /l System.Printing
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The Global Assembly Cache contains the following assemblies:
  System.Printing, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=AMD64
  System.Printing, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=x86
  System.Printing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=AMD64
  System.Printing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=x86

Number of items = 4
```

What gives? I assume the issue is on my end, but honestly I have no clue. Could it have something to do with versions of GAC/.NET/whatever? System.Drawing and System.Windows.Forms are both listed with `Version=2.0.0.0` and `Version=4.0.0.0` in gacutil, but as you saw System.Printing is only listed with `Version=3.0.0.0` and `Version=4.0.0.0`.

**Comment by tjanczuk** [comment]
Hello World!

**Comment by agracio** [comment]
Have you tried creating a standalone .dll with your C# code instead of using .csx file?

**Comment by TheGuywithTheHat** [comment]
That may work, but there's a couple problems with it:

- At the moment, I don't know exactly how to do that. (I can't use Visual Studio, so if that's the usual solution I'd have to find another way).
- It introduces another build step which Edge is currently doing for me.

Currently I'm just referencing the fully qualified path to System.Printing. That works fine, it would just be better if I could reference it by `System.Printing.dll` alone. I don't want to spend hours fixing something that isn't broken, I'm just wondering if there's a quick fix, since it seems like `System.Printing.dll` alone _should_ work.
