### ISSUE TITLE
Just doesn't work on Linux + .NET Core (with most filesystems)

### ISSUE THREAD

**Issue by kmaragon** [tjanczuk/edge#599]
https://github.com/tjanczuk/edge/blob/ec699715947169b555c88a2eab9151cc774c32f2/src/CoreCLREmbedding/deps/deps_entry.cpp#L186

There is no case normalization. Most projects will have a package like Edge.js.CSharp in the project file. the dotnet restore process will download that into a folder called ~/.nuget/packages/edge.js.csharp...

So when the dep lookup is trying to validate the sha512, it basically never actually successfully opens the file because for most Filesystems popular on Linux, Filenames are case sensitive. So the sha match pretty much always fails for all packages on Linux.

**Comment by tjanczuk** [comment]
Hello World!

**Comment by agracio** [comment]
From the previous comments on this repo it appears that Edge does work fine on Linux when using .NET Core 1.0, but does not support any versions above 1.0.
I have a fork that supports version 1.+ - 2.0 that works on Linux, at least on Travis CI build machines, you can give it a try https://github.com/agracio/edge-js.

**Comment by kmaragon** [comment]
@agracio edge-js inherited the same issue. The dotnet SDK normalizes filenames for all packages to lower case. It's independent of the runtime, whether 1.0 or 2.0. edge-js has the same issue on Linux unless the filesystem is non-case-sensitive.

When newer versions of the dotnet SDK (starting with one that shipped with .NET Core 1.1, I believe) , the downloaded nuget package filenames are all normalized to be lower case. In both edge and edge-js, that snippet of code that I linked to looks for hash files for packages based on the denormalized names and always fails on linux (unless one were installing a package that is all lower case anyway).

It's kind of an ugly mismatch anyway. NuGet package names are all case insensitive, probably built on windows where filenames are case insensitive. For most mainstream Filesystems on Linux (ext, btrfs, reiser, etc) filenames are case sensitive. It seems one could rely on dotnet to have been lowercase everything for some time. But if edge (and by extension) edge-js wish to support pre-release versions of the dotnet sdk, they might need to have the logic to do case insensitive searching of files (which could really hurt performance).

On the other hand, if it were to *only* support recent versions of the dotnet cli, deps_entry.cpp could easily be changed to just normalize `library_name` to be lower case without a broader case-insensitive file search. And then it'd be able to find the library hash files.

But as it stands now, it doesn't work. For example, a common package: Microsoft.Extensions.Configuration. When downloaded locally it might look like:
```
~/.nuget/packages/microsoft.extensions.configuration/2.0.0/microsoft.extensions.configuration.1.0.0.nupkg
~/.nuget/packages/microsoft.extensions.configuration/2.0.0/microsoft.extensions.configuration.1.0.0.nupkg.sha512
~/.nuget/packages/microsoft.extensions.configuration/2.0.0/microsoft.extensions.configuration.1.0.0.nuspec
~/.nuget/packages/microsoft.extensions.configuration/2.0.0/lib/netstandard2.0/microsoft.extensions.configuration.dll
```

Then in https://github.com/agracio/edge-js/blob/master/src/CoreCLREmbedding/deps/deps_entry.cpp#L150

The function tries to open the hash file, in this case `~/.nuget/packages/microsoft.extensions.configuration/2.0.0/microsoft.extensions.configuration.1.0.0.nupkg.sha512`

It puts together the filename as:
`~/.nuget/packages/Microsoft.Extensions.Configuration/2.0.0/Microsoft.Extensions.Configuration.1.0.0.nupkg.sha512` based on the fact that the project file calls out the package by it's nuget package name with a mixed case specifier.

Then on line 186 the code tries to open that hash file. And on line 187 fstream.good() is false. Because on Linux with ext4, `~/.nuget/packages/Microsoft.Extensions.Configuration/2.0.0/Microsoft.Extensions.Configuration.1.0.0.nupkg.sha512` != `~/.nuget/packages/microsoft.extensions.configuration/2.0.0/microsoft.extensions.configuration.1.0.0.nupkg.sha512`

So the file it's trying to open doesn't exist. And running the node program that uses edge-js fails because it couldn't open any of hash files to verify any of the referenced libraries.

**Comment by agracio** [comment]
I'm afraid I am not a Linux expert, I use Windows to build the libraries and only test Linux implementation using Travis CI https://travis-ci.org/agracio/edge-js and occasionally using Ubuntu on Docker. It works fine with default Ubuntu server on both Docker and Travis CI . Perhaps different Linux flavours behave differently, but I wont be able to offer any additional help there.

**Comment by agracio** [comment]
Can you create some kind of code sample that would show the failures that you experiencing, preferably something that can be put into a test case that would make it fail on Travis?

**Comment by kmaragon** [comment]
Well the key is that for both the project.json issue and this one, the problem has nothing to do with what version of .NET core one uses. It's based on the version of the dotnet cli that they use. And edge-js is the only way you can get support for *any* stable version of the dotnet sdk (the dotnet cli was still in prerelease when .NET Core 1.0 was released).

So that means that even if the project is targeting .NET Core 1.0, vanilla edge *still* just doesn't work. edge-js is the only npm package that works at all with any stable dotnet sdk release, as long as one doesn't use any nuget packages. I didn't see any tests being run by travis that make node -> .NET calls which use nuget packages. And it's specifically the file hash validation of nuget packages that is broken in edge-js on Linux (in the function I previously cited). It's 100% because of filesystem case sensitivity, which is why works even for .NET Core 2.0 on Windows or OSX but not Linux.

And again, fixing it by just lower-casing library_name in deps_entry (2 line fix) will fix that test but could break any users that are using Linux on *old* versions of the dotnet tools. If that whole method were refactored to do directory listing and do a case insensitive comparison of every package it has for every package it needs, then the performance of library resolution might be pretty negatively impacted but it should also fix nuget package loading on Linux for both new and old versions of the dotnet sdk.

**Comment by agracio** [comment]
The tests use Newtonsoft.Json package.

**Comment by kmaragon** [comment]
Which one (that does node -> .NET calls)?

**Comment by kmaragon** [comment]
https://github.com/agracio/edge-js/pull/7

So there is a case sensitivty issue. But I'm not sure why it suddenly is happening now when it didn't used to. I see your travis builds not failing. But my Docker container running the tests breaks on all of the tests. Not just the one I added.

**Comment by agracio** [comment]
This one
* https://github.com/agracio/edge-js/blob/master/test/201_patterns.js#L218
* https://github.com/agracio/edge-js/blob/master/test/tests.cs#L398

The difference is that it uses pre-compiled .dll file for test and not inline calls.

**Comment by agracio** [comment]
Narrowed the problem down to Linux and .NET Core 2.0.x. It works on Linux using .NET Core 1.0.4, MacOS 1.0.4 - 2.0.x and Windows 1.0.4 - 2.0.x. Will have to look more into this one.

**Comment by agracio** [comment]
The problem is considerably more complex than it originally appeared. The call https://github.com/agracio/edge-js/blob/master/src/common/edge.cpp#L50 to `CoreClrEmbedding::Initialize` method located at https://github.com/agracio/edge-js/blob/master/src/CoreCLREmbedding/coreclrembedding.cpp#L178 fails on .NET Core 2.0.x on Linux. CoreClr routines are either not initialised at all or perhaps partially initialised, so the problem is not with .NET packages. 
This looks like it will take considerable time to investigate and resolve, I'd recommend to use .NET Core 1.0.4 in the meantime.
I am rather curious why it works on MacOS with .NET Core 2.0.0 though.

**Comment by kmaragon** [comment]
Incidentally, I can’t get dotnet 2.0 working on Windows either
 
The first issue is this new “feature”
 
https://github.com/dotnet/dotnet-docker/issues/237
 
Which seems like less of a feature for many use cases. But edge-js fails to probe that NugetFallbackFolder. Therefore, without disabling that, loading packages fails because the packages aren’t found.
 
I can set the environment variable DOTNET_SKIP_FIRST_TIME_EXPERIENCE and delete that fallback folder before doing a dotnet restore / build. That will then put all of the dependent packages in a place where edge-js knows to look for them. But once it finds them, this happens:

 ```
CoreClrEmbedding::Initialize - CoreCLR initialized successfully
CoreClrEmbedding::Initialize - App domain created successfully (app domain ID: 1)
Error occurred during CoreCLR initialization
Failed: Call to coreclr_create_delegate() for G failed with a return code of 0x80070002.
  Stack:
    Error: Call to coreclr_create_delegate() for G failed with a return code of0x80070002.
        at Object.Module._extensions..node (module.js:598:18)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (C:\Users\...\edge-js\lib\edge.js:51:8)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
 ```

**Comment by agracio** [comment]
Never tried to run it in a Docker container to be honest. Works on multiple Windows versions that I happen to work with.

**Comment by agracio** [comment]
It took me two months but I believe I've solved the problem with Linux and .NET Core 2.0.
The new version is not on NPM yet, but so far it runs .NET Core 1.0.4 on Travis CI Ubuntu, .NET Core 1.0.3 Travis CI macOS and local .NET Core 2.0 on both Ubuntu and macOS.
I will push this build to NPM in a few days, let me know of you can test it in the meantime.

**Comment by agracio** [comment]
The new version with full .NET Core 2.0 support on Linux is now on NPM v9.3.2

**Comment by westonpace** [comment]
I'm not certain I agree that .NET Core 2.0 is working on Linux.  I'm running into the exact same case sensitivity issue mentioned by @kmaragon .  The failure I receive is:

```
The hash file is invalid [/home/ubuntu/.nuget/packages/Microsoft.CSharp/4.4.1/Microsoft.CSharp.4.4.1.nupkg.sha512]
    Skipping... match hash failed
  Considering entry [Microsoft.CSharp/4.4.1/lib/netstandard1.3/Microsoft.CSharp.dll] and probe dir [/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.2]
    Skipping... probe in deps json failed
    Local path query did not exist /home/ubuntu/test/node_modules/edge-js/lib/bootstrap/bin/Release/netcoreapp1.1/Microsoft.CSharp.dll
Error: assembly specified in the dependencies manifest was not found -- package: 'Microsoft.CSharp', version: '4.4.1', path: 'lib/netstandard1.3/Microsoft.CSharp.dll'

```

This seemed very strange to me that a hash file would be invalid.  I also noticed that `/home/ubuntu/.nuget/packages/Microsoft.CSharp/4.4.1/Microsoft.CSharp.4.4.1.nupkg.sha512` does not exist.  The file is named `/home/ubuntu/.nuget/packages/microsoft.csharp/4.4.1/microsoft.csharp.4.4.1.nupkg.sha512`.

Note that this error is similar to the one reported in https://github.com/agracio/edge-js/issues/26 but I did not install anything as root so it isn't a permissions issue.

Digging further it appears there was a NuGet change to how dependencies are stored (https://github.com/NuGet/Home/issues/2522) which caused them to get stored all lowercase.  A change had to be made to the CLR to adapt to this (https://github.com/dotnet/core-setup/issues/1559) and was made in 1.0.5.  The fix (https://github.com/dotnet/core-setup/pull/1807/files) involved changes to files like `deps_entry.cpp` which I notice is present in this repo in `CoreCLREmbedding`.  The lowercasing fix is not present in the `deps_entry.cpp` version in `edge` or `edge-js`.

Also, I looked into the TravisCI builds for `edge-js` and, as best I can tell, they are still using .NET 1.0.4 so I'm not certain that .NET Core 2.0 is working on Linux correctly.

**Comment by westonpace** [comment]
Ok.  I dug further.  It appears that agracio DID bring the lowercasing fix in `deps_entry.cpp`.  However, it is not being applied because it is behind `#if EDGE_PLATFORM_NIX` and `EDGE_PLATFORM_NIX` is not defined.  This is because in `deps_entry.h` there are the lines:

```
#if EDGE_PLATFORM_NIX
#include "../edge.h"
#endif
```

However `EDGE_PLATFORM_NIX` will not be defined until `edge.h` is included and so `edge.h` is never included and `EDGE_PLATFORM_NIX` is not defined.  I will open a separate issue against `edge-js` for this.
