### ISSUE TITLE
Edge.Func(...) hangs when running/debugging app in linked folder

### ISSUE THREAD

**Issue by peter-hartmann** [tjanczuk/edge#601]
Using Edge.js.8.2.1 I can reliably reproduce a hanging Edge.Func(...) call when running/debugging my executable through a linked folder.  Since our build setup depends on symlinks this is kind of a big deal for us.  E.g.:

Have:
```
c:\bin\ConsoleAppUsingEdgeJS.exe
c:\bin\edgejs.dll
c:\bin\edgejs\...
d:\symlink2bin\
```
Now run:
```
c:\bin\ConsoleAppUsingEdgeJS.exe           <-- all good
d:\symlink2bin\ConsoleAppUsingEdgeJS.exe   <-- hangs
```
Similar in VS2015 Project for ConsoleAppUsingEdgeJS when debugging:
```
if exe was build with build output path set to c:\bin\          <-- all good while debugging
if exe was build with build output path set to d:\symlink2bin\  <-- Edge.Func never returns
```
Is there any workaround that makes symlinks work?

**Comment by tjanczuk** [comment]
Hello World!

**Comment by peter-hartmann** [comment]
#410 - looks related.
