### ISSUE TITLE
using log4.net with edge

### ISSUE THREAD

**Issue by jeremiah-c** [tjanczuk/edge#602]
is it possible to use log4net inside the dll's i'm using via edge? if i run my dll via a simple hello world project, the log4net calls log, whereas if i invoke the same methods via edge, the methods run correctly, return correct data, but there is no log4net logging. is there some special namespace issue? i tried including the roslyn //r# for the additional log4net assemble; not luck.

**Comment by tjanczuk** [comment]
Hello World!

**Comment by jeremiah-c** [comment]
is it possible to leverage log4net calls nested in dll invoked via edge? do i need to do something special in the classes that make up the dll?

**Comment by jeremiah-c** [comment]
log4net works find with dll's node/edge is using. i just needed to qualify my path to the log4net.config.
