### ISSUE TITLE
 node-gyp: versions = _DetectVisualStudioVersions(version_map[version], 'e' in version) KeyError: '2017'

### ISSUE THREAD

**Issue by paulprendergast** [tjanczuk/edge#603]
Hi all, I have seen similar issues around my problem and tried some of them but no solutions. I am in desperate need to get this resolved.  if it has been resolved can you direct me to page and location on page or give me direct feedback. any feed back please?

what I am trying to do is build out NattiveCLR.node and coreCLR.node with electron-edge-js and make hello world for electron and electron-edge-js work. what I am getting is the below problem.

Problem:
versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017'
attached are my logs
[KeyError2017.pdf](https://github.com/tjanczuk/edge/files/1452281/KeyError2017.pdf)

it seems to be with node-gyp.
I can node-gyp build at the root at electron-edge-js and electron-edge but when i try under \tools\build.bat release 7.9.0 i always get error.
when I do \tools\build.bat release 7.9.0 for edge it works and hello world works

using the latest electron = 1.7.9

**My Computer:**
Win10
VS2015
Python=2.7.9
angularCLI =latest

**Environment Vars:**
GYP_MSVS_VERSION= 2015

**Comment by tjanczuk** [comment]
Hello World!

**Comment by agracio** [comment]
Looks like the same issue as this one: https://github.com/agracio/edge-js/issues/10
Why would you want to build 7.9.0 on `electron-edge-js` if it's already included there?

**Comment by paulprendergast** [comment]
The build 7.9.0 on electron-edge-js did not work out of the box or when I tried \tools\build.bat. so this why I posted for KeyError=2017. When I try with just edgejs it gave error below and told me to run \tools\build.bat and it builds and I dont get below error and hello world works. it did say it support Electron 1.7.x - Node.js v7.9.0. when I run hello world for electron-edge-js I get below logs.
 Do you have another suggestions? 

For second lead you gave me, I followed the link you provided and installed Windows 8.1 SDK in Build Tools for Visual Studio 2017. still no luck. what more do you suggest I need to install with build tools VS2017 or other options?

TypeError: Cannot read property 'initializeClrFunc' of undefined
    at Object.exports.func (C:\electronDevelopment\chap5\electronEdge4\node_modules\electron-edge-js\lib\edge.js:181:16)
    at Object.<anonymous> (C:\electronDevelopment\chap5\electronEdge4\testedge.js:4:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)

**Comment by agracio** [comment]
I am surprised that `electron-edge-js` 7.9.0 build does not work for you out of the box, I use it in multiple applications with Electron 1.7.9. To build 7.9.0 in electron-edge-js change msvs_version to 2015 in `build.bat` that should work for you.

**Comment by paulprendergast** [comment]
I have found that the build.bat that 
"C:\\electronDevelopment\\chap5\\electronEdge4\\node_modules\\electron-edge-js\\lib\\native\\win32\\x64\\7.9.0\\node.exe" "C:\\Users\\Paulp\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build" **"--target=1.7.6"** "--dist-url=https://atom.io/download/atom-shell" **"--msvs_version=2017"** "-release"

has hard coded target and msvs_version. when I make the change to --target=1.7.9 and --msvs_version=2015
**it build successfully.**

but I still end up with TypeError: Cannot read property 'initializeClrFunc' of undefined when running for hello world. @agracio is see you on #495. do you know if any more leads.

**Comment by Ak-lilu** [comment]
jhgffdghjk
