### ISSUE TITLE
No pre-compiled version for 8.9.0

### ISSUE THREAD

**Issue by aapablaza** [tjanczuk/edge#604]
Hello.

I tried Edge, but it sends me "Error: The edge module has not been pre-compiled for node.js version 8.9.0. You must build a custom version of edge.node. ..."

I read in another issue that 8.x was supported, and also that 9.0 support was already done.. so I don't understand why I'm getting that error.

Windows 10. Error pop-ups when installing (npm install edge --save).

Thanks for time and help,
Best Regards,
Alex

**Comment by tjanczuk** [comment]
Hello World!

**Comment by aapablaza** [comment]
Clossing Issue.

Just cloned the project and installed from here. Please update in npm.
