### ISSUE TITLE
fails to run at Win7 x64, where no dev enviornment present

### ISSUE THREAD

**Issue by freezepro** [tjanczuk/edge#605]
We used this project with unoficial PlayMusic library(google music api), it works in node.js version.
So trying to use it in production Win7, x64 bit(same as dev machine) with .net 4.5 installed and it simply crashes, no exception happens nothing. It crashes at very first call(login to google music) method.

Any ideas or help how to check it ?
note.it failed on another machine same way and we installed Vs.NET 2017 free edition to test, suddenly this thing started to work. 
also we tried to install .net 4.6.1(without vs.net) at machine that doesnt work and still same.

**Comment by tjanczuk** [comment]
Hello World!

**Comment by freezepro** [comment]
Hello.just a note
Tried several older versions of EDGE.JS, so 6.11 works fine

**Comment by agracio** [comment]
Have you tried to install .NET SDK and see if it makes a difference?

**Comment by freezepro** [comment]
Nope, however I can't do that on every client machine(as it's now in production), as of now it works great with 6.11(so far...)
