### ISSUE TITLE
Edge js and .net standard 2.0 error

### ISSUE THREAD

**Issue by DotNet-Fan** [tjanczuk/edge#606]
Hi iam trying to call a .net method available in a .net standard 2.0 class library  from node and edge and iam getting this error. Can you please help?

Error: Unable to compile C# code.
----> Errors when compiling as a CLR library:
c:\xxxx\xxxxxx\AppData\Local\Temp\jobeqsy5.0.cs(9,15) : error CS0012: The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

var edge = require('edge');

var standardfunction = edge.func({
  source: function () {
    /*
        using Standard.Edge;
        using System.Threading.Tasks;
        
        public class Startup
        {
            public async Task<string> Invoke(object input)
            {
              EdgeClass cls = new EdgeClass();
              return cls.GetValue();
            }
        }
    */
  
  },
  references: ['./lib/EdgeClient.dll']
});

standardfunction('Node', function (error, result) {
    if (error) throw error;
    console.log(result);
  });

**Comment by tjanczuk** [comment]
Hello World!

**Comment by Kallzz** [comment]
Hi Team , I appreciate if you can provide some inputs around this.

**Comment by benydc** [comment]
I had same issue and I used netstandard.dll 4.7.2633.0 as reference, but I have a different error now:
`error CS0012: The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.`

I'm using .net core 2.0 and I think the edge library is using VS 2015. I was going to try and replace those dlls with newer version but I think they are used by the edge native addon.

**Comment by agracio** [comment]
Take a look at this example app that uses .NET Core 2.0: https://github.com/agracio/edge-js-quick-start

**Comment by benydc** [comment]
@agracio I installed edge-js and I get same error.

**Comment by agracio** [comment]
Have you followed steps from the sample app?

**Comment by grofit** [comment]
@benydc did you ever solve this issue?
