### ISSUE TITLE
Does edge support Node.js 8.4.0?

### ISSUE THREAD

**Issue by zhangming1978** [tjanczuk/edge#607]
I got message like below:

> Error: The edge module has not been pre-compiled for node.js version v8.4.0. You must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge for building instructions.

Has someone successful run edge on Node 8.4.0?

**Comment by tjanczuk** [comment]
Hello World!

**Comment by agracio** [comment]
Edge does not have pre-compiled binaries for Node v8.x you can either compile it yourself or use a this fork that comes with support for v8.x and v9.x https://github.com/agracio/edge-js.

**Comment by mhcgolds** [comment]
@agracio now that is an useful answer. Thanks for the fork, saves lots of time!
