### ISSUE TITLE
Bug in QMap::destroySubTree

### ISSUE THREAD

**Issue by jpek42** [tjanczuk/edge#608]
Noticed in the 5.6 source code, and it's still an issue in current code:
`void destroySubTree()
    {
        callDestructorIfNecessary(key);
        callDestructorIfNecessary(value);
        doDestroySubTree(QtPrivate::integral_constant<bool, QTypeInfo<T>::isComplex || QTypeInfo<Key>::isComplex>());
    }`

Note that the first "isComplex" should be a method call, like the 2nd. 

This is also causing warnings in Visual Studio 2017:

> 3>d:\cam-main\invcam\thirdparty\hsm\qt\5.6\include\qtcore\qmap.h(127): warning C4718: 'QMapNode<enum Iron::Tools::ToolLibraryActions::EActionType,QAction * __ptr64>::doDestroySubTree': recursive call has no side effects, deleting
3>d:\cam-main\invcam\thirdparty\hsm\qt\5.6\include\qtcore\qmap.h(127): warning C4718: 'QMapNode<enum Iron::Tools::FilterType,QWidget * __ptr64>::doDestroySubTree': recursive call has no side effects, deleting

Thank you!

**Comment by tjanczuk** [comment]
Hello World!

**Comment by jpek42** [comment]
Weird. I certainly didn't mean to open this issue in your repo. Sorry about that. It must have taken me here from my earlier issue. Feel free to delete/close.
