### ISSUE TITLE
Occasional ModuleLoadException from edge_nativeclf.node

### ISSUE THREAD

**Issue by davidhouweling** [tjanczuk/edge#610]
I'm using Edge to load up Node within an ASP.NET web application and occasionally when Edge.func is called, it simply crashes the process (I have it on in debug mode) with the following in the output:

```
Exception thrown: '<CrtImplementationDetails>.ModuleLoadException' in edge_nativeclr.node
```

It also causes the IIS App pool to stop, and requires me to restart it.

I initially thought it might be to do with the node script, but i changed the node script to a super simple one (like the Hello world example) and was still getting it.

Edge version: 6.5.1
Node DLL: 6.5.0
Installed Node version on Windows 10: 6.11.3

**Comment by tjanczuk** [comment]
Hello World!

**Comment by davidhouweling** [comment]
Unfortunately it is difficult for me to show it in action as it's part of quite a large solution. Oddly though, on a super simple .NET solution I haven't encountered it. Is there a way to get further debugging information for situations like this though?

**Comment by davidhouweling** [comment]
@tjanczuk would you be able to provide guidance on how to generate the PDB for edge_nativeclr.node? I noticed there were no VS based solution/project files, so not entirely sure what the appropriate approach should be.

**Comment by davidhouweling** [comment]
For future reference, even though Windows will say that C++ 2017 is the more up to date distribution, you must uninstall it and install C++ 2015 for this to work consistently.
