### ISSUE TITLE
Running sample code results in System.AccessViolationException

### ISSUE THREAD

**Issue by rogerfar** [tjanczuk/edge#611]
I have an ASP.NET project and added Nuget package. When I execute the sample code in Visual Studio 2017 in debug mode it gives me the following exception:

    'iisexpress.exe' (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131571488773891858): Loaded '\\?\C:\Projects\Project\bin\edge\x86\edge_nativeclr.node'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    An unhandled exception of type 'System.AccessViolationException' occurred in edge_nativeclr.node
    Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

What could cause this?

**Comment by tjanczuk** [comment]
Hello World!

**Comment by yesman85** [comment]
@tjanczuk what do you mean? Yes I used the hello world code from the main page...

**Comment by agracio** [comment]
@tjanczuk has set 'Hello World!' auto-reply to all new issues in this repo. This issue requires merge of PR https://github.com/tjanczuk/edge/pull/573, however it appears that this repo is no longer maintained. I have a fork that has that PR merged, you can try it out: https://github.com/agracio/edge-js. There is no *nuget* package on the fork, instead the binaries are attached to the release page https://github.com/agracio/edge-js/releases.

**Comment by yesman85** [comment]
Unfortunately that didn't do the trick, I tried the 9.0 release but it just kills iisexpress without any warning.
