### ISSUE TITLE
musl libc: error: 'timeval'

### ISSUE THREAD

**Issue by acoul** [tjanczuk/edge#612]
Greetings,

On Void-linux musl-x86_64 when trying to npm install edge I am getting the following error:

  >./src/CoreCLREmbedding/json/casablanca/include/cpprest/asyncrt_utils.h:496:47: error: 'timeval' does not name a type; did you mean 'timegm'?
  >     static datetime timeval_to_datetime(const timeval &time);
  >                                              ^~~~~~~
  >                                            timegm`

**Comment by tjanczuk** [comment]
Hello World!
