### ISSUE TITLE
Crash when using mono 5.4.x

### ISSUE THREAD

**Issue by SmartBuster** [tjanczuk/edge#613]
I am trying to get it running with mono 5.4 and encounter a crash (on MacOS).

This crash originates from the Dictionary::Add method, because the 
```
add = mono_class_get_method_from_name(mono_object_get_class(_this), 
"System.Collections.Generic.IDictionary<string,object>.Add", -1);
```

call in line 8 returns a NULL pointer. I understand the reason for this, but don't understand why this does not occur under mono 4.8.

The most common usage is with an `ExpandoObject` which implements `System.Collections.Generic.IDictionary<string,object>.Add` but unfortunately as private interface using explicit interface implementation. Using reflection clearly shows the method to be private.

The methods can be made visible by explicitly casting an object to the interface. While this works when written in C# I am still not able to get it working with mono embedding.

I request the method from the specific interface class <string, object> and use `mono_object_castclass_mbyref`to cast the `_this` object to one of  the interface class.

My current workaround is an additional static method in MonoEmbedding.cs that gets the object, key & value and makes the operation in C# code, which works, but I am not happy about the switch from native to managed and back which is used many times.

Anyone with a better solution?

**Comment by tjanczuk** [comment]
Hello World!
