### ISSUE TITLE
edge source code is not ported for the new v8 engine (6.3) shipped with Chrome 63

### ISSUE THREAD

**Issue by wythe0102** [tjanczuk/edge#614]
I get an problem when using node-gyp to build the source code. the commond is `node-gyp build`

for details please refer [](https://github.com/nwjs/nw.js/issues/6342) .

is there any solution for this issue?

**Comment by tjanczuk** [comment]
Hello World!

**Comment by agracio** [comment]
What Node.Js version you using and what issues you getting?
