### ISSUE TITLE
macOS install errors

### ISSUE THREAD

**Issue by fudgepop01** [tjanczuk/edge#615]
Hello, for the past two days i've been trying to install this but to no avail. I've been experiencing errors from "unable to locate pkg-config" to "binding.gyp not found" to, this one that i'm experiencing at present: 

`MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.`

I'm running a fresh install of node `8.9.3 LTS` and have (I THINK) installed `node-gyp` successfully multiple times. The mono framework i'm using is `5.4.1`.

Here is the terminal output when running 
`sudo sudo PKG_CONFIG_PATH=/Library/Frameworks/Mono.framework/Versions/5.4.1/lib/pkgconfig npm install edge`

(...yes the double sudo is necessary for some reason or else I get EACCESS errors)

> 
>> electron-edge@6.5.5 install /Users/Dominick/Creative Cloud Files/SVG_Builder/input-display/app/node_modules/electron-edge
> node tools/install.js

> xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line to
ols instance

> xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line to
ols instance
>  CXX(target) Release/obj.target/edge_nativeclr/src/mono/clractioncontext.o
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/clrfunc.o
../src/mono/clrfunc.cpp:365:13: warning: 'SetPrototype' is deprecated [-Wdeprecated-declarations]
    result->SetPrototype(v8::Exception::Error(message));
            ^
/Users/Dominick/.node-gyp/8.9.3/include/node/v8.h:3256:3: note: 'SetPrototype' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", bool SetPrototype(Local<Value> prototype));
  ^
/Users/Dominick/.node-gyp/8.9.3/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/clrfuncinvokecontext.o
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/monoembedding.o
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/task.o
>  CXX(target) Release/obj.target/edge_nativeclr/src/mono/dictionary.o
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/nodejsfunc.o
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/nodejsfuncinvokecontext.o
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/utils.o
  CXX(target) Release/obj.target/edge_nativeclr/src/common/utils.o
../src/common/utils.cpp:23:13: warning: 'SetPrototype' is deprecated [-Wdeprecated-declarations]
        exception->SetPrototype(v8::Exception::Error(Nan::New<v8::String>(message).ToLocalChecked()));
                   ^
/Users/Dominick/.node-gyp/8.9.3/include/node/v8.h:3256:3: note: 'SetPrototype' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", bool SetPrototype(Local<Value> prototype));
  ^
/Users/Dominick/.node-gyp/8.9.3/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
>  CXX(target) Release/obj.target/edge_nativeclr/src/common/v8synchronizationcontext.o
  CXX(target) Release/obj.target/edge_nativeclr/src/common/edge.o
  SOLINK_MODULE(target) Release/edge_nativeclr.node
  CXX(target) Release/obj.target/edge_coreclr/src/common/v8synchronizationcontext.o
  CXX(target) Release/obj.target/edge_coreclr/src/common/edge.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrembedding.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrfunc.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrnodejsfunc.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrfuncinvokecontext.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrnodejsfuncinvokecontext.o
  CXX(target) Release/obj.target/edge_coreclr/src/common/utils.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/pal/pal_utils.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/pal/trace.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/fxr/fx_ver.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/fxr/fx_muxer.o
>  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/json/casablanca/src/json/json.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/json/casablanca/src/json/json_parsing.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/json/casablanca/src/json/json_serialization.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/json/casablanca/src/utilities/asyncrt_utils.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/deps/deps_format.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/deps/deps_entry.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/deps/deps_resolver.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/host/args.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/host/coreclr.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/host/libhost.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/host/runtime_config.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/pal/pal.unix.o
  SOLINK_MODULE(target) Release/edge_coreclr.node
  ACTION binding_gyp_build_managed_target_restore_bootstrap_packages lib/bootstrap/project.lock.json
> /bin/sh: Cloud: command not found
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
make: *** [lib/bootstrap/project.lock.json] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/Dominick/Creative Cloud Files/SVG_Builder/input-display/app/node_modules/electron-edge
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

>npm WARN electron-react-boilerplate@1.0.0 No repository field.

If anyone can help me figure this out I'd be MUCH appreciated. Thanks!

**Comment by tjanczuk** [comment]
Hello World!

**Comment by agracio** [comment]
First of all you should not need to use `PKG_CONFIG_PATH=/Library/Frameworks/Mono.framework/Versions/5.4.1/lib/pkgconfig` when installing edge on macOS. Once you have all the required components installed on your system you just need to `npm install edge` in your project. First you need 'node-gyp' installed as global package `npm install -g node-gyp`. 'pkg-config' problem appears to be a recent one and I am not sure whether it is related to latest Mono runtime or some updates on macOS but adding it using Homebrew `brew install pkg-config` solves the problem.

Now the actual error you getting is related to .NET Core code parts and not Mono code. Edge.js only supports old C# project definitions 'project.json' that were deprecated after .NET Core v1.0.0 and replaced by proper '.csproj' format. This causes an error on .NET Core portion of compile.

There is also another problem, `edge` does not support Mono runtime in its current state, you can read more details here: https://github.com/agracio/edge-js/issues/15.

Since @tjanczuk abandoned the project I run a fork of 'edge' called `edge-js` that adds various fixes and improvements that includes a fix for Mono runtime. https://github.com/agracio/edge-js
Try it out and let me know if you have any issues.

**Comment by fudgepop01** [comment]
Oh! Wow - I didn't realize that this project was abandoned. it's awesome that you're running something that keeps this project alive! I eventually tried your edge-js (albiet with the idea that it was outdated, ironically enough), and that ended up working.

Thanks again!

**Comment by agracio** [comment]
Considering that Mono runtime fix was only published yesterday, you have chosen the perfect time to try it :)
