### ISSUE TITLE
Webpack missing module

### ISSUE THREAD

**Issue by aneogiarcadix** [tjanczuk/edge#616]
It seems like webpack can't find type definitions for the package, but I'm not sure why it needs any. 
I have a server.ts file, which has a simple hello world edge.js proxy function. I bundle the file using webpack, and it is completed successfully. But the bundled file has "webpackMissingModule" error at the import. 
bundle.js
> edge = !(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }());

Please suggest a fix for this. 

> 
> Application has thrown an uncaught exception and is terminated:
> Error: Cannot find module "."
>     at webpackMissingModule

**Comment by tjanczuk** [comment]
Hello World!

**Comment by agracio** [comment]
See https://github.com/agracio/edge-js/issues/16
