### ISSUE TITLE
how can i use C# original dll

### ISSUE THREAD

**Issue by popsugon** [tjanczuk/edge#617]
is there a way that I can directly to use C# .dll through edge?

**Comment by tjanczuk** [comment]
Hello World!

**Comment by popsugon** [comment]
take Excel.dll as an example. C# already has interface about Excel, How can I use it directly? if every function about Excel should follow "public async Task<object> Invoke(object input)", it would be a long work

**Comment by benydc** [comment]
You should get that C# interface or wrapper and compile with csc.exe. Edge will not work with any build from VS Then, you can reference it in JS like this:

```javascript
var edge = require('./lib/edge');

var invokeAction = edge.func({
    //assemblyFile: 'Sample105.dll',
    source: () => {
       /* Your C# code with Invoke */
    },
    references: ['Excel.dll', 'ExcelWrapper.dll'];
```

I suggest you use a switch to handle multiple methods.
