### ISSUE TITLE
C# module lets application crash hard when Edge.AssemblyDirectory contains a non-ASCII character

### ISSUE THREAD

**Issue by haukepribnow** [tjanczuk/edge#621]
### Example situation:
`Edge.AssemblyDirectory = @"C:\dev\demöß"`
(You can get this situation when creating a new project in this a folder and installing the current version of Edge.Js via NuGet.)

### Example code that makes problem appear:
```
var testfunc = Edge.Func("return function (data, callback) {callback(null, \"Test\");};");
var a = 1;
```
Set a breakpoint on `var a = 1;`

### Result:
The application crashes hard at the `testfunc` assignment, i.e. without throwing an exception. The breakpoint on the `a` assignment will never be reached.

### Cause:
Edge.Js seems to use a Unicode-insensitive version of `LoadLibrary`:
```
    [DllImport("kernel32.dll")]
    private static extern int LoadLibrary([MarshalAs(UnmanagedType.LPStr)] string lpLibFileName);
```

Instead, a Unicode-sensitive version of `LoadLibrary` should be used as recommended for example [here](https://stackoverflow.com/a/40907385/1560865):
```
    [DllImport("kernel32", SetLastError = true]
    private static extern IntPtr LoadLibraryW([MarshalAs(UnmanagedType.LPWStr)] string lpLibFileName);
```

**Comment by tjanczuk** [comment]
Hello World!
