### ISSUE TITLE
cannot build with 9.3.0

### ISSUE THREAD

**Issue by vishnu-meera** [tjanczuk/edge#622]
I was running my application in LTS version, changed the node version to 9.3.0.
After that my edge app is not working.

I tried to build it, but getting below error.

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\*******\AppData\Roaming\npm\
node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:209:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Users\\*******\\Desktop\\node\\node_modules\\edge\\lib\\na
tive\\win32\\x64\\9.3.0\\node.exe" "C:\\Users\\*******\\AppData\\Roaming\\npm\\n
ode_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build" "--msvs_version=201
5" "-release"
gyp ERR! cwd C:\Users\*******\Desktop\node\node_modules\edge
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Error building edge.node release for node.js x64 v9.3.0

**Comment by tjanczuk** [comment]
Hello World!
