### ISSUE TITLE
is it possible to simply return a string?

### ISSUE THREAD

**Issue by kappa10j** [tjanczuk/edge#624]
public async Task<object> GetTitle(object input)
        {
            return "a string";
        }

const dialog = require('./support/dialog.js')
var f = await dialog.GetTitle();

---------------------------
'use strict';
const edge = require('edge-js')
const GetTitle = edge.func({
  assemblyFile: 'Library.dll',
  typeName: 'Library.ClassName',
  methodName: 'GetTitle'
})
module.exports = {

  GetTitle
    
}

**Comment by tjanczuk** [comment]
Hello World!

**Comment by benydc** [comment]
change return type to `Task<string>` in C#:
```c#
        public async Task<string> Invoke(ActionCanonSDK action)
        {
             return "hello world";
        }
```
