### ISSUE TITLE
not working in a .net standard 1.6 library

### ISSUE THREAD

**Issue by woodp** [tjanczuk/edge#625]
I create a .net standard class library (VS 2017), change it to .net standard 1.6, add edge.js 8.2.1 nuget package and try to use it. Is as if I wouldn't have added the nuget package at all.

Do I need to do something else?

This how my .csproj looks like:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.6</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Edge.js" Version="8.2.1" />
  </ItemGroup>

</Project>
```

**Comment by tjanczuk** [comment]
Hello World!

**Comment by agracio** [comment]
Take a look at project readme, there is compatibility table at the very top, you can only script Node.js from .NET Framework, Core CLR is not supported.
