### ISSUE TITLE
var func = Edge.Func(@"return require('../server.js');"); hangs in Visual Studio

### ISSUE THREAD

**Issue by ivoloshin** [tjanczuk/edge#629]
So, if i compile my application and run it from the exe, that function works fine. However, in Visual Studio it hangs. This started just recently, so I'm  not sure if it's a VS update that did it or something else.

I tried updating to latest edgejs package from nuget (previously was running 0.10), but it didn't help.

Any suggestions on how to trouble shoot it?

Thanks!

Edit: So, more weirdness is that 1. it works on other PCs. 2. It works on my PC under a different Windows Profile (another user logged in). 3. it still does not work for under my profile.

I'm going to create a new profile for my account and I'm sure that'll fix it, but it's just really strange. Maybe you can help me with identifying any temp locations where EdgeJS might be writing to clear those out?

**Comment by tjanczuk** [comment]
Hello World!

**Comment by ivoloshin** [comment]
Deleting all files in %temp% fixed my issue.
