### ISSUE TITLE
importing large interrelated node module breaks in edge.js

### ISSUE THREAD

**Issue by AnkitSource** [tjanczuk/edge#637]
I am writing a C# based Console application (.net framework v4.6.1) that can interact with Node modules.

In my code I am trying to import a node module (using edge.js v6.5.1 package) that internally importing other modules (more than 50 other modules) inside it.

Nothing comes as a result I just get following message inside Visual Studio Output window:

The program '[21072] [application].exe' has exited with code -1066598273 (0xc06d007f) 'Procedure not found'.

Following is my code:

```
public static async Task Start()
{
    var func = Edge.Func(@"
            return function (data, callback) {
                var x = require('../[path to module]');
                console.log(x.prop1);
            }
        ");

    await func(null);
    Console.Read();
}

static void Main(string[] args)
{
    Start().Wait();
}
```

Though if i use a simple module that has less or no dependencies works pretty fine with above code base.

Please suggest me if I am missing anything.

**Comment by AnkitSource** [comment]
So I have just noticed there are few circular reference inside the modules..
such as module1 has module2 imported then module3 importing module1.. is that makes any difference?

**Comment by rkaw92** [comment]
In Node, that would cause `require()` in one of the modules to return an empty object `{}`. Try running it with Node first.

Dnia 26 kwietnia 2018 07:50:43 CEST, Ankit Agrawal <notifications@github.com> napisał(a):

**Comment by AnkitSource** [comment]
@rkaw92 thanks for your response.. 
With Node application runs pretty well, it's an existing and running application I need to consume it's Node modules to get access to the db.. the CouchDb, that Node application already using.. 

Also is there a way I can see the logs/traces is there any that may help finding the issue?
