### ISSUE TITLE
asyncrt_utils.h: xlocale.h has been renamed

### ISSUE THREAD

**Issue by StewartThomson** [tjanczuk/edge#644]
The files "src/CoreCLREmbedding/json/casablanca/include/cpprest/asyncrt_utils.h" and "src/CoreCLREmbedding/cpprest/asyncrt_utils.h"  include xlocale.h
xlocale.h has been renamed in glib.c

https://sourceware.org/git/?p=glibc.git;a=commit;h=f0be25b6336db7492e47d2e8e72eb8af53b5506d
https://sourceware.org/git/?p=glibc.git;a=commit;h=af85385f311c574590381f7897461643f8a2fe6f

This causes the following build error:
```
../src/CoreCLREmbedding/json/casablanca/include/cpprest/asyncrt_utils.h:44:10:
fatal error: xlocale.h: No such file or directory #include <xlocale.h>
```

**Comment by agracio** [comment]
This has been addressed in `edge-js` repo: https://github.com/agracio/edge-js/pull/41
