### ISSUE TITLE
Dentrix API: How to connect to Dentrix API using Node.js

### ISSUE THREAD

**Issue by dipakdeshmukh-tudip** [tjanczuk/edge#649]
Is there any way we can connect to Dentrix using Node.js or Javascript. I found a huge documentation about Dentrix after login, but I am not getting the way to connect using Javascript.

I have found several ways to connect using ODBC, but I am a newbie in the Java. So I am looking for NodeJS based connections.

What I am trying to do here is, I want to connect to the Dentrix database and do some CRUD operations.

I downloaded the Dentrix sample code from the website but the code is in C#.

Login >> Resources >> Archived Downloads >> Dentrix sample code

**Comment by grumpyshave** [comment]
hi did you ever found a way to connect to dentrix via any coding or any api's thanks a bunch if you have anything to share with us
