### ISSUE TITLE
Scripting Node.js from Core - current state

### ISSUE THREAD

**Issue by KillyMXI** [tjanczuk/edge#651]
Readme says "coming soon"™.
Considering the currently stalled state of development it doesn't look promising.

I found this project looking exactly for this feature. Now I'm trying to figure my further steps.

What are the blocking issues? Is someone working on them? Where to look to estimate if I'm able to provide some PRs to move this feature forward?

Are there any alternatives and workarounds? I only need to use Node.js from .NET Core project. Windows only so far, but I'm not really keen of re-targeting back from Core.

**Comment by agracio** [comment]
You are welcome to submit PR, but if it was a simple issue it would have been solved already.
Take a look at this solution: https://github.com/aspnet/JavaScriptServices

**Comment by KillyMXI** [comment]
To make a difficult task more approachable someone better to describe it at least.

Will take a look, thanks.
