### ISSUE TITLE
Could not load file or assembly 'xx.dll' or one of its dependencies. The specified module could not be found.

### ISSUE THREAD

**Issue by yt888** [tjanczuk/edge#654]
var invoke1=edge.func({
  assemblyFile:"xx.dll",
  typeName:"namespace",
  methodName: "function"  
})
invoke1("",function(err,result)
{
  if (err) throw err;
  console.log(result);
});

Exception:

Error: Could not load file or assembly 'xx.dll' or one of its dependencies. The specified module could not be found.
    at Object.exports.func (E:\Workspace\WebStorm\express-master\node_modules\_edge@7.10.1@edge\lib\edge.js:169:17)
    at Object.<anonymous> (E:\Workspace\WebStorm\express-master\abc1.js:21:18)
    at Module._compile (module.js:571:32)

there are two dlls : xx.dll  ,    xxx.Core.dll.
 xx.dll refers from xxx.Core.dll
But when i used the edge node , it was wrong when it loaded the dlls
who can help me ?

**Comment by kapilepatel** [comment]
Any update on this?
