### ISSUE TITLE
npm install edge  - node ./tools/install.js  throws "The specified module could not be found"

### ISSUE THREAD

**Issue by mreis1** [tjanczuk/edge#657]
I'm opening this issue even I this might be related to: https://github.com/tjanczuk/edge/issues/583

The thing is that the issue above doesn't mention any problems concerning the install. 
Since this is a very frustrating issue I'll explain each attempt made to find a solution below. 

I've two windows machines where both machines have > .NET 4.5 installed.  One of them has the windows build tools installed and other stuff since it's my main dev machine.  The other didn't have this type of tools installed but I decided to install to discard the hypothesis that the error could be caused by the lack of these tools. In the end, the problem wasn't that and running `npm install edge` fails in my staging machine with the following error message:

```
> edge-js@10.3.1 install C:\Program Files (x86)\My Programs\pkg-test\p
kg-test\node_modules\edge-js
> node tools/install.js

***************************************
Error: The specified module could not be found.
\\?\C:\Program Files (x86)\My Programs\pkg-test\pkg-test\node_modules\
edge-js\lib\native\win32\x64\8.11.2\edge_nativeclr.node
    at Object.Module._extensions..node (module.js:672:18)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Program Files (x86)\My Programs\pkg-test
\pkg-test\node_modules\edge-js\lib\edge.js:54:8)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
***************************************
Success: platform check for edge.js: node.js x64 v8.9.4
npm WARN pkg-test@1.0.0 No description
npm WARN pkg-test@1.0.0 No repository field.
```

I also attempted to copy a project that is running in my dev machine (both machines have the same node version)  to the staging machine but I still get a similar error: 

This is the helloworld.js script that I'm running in both machines.

```js
var edge = require('edge-js');

var helloWorld = edge.func(function () {/*
    async (input) => { 
        return ".NET Welcomes " + input.ToString(); 
    }
*/});

helloWorld('JavaScript', function (error, result) {
    if (error) throw error;
    console.log(result);
});
```

And this is the error that is coming up

```
C:\Program Files (x86)\My Programs\pkg-test\pkg-test>node helloworld.js
module.js:672
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Program Files (x86)\My Programs\pkg-test\pkg-test\node_modules\
edge-js\lib\native\win32\x64\8.11.2\edge_nativeclr.node
    at Object.Module._extensions..node (module.js:672:18)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Program Files (x86)\My Programs\pkg-test
\pkg-test\node_modules\edge-js\lib\edge.js:54:8)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
```

**Comment by mreis1** [comment]
Solved after format + install of windows 7 sp1.

**Comment by dreamdevil00** [comment]
You have to install Microsoft Visual C++ redistrbutable package 2015 or later . Hope this will help some one.

**Comment by mreis1** [comment]
In my case those dependencies were installed but still it didn't work.

**Comment by dreamdevil00** [comment]
It seems that your NodeJS version is 8.11.2, release v8.2.1 supports NodeJS 8， but the npm package is still 7.10.1. I installed the release v8.2.1 in github without problems. Have a try.
