### ISSUE TITLE
Unable to build edge... gyp err recipe for target 'lib/bootstrap/project.lock.json' failed

### ISSUE THREAD

**Issue by ghost** [tjanczuk/edge#662]
I'm trying to rebuild an old project and edge is barfing on up this stack trace.    The version of edge is ^6.5.1.    Here is the stack trace...   make: Entering directory '/home/user/Documents/aad-application-service-node/AADApplicationServiceNode/node_modules/edge/build'
 ACTION binding_gyp_build_managed_target_restore_bootstrap_packages lib/bootstrap/project.lock.json
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
build_managed.target.mk:13: recipe for target 'lib/bootstrap/project.lock.json' failed
make: *** [lib/bootstrap/project.lock.json] Error 1
make: Leaving directory '/home/user/Documents/aad-application-service-node/AADApplicationServiceNode/node_modules/edge/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.nvm/versions/node/v6.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-130-generic
gyp ERR! command "/home/user/.nvm/versions/node/v6.9.0/bin/node" "/home/user/.nvm/versions/node/v6.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/user/Documents/aad-application-service-node/AADApplicationServiceNode/node_modules/edge
gyp ERR! node -v v6.9.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

Any ideas on how I can get past this?

**Comment by agracio** [comment]
Updated project can be found at https://github.com/agracio/edge-js
