### ISSUE TITLE
The edge native module is not available at ' + builtEdge

### ISSUE THREAD

**Issue by ghost** [tjanczuk/edge#664]
Just tried to install edge
```
npm install edge
npm install edge-py
```
and then run the python example:

```
var edge = require('edge');

var hello = edge.func('py', function () {/*
    def hello(input):
        return "Python welcomes " + input

    lambda x: hello(x)
*/});

hello('Node.js', function (error, result) {
    if (error) throw error;
    console.log(result);
});
```
But I am getting the following error:

> Error: The edge native module is not available at /home/user/code/node_modules/edge/build/Release/edge_coreclr.node. You can use EDGE_NATIVE environment variable to provide alternate location of edge.node. If you need to build edge.node, follow build instructions for your platform at https://github.com/tjanczuk/edge

**Comment by gamooga-echoabhishek** [comment]
Even I am facing the same issue EDGE_NATIVE is not there.
Though when I run the docker container everything runs smoothly

```
home/arora/CADENZA/Gamooga/Projects/jasmine/custom_scripts/services/encryption/node_modules/edge/lib/edge.js:34
    throw new Error('The edge native module is not available at ' + builtEdge 
    ^

Error: The edge native module is not available at /home/arora/CADENZA/Gamooga/Projects/jasmine/custom_scripts/services/encryption/node_modules/edge/build/Release/edge_coreclr.node. You can use EDGE_NATIVE environment variable to provide alternate location of edge.node. If you need to build edge.node, follow build instructions for your platform at https://github.com/tjanczuk/edge
```

**Comment by avneet-01** [comment]
@gamooga-echoabhishek @saitam1 Were you able to resolve this issue? I am also getting this error in Azure VM with Ubuntu OS:

throw new Error('The edge native module is not available at ' + builtEdge
    ^

Error: The edge native module is not available at /home/lincoln_9.3/ccr/node_modules/edge-js/build/Release/edge_coreclr.node. You can use EDGE_NATIVE environment variable to provide alternate location of edge.node. If you need to build edge.node, follow build instructions for your platform at https://github.com/agracio/edge-js
    at Object.<anonymous> (/home/lincoln_9.3/ccr/node_modules/edge-js/lib/edge.js:34:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/lincoln_9.3/ccr/expserver.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

**Comment by skokeh** [comment]
any solution guys

**Comment by avneet-01** [comment]
> any solution guys

Working fine when tried with Windows VM.
