### ISSUE TITLE
Compiler flags

### ISSUE THREAD

**Issue by lordbah** [tjanczuk/edge#667]
Is there a way to cause edge to compile C# code on the fly with the /unsafe flag?

**Comment by TheNak976** [comment]
same issue, help pls...

**Comment by lordbah** [comment]
I never found an answer. However I was able to compile the assembly in Visual Studio with /unsafe and use edge.func('path/to/dll').

**Comment by agracio** [comment]
This is correct to use any compiler flags, .csproj settings etc C# code should be first compiled into dll.
