### ISSUE TITLE
Does Edge.js Support v9+ of Node.js

### ISSUE THREAD

**Issue by shagemey** [tjanczuk/edge#669]
I'm looking to make use of the new higher datatype size limits in Node.js v9+ with an Edge.js project. Can someone tell me if Edge.js has been updated to be compatible with Node.js v9+ yet? Or is Node.js 8.2.4 still the highest compatible version?

**Comment by agracio** [comment]
https://github.com/agracio/edge-js supports Node.js up to version 10.x. Version 11.x coming soon

**Comment by shagemey** [comment]
Very good! Thank you.
