### ISSUE TITLE
Call C# from node 

### ISSUE THREAD

**Issue by BobFrankston** [tjanczuk/edge#670]
I tried "npm install edge" to use C# from a node project but it complained about the lack of a solution file (SLN?). Are there any examples of a project so I don't need to guess.

Sorry that there doesn't seem to be ongoing support. Being able to write node extensions in C# would be invaluable.

**Comment by darkworks** [comment]
ya same issue here it not building . not sure why not they prebuild these projects , very annoying

**Comment by agracio** [comment]
Updated project can be found here: https://github.com/agracio/edge-js.
