### ISSUE TITLE
Trying to run node from .NET

### ISSUE THREAD

**Issue by pekempy** [tjanczuk/edge#681]
Hi all,

I'm trying to write a c# server to, for example, control lightbulbs.

This package works to control them: https://www.npmjs.com/package/tplink-lightbulb

But I'm having a lot of trouble writing a method using Edge.JS to run a command such as 
`tplight off 192.168.1.14` (turn off the lightbulb assigned to that IP)

Looking at the readme it requires a func with a data/callback pair - is anyone able to help me out how to use the external npm package (which I have installed separately) and how to run that one line of code

**Comment by vinojash** [comment]
Did you check the below link already ?
https://github.com/tjanczuk/edge#how-to-use-external-nodejs-modules

**Comment by pekempy** [comment]
I did, it didn't seem to send the command at all. I've gone for an alternative method
