### ISSUE TITLE
Add support for the latest LTS 12.x

### ISSUE THREAD

**Issue by liudonghua123** [tjanczuk/edge#695]
Hi, the latest support version of node is 8.x now, it was too old. Please update to support the latest LTS 12.x.

**Comment by bsivanov** [comment]
Yes, I was thinking the same. @tjanczuk, is the project (kind of) abandoned? What is the last supported version of Node.js, from the commit history it seems it's 8.2.1, and that happened more than two years ago? Should it be too hard to port this to the newest versions - judging from commit adding the support, it seems kind of easy - but are you aware of any blockers? Will you accept pull requests and have time to release new versions, publishing them to npm and nuget.org?

P. S. I am not judging in any way, I just saw the project and I like it, and I want to clear the status of it.

**Comment by agracio** [comment]
You can use https://github.com/agracio/edge-js that is precompiled for latest NodeJs versions.
