### ISSUE TITLE
Uncaught Error: Cannot find module 'project path\node_modules\electron\dist\resources\electron.asar\renderer\native\win32\x64\12.8.1\edge_nativeclr'

### ISSUE THREAD

**Issue by chiyusen** [tjanczuk/edge#700]
node  v12.14.0
electron v7.1.2
install edge success,then start,have a problem about edge_nativeclr.
![image](https://user-images.githubusercontent.com/49776323/71332096-da29ee00-256f-11ea-9502-01a204cc9ad2.png)

I hope to get your help
thanks

**Comment by tritrancs** [comment]
I got same issue with electron-edge-js
May relate to this https://github.com/agracio/electron-edge-js/issues/39
