### ISSUE TITLE
The edge module has not been pre-compiled

### ISSUE THREAD

**Issue by SPDEVGUY** [tjanczuk/edge#701]
The edge module has not been pre-compiled for node.js version v12.15.0. You must build a custom version of edge.

Lazy.

Can you please make an action part of npm install edge to run the following command:

./tools/build.bat release [latestBuildVersionFromNode // node -v]

Right now this is an extra developer action as part of setting up dev env and could easily be automated on your part.

**Comment by FremyCompany** [comment]
@SPDEVGUY Hey, small question. I tried to build for v12.16.1 but get the following error:
```
c:\users\franc\__projects__\seebrow\node_modules\edge\src\dotnet\edge.h(53): error C2872: 'Task': ambiguous symbol (compiling source file ..\src\dotnet\persistentdisposecontext.cpp) [C:\Users\franc\
__PROJECTS__\Seebrow\node_modules\edge\build\edge_nativeclr.vcxproj]
  c:\users\franc\__projects__\seebrow\node_modules\edge\src\dotnet\edge.h(53): note: could be 'System::Threading::Tasks::Task' (compiling source file ..\src\dotnet\persistentdisposecontext.cpp)      
  c:\users\franc\.node-gyp\12.16.1\include\node\v8-platform.h(23): note: or       'v8::Task' (compiling source file ..\src\dotnet\persistentdisposecontext.cpp)
```

Are you facing the same problem now?

**Comment by agracio** [comment]
You can use https://github.com/agracio/edge-js that comes precompiled with new versions of NodeJs.
