### ISSUE TITLE
install option other than via nuget (edgejs with unity)

### ISSUE THREAD

**Issue by grzesiekmq** [tjanczuk/edge#703]
What is the other install option instead of nuget package.
I want to use .dll file assume EdgeJs.dll into Unity in Assets/plugins
so due to this I can make it work with typing `using EdgeJs;`
Because unity not supports nuget I want other install option

**Comment by ttay24** [comment]
You can try using NuGet package manager for Unity to pull this in:
https://github.com/GlitchEnzo/NuGetForUnity
