### ISSUE TITLE
Edge parameter passing problem (I need to pass multiple parameters)

### ISSUE THREAD

**Issue by 1006569910** [tjanczuk/edge#705]
Hi, I'm using edge recently. But I had a problem recently. I need to pass more than one parameter when I call a DLL written in c# with edge.js.

method：
`const Test = edge.func({
  assemblyFile: path.resolve("D://WmLibrary.dll"),
  typeName: "WmLibrary.BasicClass",
  methodName: "Test"
});
Test('test','127.0.0.1',3030, function(err, val) {
        if (err) throw err;
        console.log(val);
      });`

error ：
Error in v-on handler: "System.Reflection.TargetParameterCountException: Parameter counts do not match。"

c#：
`using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;
using wmsocket;

namespace WmLibrary
{
	public class BasicClass
	{
		private DataPacket dp = new DataPacket();

		private BasicSocket bsk = new BasicSocket();

		[DebuggerStepThrough, AsyncStateMachine(typeof(BasicClass.<Test>d__2))]
		public Task<object> Test(object value, object ohost, object oport)
		{
			BasicClass.<Test>d__2 <Test>d__ = new BasicClass.<Test>d__2();
			<Test>d__.<>4__this = this;
			<Test>d__.value = value;
			<Test>d__.ohost = ohost;
			<Test>d__.oport = oport;
			<Test>d__.<>t__builder = AsyncTaskMethodBuilder<object>.Create();
			<Test>d__.<>1__state = -1;
			AsyncTaskMethodBuilder<object> <>t__builder = <Test>d__.<>t__builder;
			<>t__builder.Start<BasicClass.<Test>d__2>(ref <Test>d__);
			return <Test>d__.<>t__builder.Task;
		}

		private void Bsk_OnHeart(object obj)
		{
			Log.WriteLog("发送心跳包");
			try
			{
				this.bsk.SendData(this.dp.createPacket(new byte[]
				{
					5
				}, Encoding.UTF8.GetBytes("12")));
			}
			catch
			{
			}
		}

		private void bsk_OnSocketClose(object obj)
		{
			Log.WriteLog("连接关闭");
		}

		private void bsk_OnConnOk(object obj)
		{
			Log.WriteLog("服务器端连接成功");
		}

		private void bsk_OnReadData(object arg1, byte[] data)
		{
			try
			{
				List<SocketData> list = this.dp.formatData(data);
				bool flag = list != null && list.Count > 0;
				if (flag)
				{
					for (int i = 0; i < list.Count; i++)
					{
						SocketData socketData = list[i];
						Log.WriteLog("收到数据包" + socketData.Command.ToString());
						byte command = socketData.Command;
					}
				}
			}
			catch (Exception ex)
			{
				Log.WriteLog("ClientAction Start方法 出现异常，具体情况如下:" + Environment.NewLine + ex.Message);
			}
		}
	}
}`

**Comment by prasanna4567** [comment]
@tjanczuk 
How can we do this when we have no option of sending all the parameters as a json and parsing it on C# side ?

**Comment by pmahend1** [comment]
Same here, I want to pass multiple parameters , looks like `ffi` has way for that. Looking the code in double-edge looks like it mandates to accepts only one parameter.

```js
var initialize = edge.func({
    assemblyFile: __dirname + '\\..\\EdgeJs.dll',
    typeName: 'EdgeJs.Edge',
    methodName: 'InitializeInternal'
});

var compileFunc = function (data, callback) {
    var wrapper = '(function () { ' + data + ' })';
    var funcFactory = eval(wrapper);
    var func = funcFactory();
    if (typeof func !== 'function') {
        throw new Error('Node.js code must return an instance of a JavaScript function. '
            + 'Please use `return` statement to return a function.');
    }

    callback(null, func);
};
```

**Comment by JuntaoXu** [comment]
using edge-electron-js, passing parms using JSON solved my issue

**Comment by agracio** [comment]
Edje.Js accepts multiple parameters without the need to use JSON, here are some examples.

#### Inline

```js
const edge = require('edge-js');

var hello = edge.func(function () {/*
    async (dynamic input) => { 
        return ".NET Welcomes " + input.firstName + " " + input.lastName; 
    }
*/});

hello({firstName: 'John', lastName: 'Smith'}, function (error, result) {
    if (error) throw error;
    console.log(result);
});
```

#### C# class with js call

```cs
public async Task<object> Test(dynamic input)
{
   var value = input.value.ToString();
   var ohost= input.ohost.ToString();
   // no need to convert to int
   int opost= input.oport;
   // code here
}
```

```js
const edge = require('edge-js');

const test = edge.func({ 
   assemblyFile: path.resolve("D://WmLibrary.dll"), 
   typeName: "WmLibrary.BasicClass", 
   methodName: "Test" }); 
     
test({value: 'test', ohost: '127.0.0.1', oport: 3030}, function(err, val) { 
   if (err) throw err; 
   console.log(val); 
});
```
