### ISSUE TITLE
There was an error when I ran demo code！

### ISSUE THREAD

**Issue by junbao520** [tjanczuk/edge#712]
There was an error when I ran this code！
var edge = require('edge');

var helloWorld = edge.func(function () {/*
    async (input) => { 
        return ".NET Welcomes " + input.ToString(); 
    }
*/});

helloWorld('JavaScript', function (error, result) {
    if (error) throw error;
    console.log(result);
});

**Comment by agracio** [comment]
If the issue is still relevant raise it in https://github.com/agracio/edge-js. However you would need to provide more details.
