### ISSUE TITLE
Edge-js not getting installed on Azure VM Ubuntu 20.4

### ISSUE THREAD

**Issue by avneet-01** [tjanczuk/edge#724]
I'm unable to install Edge-js on my Azure VM Ubuntu 20.4 due to - "**MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.**". 

![image](https://user-images.githubusercontent.com/74612853/146068150-5416fc66-cedd-448c-82fe-bfe845e1f748.png)

Installed .NET Core 3.1:

![image](https://user-images.githubusercontent.com/74612853/146068302-9c1706fd-ef30-4df2-8712-439840ff5b82.png)

Experts please let me know if other then the pre-requisities, is there anything else that I need to do before installing edge-js on Ubuntu??? Thanks in advance!
@tjanczuk  @lstratman @bmavity @alexbeletsky @dthorpe @dbaeumer @bbaia @dpolivy

**Comment by agracio** [comment]
You need to use https://github.com/agracio/edge-js
