### ISSUE TITLE
Will Edge.js NuGet package works with .net 6.0

### ISSUE THREAD

**Issue by satya023** [tjanczuk/edge#731]
Hi,

I am looking for a way to invoke my methods inside the dll using java script and i came across edge-js. It was working fine with the versions of dotnetcore1 and net467. But the dll i want to invoke is in .net6.0 and getting the below error
 **Error: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxx or one of its dependencies. The system cannot find the file specified at exports.func (Path\edge-js\lib\edge.js:178:17)**

Is there way around to invoke this .net6.0 version dll using edge-js? or are there any other libraries that does the job. Thanks in advance

**Comment by agracio** [comment]
Unfortunately adding support for .NET Core is very complicated and is not planned at this point. Any new Issues should be raised in https://github.com/agracio/edge-js
