### ISSUE TITLE
Added into awesome directory

### ISSUE THREAD

**Issue by robinrodricks** [tjanczuk/edge#734]
Congrats!

You just got listed in the awesome-node directory!

https://github.com/sindresorhus/awesome-nodejs#cross-platform-integration

Regards, Robin

**Comment by robinrodricks** [comment]
Be sure to let me know if you know any similar projects that can fit in the same category.

**Comment by Heartnett** [comment]
The project seems inactive/unmaintained. At the time of writing this, the last release (v8.2.1) was 6 years ago. Ideally you would add an actively maintained fork (if any) of this project to that awesome list.

**Comment by robinrodricks** [comment]
Let me know if you find an active fork.

**Comment by agracio** [comment]
Active fork here: https://github.com/agracio/edge-js
