### ISSUE TITLE
Activating extension 'undefined_publisher.newextension' failed: The specified procedure could not be found. \\?\s:\Work\VSExtension\node_modules\edge-js-up\lib\native\win32\x64\18.14.0\edge_nativeclr.node.

### ISSUE THREAD

**Issue by Mgkatkar** [tjanczuk/edge#735]
I am facing above issue while I am trying to run extension project in VS code and I am using edge-js-up for adding .net library into that project .
Basic requirement is in extension project , I wanted to add C# library and use the classes from that into extension project .
My configuration below- 
Node.js 19.9.0		
npm 9.6.3
edge-js-up = 9.6.3

I have tried with same edge, edge.js,edge-js and now edge-js-up.
Can someone help me to resolve this issue.

Any help would be appreciated.

**Comment by agracio** [comment]
If you looking for support for `edge-js` then you need to post your questions in the respective github repo.

**Comment by agracio** [comment]
VS Code is built using Electron, to build extensions for it use https://github.com/agracio/electron-edge-js
