### ISSUE TITLE
Why this asyncronous function call is blocking?

### ISSUE THREAD

**Issue by yuriykashin** [tjanczuk/edge#74]
``` JavaScript
var edge = require('edge');

var f = edge.func(function(){/*
  async (input) => {
    System.Threading.Thread.Sleep(1000);
    return input.ToString();
  }
*/});

f('two', function (error, result) {
  console.log(result);
});
console.log('one');
```

The code above outs:

```
two
one
```

I've expected it to be:

```
one
two
```

Why so?

This version runs as expected (really non-blocking):

``` JavaScript
var edge = require('edge');

var f = edge.func(function(){/*
  async (input) => {
    return await Task.Run<object>(async () => {
        System.Threading.Thread.Sleep(1000);
        return input.ToString();
    });
  }
*/});

f('two', function (error, result) {
  console.log(result);
});
console.log('one');
```

But I can not run it in synchronous manner:

``` JavaScript
f('smth', true)
```

It throws: _System.InvalidOperationException: The JavaScript function was called 
synchronously but the underlying CLR function returned without completing the Task. Call the JavaScript function asynchronously._

How to make same code being able to be called sync and async (really async)?

**Comment by camhart** [comment]
I found this issue to be extremely helpful.  Having it in the read me would have helped me.
