### ISSUE TITLE
Building on node 0.11.6

### ISSUE THREAD

**Issue by chvck** [tjanczuk/edge#86]
I'm using some of the harmony features in node 0.11.x in my application and when I install edge it reports that I'm using an unsupported version (as expected) and to do a manual build. I have been trying to do a manual build but it fails every time. I have vs2012 and .net4.5 installed. Are there any plans to support 0.11.x?

The output from build is:

Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  clrfuncreflectionwrap.cpp
  edge.cpp
  nodejsfunc.cpp
  nodejsfuncinvokecontext.cpp
  clrfunc.cpp
  persistentdisposecontext.cpp
  utils.cpp
  clractioncontext.cpp
..\src\edge.cpp(17): error C2660: 'v8::Persistent<T>::New' : function does not
take 1 arguments [C:\Users\Administrator\Documents\GitHub\exony-sql-server\node
_modules\edge\build\edge.vcxproj]
          with
          [
              T=v8::Function
          ]
..\src\edge.cpp(20): error C2664: 'node::NODE_SET_METHOD' : cannot convert para
meter 3 from 'v8::Handle<T> (__cdecl *)(const v8::Arguments &)' to 'v8::Functio
nCallback' [C:\Users\Administrator\Documents\GitHub\exony-sql-server\node_modul
es\edge\build\edge.vcxproj]
          with
          [
              T=v8::Value
          ]
          Incompatible calling conventions for UDT return value
  v8synchronizationcontext.cpp
..\src\nodejsfunc.cpp(23): error C2660: 'v8::Persistent<T>::New' : function doe
s not take 1 arguments [C:\Users\Administrator\Documents\GitHub\exony-sql-serve
r\node_modules\edge\build\edge.vcxproj]
          with
          [
              T=v8::Function
          ]
..\src\nodejsfuncinvokecontext.cpp(71): warning C4996: 'v8::FunctionTemplate::N
ew': was declared deprecated [C:\Users\Administrator\Documents\GitHub\exony-sql
-server\node_modules\edge\build\edge.vcxproj]
          C:\Users\Administrator\.node-gyp\0.11.6\deps\v8\include\v8.h(3358) :
  see declaration of 'v8::FunctionTemplate::New'
..\src\nodejsfuncinvokecontext.cpp(78): error C2248: 'v8::Persistent<T>::operat
or ->' : cannot access private member declared in class 'v8::Persistent<T>' [C:
\Users\Administrator\Documents\GitHub\exony-sql-server\node_modules\edge\build\
edge.vcxproj]
          with
          [
              T=v8::Function
          ]
          C:\Users\Administrator\.node-gyp\0.11.6\deps\v8\include\v8.h(784) : s
  ee declaration of 'v8::Persistent<T>::operator ->'
          with
          [
              T=v8::Function
          ]
  clrfuncinvokecontext.cpp
..\src\clrfunc.cpp(41): error C2660: 'v8::Persistent<T>::New' : function does n
ot take 1 arguments [C:\Users\Administrator\Documents\GitHub\exony-sql-server\n
ode_modules\edge\build\edge.vcxproj]
          with
          [
              T=v8::Function
          ]
..\src\clrfunc.cpp(42): error C2248: 'v8::Persistent<T>::operator ->' : cannot
access private member declared in class 'v8::Persistent<T>' [C:\Users\Administr
ator\Documents\GitHub\exony-sql-server\node_modules\edge\build\edge.vcxproj]
          with
          [
              T=v8::Function
          ]
          C:\Users\Administrator\.node-gyp\0.11.6\deps\v8\include\v8.h(784) : s
  ee declaration of 'v8::Persistent<T>::operator ->'
          with
          [
              T=v8::Function
          ]
..\src\clrfunc.cpp(43): error C2664: 'void v8::Persistent<T>::MakeWeak<void>(P
*,void (__cdecl *)(v8::Isolate *,v8::Persistent<T> *,P *))' : cannot convert pa
rameter 2 from 'void (__cdecl *)(v8::Persistent<T>,void *)' to 'void (__cdecl *
)(v8::Isolate *,v8::Persistent<T> *,P *)' [C:\Users\Administrator\Documents\Git
Hub\exony-sql-server\node_modules\edge\build\edge.vcxproj]
          with
          [
              T=v8::Function,
              P=void
          ]
          and
          [
              T=v8::Value
          ]
          and
          [
              T=v8::Function,
              P=void
          ]
          None of the functions with this name in scope match the target type
..\src\clrfunc.cpp(44): error C2784: 'v8::Local<T> v8::HandleScope::Close(v8::H
andle<T>)' : could not deduce template argument for 'v8::Handle<T>' from 'v8::P
ersistent<T>' [C:\Users\Administrator\Documents\GitHub\exony-sql-server\node_mo
dules\edge\build\edge.vcxproj]
          with
          [
              T=v8::Function
          ]
          C:\Users\Administrator\.node-gyp\0.11.6\deps\v8\include\v8.h(830) : s
  ee declaration of 'v8::HandleScope::Close'
..\src\clrfunc.cpp(191): error C2882: 'Buffer' : illegal use of namespace ident
ifier in expression [C:\Users\Administrator\Documents\GitHub\exony-sql-server\n
ode_modules\edge\build\edge.vcxproj]
..\src\clrfunc.cpp(191): fatal error C1903: unable to recover from previous err
or(s); stopping compilation [C:\Users\Administrator\Documents\GitHub\exony-sql-
server\node_modules\edge\build\edge.vcxproj]
..\src\v8synchronizationcontext.cpp(63): error C2664: 'uv_unref' : cannot conve
rt parameter 1 from 'uv_loop_t *' to 'uv_handle_t *' [C:\Users\Administrator\Do
cuments\GitHub\exony-sql-server\node_modules\edge\build\edge.vcxproj]
          Types pointed to are unrelated; conversion requires reinterpret_cast,
   C-style cast or function-style cast
..\src\clrfuncinvokecontext.cpp(25): error C2660: 'v8::Persistent<T>::New' : fu
nction does not take 1 arguments [C:\Users\Administrator\Documents\GitHub\exony
-sql-server\node_modules\edge\build\edge.vcxproj]
          with
          [
              T=v8::Function
          ]
..\src\clrfuncinvokecontext.cpp(121): error C2248: 'v8::Persistent<T>::operator
 ->' : cannot access private member declared in class 'v8::Persistent<T>' [C:\U
sers\Administrator\Documents\GitHub\exony-sql-server\node_modules\edge\build\ed
ge.vcxproj]
          with
          [
              T=v8::Function
          ]
          C:\Users\Administrator\.node-gyp\0.11.6\deps\v8\include\v8.h(784) : s
  ee declaration of 'v8::Persistent<T>::operator ->'
          with
          [
              T=v8::Function
          ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Roamin
g\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:106:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:790:
12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\Administrator\\Documents\\GitHub\\exony-sql-server\
\node_modules\\edge\\tools\\\\..\\lib\\native\\win32\\x64\\0.11.6\\node.exe" "C:
\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node
-gyp.js" "configure" "build" "--msvs_version=2012" "-release"
gyp ERR! cwd C:\Users\Administrator\Documents\GitHub\exony-sql-server\node_modul
es\edge
gyp ERR! node -v v0.11.6
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
Error building edge.node release for node.js x64 v0.11.6

**Comment by tjanczuk** [comment]
Edge.js 0.10.0 that just shipped supports Node 0.12.
